- users/utils_test.py
N/A
This fixes a flaky test caused by the fact that python's `email.utils.formataddr` _conditionally_ quotes the address' name component if there's a character in there that needs to be escaped. This means that this test would fail a small portion of the time if the data generated for `User.name` contained a character that needed to be escaped, for example a period (`.`) in a person's salutation (e.g. "Mrs. Smith"). I updated the tests to instead parse the result and make sure they match the expected fields on `User`.
Tests should pass, if you want to try to reproduce this on `main` you can run `pytest users/utils_test.py -k test_format_recipient
` a few times and you should eventually hit a failure case. Running it repeatedly on this branch should always succeed.
> Fix flaky util test

- docs/configure_open_edx.md
N/A
Closes #7 
Removes all references to xpro in the documentation. Note: some of the openedx plugins still have "xpro" in their name, that will get addressed at a later date as/if needed.
N/A
> Cleaned up stale references to xpro in docs

- authentication/views.py
- mail/api.py
- mail/api_test.py
- mail/exceptions.py
- main/urls.py
- main/views.py
- static/js/containers/pages/login/LoginForgotPasswordPage.js
- static/scss/auth.scss
#39 
- Updates the forgot-password API URL to match a regex of accurate length as of Django3
- Adds an error message for the user in case the API fails
- Setup, make sure the Django version is above 3 and visit `signin/forgot-password/`.
- Add dummy MAILGUN keys which will make the email API fail or forcefully throw an error from mail/API.
- Make sure that an error message is shown to the user
- Now configure the right MAILGUN creds and visit `signin/forgot-password/`
- Make sure that the user is able to reset the password correctly
- Probably run an instance and verify the generated token length as mentioned in [here](https://github.com/mitodl/mitxonline/issues/39#issuecomment-889822686)
- Now, run this PR and make sure that the acceptance criteria mention in the ticket is met. 
**Email …
> Fix: forgot password regex failure fix and error message display

- static/js/components/TopAppBar.js
- static/js/components/TopAppBar_test.js
- static/scss/top-app-bar.scss
- static/scss/user-menu.scss
- static/scss/variables.scss
fixes #21, fixes #23 
- Adds MIT Logo branding and redirection links
- Adds styling for `Sign in` and `Create Account` buttons
- Adds styling for top app bar overall
- Add styling for the hamburger icons and menus
- Adds overlay for the nav menu list
- Incorporates different menus for authenticated and non authenticated Desktop/Moblie
- Setup `mitxonline`
- Visit HomePage
- Make sure the design matches that of Invision UI mentioned in the ticket
- Make sure mobile design matches Invision UI mentioned in the ticket
- Make sure hamburger design and links match provided Invision UI in ticket
- Majorly, just make sure the acceptance criteria is met based on both the tickets mentioned
- MITx Online setup and HomePage
**Unauthenticated Desktop**
**Authenticated Desktop**
**Authenticated Desktop …
> added styling for header logo and sign-in/create account, hamburger links

- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/flow/courseTypes.js
- static/scss/layout.scss
Fixes #50
Adds dashboard message for users with no enrollments
Log in and navigate to the dashboard page with a user that has no enrollments
- There is no course catalog, which is why the "Explore" links were left out
- The issue says to implement the user notification ("Account created!") in addition to this message in the body of the page, but that's going to be a bit more involved. I'm creating a separate issue for that and will link it to this one
> Added dashboard message for users with no enrollments

- static/scss/layout.scss
Closes #70
Adds styling to pin footer to the bottom of the page, whether there is enough content to push the footer down or not
View any page in the site and fill in/remove content to make sure that the footer is always at the bottom of the page
Before:
After:
> Added styling to pin footer to the bottom of the page

- cms/migrations/0004_add_hero_titles_image_chooser.py
- courses/serializers.py
- courses/urls.py
- courses/views/v1/__init__.py
- courses/views_test.py
- mail/api.py
Closes #4
Creates an API endpoint to add enrollments for the logged-in user
- Find or create a course run and note its id
- Open a shell and test out the endpoint:
```python
RUN_ID = <your run id>
USER_EMAIL = <your user email>
import json
from django.test.client import Client
from django.contrib.auth import get_user_model
User = get_user_model()
#
user = User.objects.get(email=USER_EMAIL)
client = Client()
client.force_login(user)
resp = client.post(
"/api/enrollments/",
data=json.dumps({"run_id": RUN_ID})
content_type="application/json",
follow=True,
)
resp
```
The request should succeed, you should have a `CourseRunEnrollment` record created, and an attempt should be made to create the enrollment in edX.
If you make the request with an invalid run id, you should get a 400 with an error …
> Added API endpoint for creating user enrollments

- cms/templates/product_page.html
- static/scss/product-details.scss
relevant tickets #61 
Fixes styling issue on auth pages.
Steps for manual testing
- Open SingIn page and verify auth container Is of valid size.
- Open Forgot Password Page and verify auth container is of valid size.
Desktop Screen Shots:
Mobile Screen Shots:
> excluded .container class from .auth-page elements

- static/js/containers/App.js
#72 
- Makes the dashboard accessible to authenticated users only
- If the user visits `/dashboard` without login, he is redirected to the login page with `next` path to dashboard
- Make sure you are logged out
- Visit `/dashboard`
- You should be redirected to the login page with `signin/?next=dashboard` redirect
- Confirm that you are redirected to the dashboard when you signing now
> fix: made dashboard accessible only when authenticated

- mail/templates/email_base.html
ticket #62 
Changed image source url from mit-logo.png to mit.png as mit-logo.png is unavailable.
- Sign Up with a new user.
- Verify an image is visible in verification email.
- mit-logo.png is unavailable however mid.png.So I moved forward with it. The the only difference
between them is of size 
- During testing on local dev environment the image is still not visible but that is due to gmail image proxy.
It rewrites image src with its proxy server url and is unable to fetch the image from a local machine.
It should be testable on RC or any deployed instance.
Screent Shot:
> changed image src to valid image

- cms/models.py
N/A. Related to #38 
Fixes an incorrect assumption made in the initial implementation of the home page product section. That PR contained the assumption that the URL for a product page would always be the `slug` value, but that URL changed in this PR: #81.
Go to the home page in the CMS and add some featured products, publish, and visit the live home page. The product links should point to the correct URLs for the product detail pages (e.g.: `/courses/course-v1:first+course/`)
> Fixed home page product URLs

- cms/models.py
- cms/models_test.py
- cms/templates/home_page.html
- cms/templates/product_page.html
- conftest.py
- courses/serializers.py
- courses/urls.py
- courses/views/v1/__init__.py
- courses/views_test.py
- main/constants.py
- main/features.py
- main/settings.py
- main/templates/base.html
- openedx/api.py
- openedx/api_test.py
- openedx/constants.py
- static/js/components/NotificationContainer.js
- static/js/components/NotificationContainer_test.js
- static/js/components/notifications/index.js
- static/js/constants.js
- static/js/containers/App.js
- static/js/containers/App_test.js
- static/js/containers/HeaderApp.js
- static/js/containers/HeaderApp_test.js
- static/js/lib/notificationsApi.js
- static/js/lib/notificationsApi_test.js
- static/js/lib/util.js
- static/js/lib/util_test.js
- static/scss/notification.scss
- static/scss/variables.scss
Closes #34
- Allows users to enroll in course runs from the product detail page.
- Brings feature flag handling up to speed w/ other projects, and adds the `IGNORE_EDX_FAILURES` feature flag, which allows the app to work with enrollments without needing a working edX instance with the correct course runs seeded.
- Adds a mechanism for showing user notifications that originate from outside of the React app context (in this case, the mechanism is used to show a success message when the enrollment succeeds, and it should be applicable for showing a success message when a user first authenticates – #69)
This can be tested with or without an edX instance running with matching course runs in its database. To test _without_ edX, you can set `FEATURE_IGNORE_EDX_FAILURES=True` in your `.env`
1. …
> Implemented enrollment and notification from product detail

- main/utils.py
- main/utils_test.py
- pytest.ini
Fixes #111 
This updates `get_js_settings` to return the recaptcha key since all of the other code expects it to be there.
- Configure a V2 recaptch key (https://www.google.com/recaptcha/admin/create)
- In `.env`, set `RECAPTCHA_SITE_KEY` and `RECAPTCHA_SECRET_KEY` based on the values the admin console gives you.
- Got to the create account page, the recaptcha should render and you should be able to submit the form and receive a confirmation email.
> Fixed issues with register API and recaptcha (#111)

- static/js/components/TopAppBar.js
- static/scss/top-app-bar.scss
Tickets #83 
Fixes the following problems:
- The open/close animation on signIn and Create Account button.
- The overlay on mobile view opening, on clicking signIn create button.
Follow the bellow steps to manually test PR:
- Open home page and press sign in and/or create account buttons
- Verify they do not show open/close animation.
- Change screen to mobile view.
- verify overlay is not open 
Following are the relevant Screen shots
Desktop Screen Shot
Mobile Screen Shot
> Fixed  SignIn and Create Account style regression

- app.json
- main/settings.py
Fixes #108
Adds a setting to prevent name collisions for uploaded files (especially critical for files uploaded in Wagtail)
*NOTE:* To get this working I couldn't use my existing database, which had a bunch of CMS data from 
- Copy `AWS_` settings from RC and set `MITX_ONLINE_USE_S3=True` in your `.env`
- Run the app, and upload an image, then upload the same image again
- Navigate to the detail page for each of those images in Wagtail. Under "File:" the first image should have the same filename as the file you uploaded, and the second one should have an alphanumeric suffix attached
> Added setting to avoid name collisions in Wagtail

- static/js/components/TopAppBar.js
- static/js/components/TopAppBar_test.js
- static/js/components/UserMenu.js
fixes #120 
add dashboard, rename settings in the top bar menu
Just visit the topbar menu
> add dashboard, rename settings in the topbar menu

- cms/api.py
- cms/api_test.py
- cms/commands_test.py
- cms/conftest.py
- cms/exceptions.py
- cms/factories.py
- cms/management/commands/configure_wagtail.py
- cms/migrations/0008_move_pages_under_index.py
- cms/models_test.py
- cms/serializers.py
- cms/templatetags_test.py
- docker-compose.yml
N/A
- Changes the existing CMS data migration for setting up course index page etc. to be a no-op in favor of using the `configure_wagtail` command exclusively.
- Changes our app configuration so that the `configure_wagtail` command is run immediately after the `migrate` command, both for local development (via `docker-compose.yml`) and deployment (via [`app.json`](https://devcenter.heroku.com/articles/app-json-schema)).
Running the management command and making sure it completes successfully is a good start. 
Beyond that, the purpose of this command is to ensure that all of the Wagtail objects we care about are in the database, so the best way to test is with a fresh database. You can run the command with a fresh db and ensure that it succeeds – our custom home page is set up as the site …
> Fixed CMS migrations, added startup command to configure Wagtail

- cms/templates/home_page.html
- static/scss/home.scss
#155 
- Removes multiple `h1` tags from the homepage and keeps only now `h1`
- Removed the `alt` text from the course list on the homepage since the cards are now decorative and won't need repetitive alt names.
**Note:**
There are currently 2 `H1` elements on the Home Page. `1) Hero title` `(2 Courses Heading`. To keep only one H1 we had alternate options:
1) We already had a customized style for Hero Title's `h1` on the home page and just changing it to `h2` would let us do the job that we needed.
2) We replace `h1` with any other `h tag` in the courses heading and add a relevant style for the CSS.
I followed the approach in `point#1` since we are trying to keep common styling for all of our `h1 elements` in all the pages and the course list heading is one of them following the style …
> fix: accessibility issues on homepage

- main/context_processors.py
- main/settings.py
#148 
- Adds the missing `SITE_NAME` config variable from the Django templates
- Fixes the head titles of the pages using the site name
- Visit the home page of the web and see the head title is the one set in the `SITE_NAME` variable 
- Visit the product page and check that the head title is `{Page Name} | {Site Name}`
- Generally, other pages could also be checked to verify this change
Home Page
**Note:** For the **Before** screenshot you can visit the associated ticket
**Home Page Head**
**Product Page Head**
> fix(Accessibility): added missing SITE_NAME to context to fix head titles

- static/scss/user-menu.scss
NA
fix user name font weight in user menu
Just see the desktop user menu and see the user name there
**NOW**
**BEFORE**
> fix user name font weight in user menu

- authentication/serializers_test.py
- main/settings.py
ticket #56 
Updated Djoser setting to send a 200 response in case an email does not exist in Forgot Password Form.
- Create an Account  with a valid email.
- Enter Email in the First SignIn step
- On the `Enter Password Page` click forgot password
- Enter Invalid email and verify no email is sent
> Updated Forgot Password flow in case of email does not exist.

- static/scss/layout.scss
- static/scss/user-menu.scss
Fixes #174 
- Fixes user menu regression where overlay menu options were not visible in tablet widths
- Fixes faulty font definition for user menu in desktop width. The designs specify the same font family as all the other text on the site at slightly larger size
Set your browser window to "sm" width (≥ 576px, < 768px) and open the user menu (hamburger at the top right). Options should be visible.
> Fixed user menu visibility regression

- app.json
- courses/tasks.py
- main/settings.py
fixes #106 
Pull courserun title, dates from studio
- make a course / course run with same courseware_id both on MIT xOnline and edx-platform  e.g `course-v1:edX+DemoX+Demo_Course`
- then run management command / celery tasks to run the syncs of data
- `docker-compose exec web python manage.py sync_courserun --run=course-v1:edX+DemoX+Demo_Course`
- `courses.tasks.sync_course_runs_data`
- for further details see the attached screenshots
**THROUGH MANAGEMENT COMMAND**
**THROUGH CELERY TASK (CALLING MANUALLY / SCHEDULED)**
**BEFORE SYNCING**
**AFTER SYNCING**
> Pull courserun title, dates from studio

- authentication/templates/profile.html
- authentication/templates/register.html
- cms/templates/product_page.html
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/scss/dashboard.scss
- static/scss/product-faculty-members.scss
- static/scss/variables.scss
#171 
- Fixes the accessibility on the Product detail page
- Fixes accessibility on the Dashboard page
**Note for Reviewer:**
- Lighthouse complains about descending order of headings to be followed for accessibility e.g. `h1->h2->h3...` But in our case, we were using `h1` and then directly `h4` so i had to make our design use the heading tag in order and for that, i had to override the style of `h4` as `h2` in the specific classes to keep the design intact as well as resolve accessibility issues by LightHouse. I'm aware of using the common `h2` style but using `h2` here as is was a notable difference
- The second complaint was the color contrast so least possible color to fix the issue in tiles.
- Open the dashboard page and check the accessibility and design. There should be no …
> fix: accessibility fixes for Product Detail page and dashboard

- static/js/components/forms/RegisterEmailForm.js
- static/js/lib/urls.js
- static/scss/auth.scss
closes #197 
- Adds a privacy policy and terms of service links on the `Create Account` page
- Visit `/create-account/` and verify that you can see the privacy policy and terms of service links there.
**Desktop Normal Mode**
**Mobile Normal Mode**
**Desktop Error Mode**
**Mobile Error Mode**
> Add privacy policy and terms of service links to register page

- static/js/components/forms/ChangeEmailForm.js
- static/js/components/forms/ChangePasswordForm.js
- static/js/components/forms/EmailForm.js
- static/js/components/forms/LoginPasswordForm.js
- static/js/components/forms/ProfileFormFields.js
- static/js/components/forms/RegisterEmailForm.js
- static/js/components/forms/ResetPasswordForm.js
- static/js/components/forms/elements/FormError.js
- static/scss/common.scss
Ticket #153 
This PR has the following changes
- Adds relevant id to input tags.
- Adds role="alert" to the FormError Component
- Adds property aria-describedby to input tags
- By using light house to test accessibility.
Light house score for local testing
> Fixed accessibility issues in Forms

- cms/constants.py
- cms/models.py
- cms/models_test.py
- cms/templates/product_page.html
- courses/factories.py
- courses/models.py
- courses/models_test.py
- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/factories/user.js
- static/js/flow/authTypes.js
- static/js/lib/courseApi.js
- static/js/lib/courseApi_test.js
- users/factories.py
- users/models.py
- users/models_test.py
- users/serializers.py
- users/views_test.py
Closes #190 
Allows admins and editors access edX courses from mitxonline even if the course run is not in progress
These scenarios all require you to be enrolled in the course run you're testing. You'll be checking all of these scenarios in (1) the dashboard, and (2) the product detail page "Enrolled" text.
An "editor" in this case is someone who is not a superuser/staff, but has access to Wagtail, which is granted by adding the "Editors" group to the user, which can be done in the user record in Django admin ("Permissions" section)
- Set the course run to have a future start date, and set your user to be non-superuser/staff, and non-editor. The dashboard and product detail pages should _not_ link you to the course in edX
- Set the course run to have a current start date and future end …
> Allowed admins/editors to access closed edX courses

- static/js/components/UserMenu.js
- static/js/components/UserMenu_test.js
N/A - Fixes bug introduced by #135 
Fixes logout link in pages that are fully rendered by React (as opposed to Wagtail pages that only have a React header)
- Log in
- Visit `/dashboard/`, `/profile/`, or any other non-CMS page and click the logout link in the user menu. It should work.
- Visit any CMS page (home, product detail). The logout link should work on those too
> Fixed logout link

- cms/templates/product_page.html
- courses/models_test.py
- static/scss/common.scss
Fixes #184 
- Changes the styling of the enroll button in the product detail page if you are already enrolled. The new styling more clearly indicates that it isn't an action button, and it follows the same sort of approach that xpro uses
- Updates the logic of the button so that it only links to the edX course if you are enrolled _and_ the course is active (start date in the past, end date in the future). 
Test the page with a course run with start/end dates in the states described above
> Fixed 'enrolled' UI on product detail page

- cms/models.py
- cms/models_test.py
N/A - fixes bug related to #207 
Fixes an bug where a user visiting the product detail page without logging in could cause a server error
In a logged-out session, visit the product detail page for a course. Test with a course that has an in-progress course run, and one with its next course run starting in the future. In both cases you should see the normal product detail page with no errors.
> Fixed logged-out bug on product detail page

- static/js/components/forms/EditProfileForm.js
- static/js/components/forms/ProfileFormFields.js
- static/js/components/forms/RegisterDetailsForm.js
- static/js/components/forms/RegisterDetailsForm_test.js
- static/js/lib/validation.js
N/A - Fixes an oversight from #202 
Removes the username field from the edit profile form. The username should only be in the form if a new account is being created (just like the password field)
- Create a new account. The register details page should have username and password, and submitting the form should successfully create the user
- Edit a user profile. The username and password fields should be omitted, and saving the form should successfully apply changes to the relevant user fields
> Removed username from profile edit form

- cms/templates/product_page.html
N/A - fixes issue with #187 
Fixes the 'enrolled' UI on the product detail page for non-admin users that are enrolled in a future course run
- Log in with a non-admin, non-editor user
- Enroll in a course run that has a future start date
- Visit the dashboard page
The "enrolled" UI should look like the screenshot in PR #187
#187 was rebased several times and it looks like that css class was removed by accident
> Fixed 'enrolled' UI regression

- openedx/api.py
- openedx/api_test.py
- openedx/management/commands/retry_edx_enrollment.py
fixes #204 
fix retry_edx_enrollment management command
Just run the command command
`docker-compose exec web python manage.py retry_edx_enrollment --run=course-v1:edX+DemoX+Demo_Course <user_email>`
It seems like everything already in place but commented out that I have addressed in my PR. I don't have configured edx-platform so I could not test it.
> fix retry_edx_enrollment management command

- authentication/api_test.py
- authentication/pipeline/user.py
- cms/migrations/0013_feature_img_aspect_ratio.py
- users/serializers.py
- users/serializers_test.py
Fixes #242 
Trims whitespace around usernames during account creation, and performs a case-insensitive match for existing usernames
- Create an account, and input a unique username with spaces around it. The saved User should have a username with whitespace trimmed
- Create an account, and input a username that matches an existing user, but change the case of some/all of the letters. You should see an error message indicating that the username already exists
> Added username whitespace trimming and case-insensitive unique validation

- cms/templates/product_page.html
- courses/api.py
- courses/serializers.py
- courses/views/v1/__init__.py
- courses/views_test.py
- static/js/containers/ProductDetailEnrollApp.js
- static/js/containers/ProductDetailEnrollApp_test.js
- static/js/entry/header.js
- static/js/flow/courseTypes.js
- static/js/lib/queries/courseRuns.js
- static/js/lib/queries/courseRuns_test.js
fixes #253 
Load enrollment status dynamically in product detail page
Just visit the course / product page
> Load enrollment status dynamically in product detail page

- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
- static/js/lib/courseApi.js
- static/js/lib/courseApi_test.js
- static/scss/common.scss
- static/scss/dashboard.scss
- static/scss/notification.scss
- static/scss/variables.scss
Closes #284
Prevents unenrollment for runs with expired enrollment period
- Enroll in at least 2 course runs for some user
- Check that the "unenroll" buttons in the dashboard still work if the course runs are within their enrollment period
- Set both course runs to have expired or future enrollment periods
- Check that the "unenroll" buttons are deactivated, and that there is a tooltip like the one shown in the screenshots when you try to hover/click it
- Also check the mobile view to make sure the tooltip shows up and looks good
> Prevented unenrollment for runs with expired enrollment period

- cms/templates/product_page.html
- static/scss/product-details.scss
fixes #296
Course product pages: If no Video URL is set, display the Feature Image
Add course on wagtail but without video but only feature image and it should be shown on video place if video not available
> Course product pages: If no Video URL is set, display the Feature Image

- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
Fixes bug related to #287 
Prevents the unenrollment period tooltip from showing up when the course run's enrollment period is active
Bring up the dot menu for an enrolled course run in your dashboard. If the enrollment period is active for that run, then the unenroll button should be enabled and there should not be a tooltip on hover/click
> Fixed tooltip behavior when enrollment period is active

- static/js/containers/ProductDetailEnrollApp.js
- static/js/containers/ProductDetailEnrollApp_test.js
fixes: #274 
The Enroll now button should only appear if there is a course that is currently open for enrolment and `enrolment start < current date`
- Create course run with start_date in future.
- visit the course page.
- Enroll now button should not be appeared.
> Fixing: 'Enroll now' button appears when 'Enrollment start' date is in the future

- scripts/test/js_test.sh
none
this changes the JS test running script to grep out a few more error messages which we don't want to fail the build.
build should pass.
> fix the build

- cms/models.py
- cms/wagtail_hooks.py
Closes #322
This PR  accomplishes the following
- Changes the display name to `{courseReadableId} | {courseTitle}` 
- Sorts the title Alphabetically
This PR can be tested by the following
- Add courses to CMS
- Verify courses title is formatted correctly 
- Verify courses are sorted properly on Explorer Page
Screenshots
##Updated Screenshots
> formatted course name and ordered them in explorer

- static/js/lib/courseApi.js
#346 
**Reviewer Note:** There were multiple conditions for a course to have the edX link from which one was that if a user has `is_editor` role he'd be able to see the course without any conditions except the edX's course URL has been added. For, other users we had a check on the end date to either `be empty or be in future`. I just removed that.
- Removes course end date check for adding enrolled course link to edX, since we won't need that check for a course to have a link in the dashboard.
- Follow the instructions on #346, to set up the enrollment. Make sure the acceptance criteria marked in the ticket fulfills.
When Enrolled course end date is in past.
> fix: enable dashboard course link when end date is in past

- cms/models.py
- main/settings.py
#351 
**Additional Note - Reviewer Note**
- While working on this, I also noticed that instead of showing the title from `CoursePage` model of wagtail, we were showing the title of the `Course` model from `courses` app. So I fixed that as well. This means updating the title of a course in `/cms/pages` should be displayed everywhere instead of the title from the Course model(Can be changed in Django Admin).
- The wagtail index search doesn't update the index of the related keys automatically, so in the case when you update the readable id of a course manually from admin after the course has been added in CMS, you'll need to run `./manage.py wagtail_update_index` so that the related `readable_id` index updates
- Adds the readable id to be part of search in wagtail
- Search any course with …
> Add readable id in searchable fields of wagtail

- ecommerce/factories.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/urls.py
- ecommerce/views/v0/__init__.py
- ecommerce/views_test.py
- main/urls.py
#305 
Adds in the REST API for Product retrieval (and adds the scaffolding for that)
Use the standard DRF API explorer (go to /api/v0/products, etc.) once at least one Product has been created (via dj-admin)
pytest tests should also pass
> Adding product subsystem apis

- requirements.in
- requirements.txt
None, It's related to a requirement that was missed in https://github.com/mitodl/mitxonline/pull/333. It adds the missing dep in requirements.in.
It's related to a requirement that was missed in https://github.com/mitodl/mitxonline/pull/333. It adds the missing dep in requirements.in.
Check the course enroll/unenroll emails
> fix: add the requirements for mitol-django-openedx

- ecommerce/models.py
- [X ] Testing
- [X ] Code is tested
none
Removes "turtle" library from the models.
This triggered a deploy failure in Heroku for rc.
> Removing import for turtle in models

- static/js/containers/pages/DashboardPage.js
- static/js/containers/pages/DashboardPage_test.js
fixes #403
allow to unenroll even after the enrollment period has past
Just enroll in a course and set enrollment end date in the past that should still allow you to unenroll the course
**NOW**
**BEFORE**
> allow to unenroll even after the enrollment period has past

- main/urls.py
- main/views.py
Fixes #302 
This fixes an error where for a 500 page, django does not pass `request` to the template context, which in turn causes the 500 page to error itself.
On the main branch, set `DEBUG: false` for the web container in `docker-compose.override.yml`. Put a `raise Exception()` in `main.views.index` and try to load the dashboard. You should see a 502 Bad Gateway from nginx.
Now, perform the same test on this branch, you should see a django served 500 page that is nicely styled.
> Fixed 500 and 404 error pages

- ecommerce/views/v0/__init__.py
- requirements.in
- requirements.txt
none atm
Updates the mitol-django-payment-gateway dependency to the latest, which fixes a bug in processor response decoding. Also fixes some spots where the app was decoding responses incorrectly.
Run a transaction through - you should be ultimately redirected back into the DRF viewer (since there's no where to go quite yet when the transaction is done) and the appropriate action should be taken for the order that was created.
> Updating payment_gateway to 1.2.2, fixing some usage errors

- static/js/containers/pages/checkout/CartPage.js
#426 
Fixes #426 
On RC, add 14.750x to the cart. The title should now wrap instead of spilling out.
> Fixing wrapping issue with long course titles (#426)

- ecommerce/models.py
- ecommerce/serializers.py
- ecommerce/urls.py
- ecommerce/views/v0/__init__.py
- main/urls.py
- static/js/constants.js
- static/js/containers/App.js
- static/js/containers/pages/checkout/OrderHistory.js
- static/js/flow/cartTypes.js
- static/js/lib/queries/cart.js
- static/js/lib/urls.js
#433 
Adds the order history screen per the specs in InVision. 
Navigate to /orders/history once you've put at least one order through the system (successful or not).
- This lacks pagination controls
- The total cost field doesn't use the formatter utility function (so too many decimals, no currency type indicator, no thousands separator, etc.)
- Will need some styling for mobile; there didn't seem to be any in InVision. Should be sorta reasonable but it's not been tested.
> Add order history screen

- static/js/containers/UpsellCardApp.js
N/A
Updates the `UpsellCardApp` to only render if the upgrade dialog feature flag is set.
- Enroll in a course
- Set `FEATURE_ENABLE_UPGRADE_DIALOG=True` and verify you see the upgrade card
- Set `FEATURE_ENABLE_UPGRADE_DIALOG=False` and verify you don't see the upgrade card
> Only show the upgrade sidebar if upgrade ui enabled

- ecommerce/models.py
- ecommerce/serializers.py
#471 
Fixes #471 
Add an item to the cart - the total display should be correct. Alternatively, add an item to the cart and hit the cart API (`api/v0/checkout/cart/`) - the discounted_price should match the total_price.
> Fix cart total display when no discounts are applied

- ecommerce/serializers.py
- ecommerce/urls.py
- ecommerce/views/v0/__init__.py
- main/urls.py
- static/js/components/CartItemCard.js
- static/js/components/OrderSummaryCard.js
- static/js/constants.js
- static/js/containers/App.js
- static/js/containers/pages/checkout/CartPage.js
- static/js/containers/pages/checkout/OrderHistory.js
- static/js/containers/pages/checkout/OrderReceiptPage.js
- static/js/containers/pages/checkout/OrderReceiptPage_test.js
- static/js/flow/cartTypes.js
- static/js/lib/queries/cart.js
- static/js/lib/test_constants.js
- static/js/lib/urls.js
- static/scss/common.scss
Fix #424
Add an order receipts page
Make sure to set up a purchasable product, create a fullfilled oder for it, got to the order summary page `/orders/history/` and click to view one of the orders.
> Adding OrderReceiptPage

- courses/api.py
- courses/api_test.py
- courses/views/v1/__init__.py
fixes #445 
fix email unsubscription inconsistency after un-erollment
- Just unsubscribe to emails before unsubscribe
- enroll back in should be subscribed back 
- that should have deleted the popout entry in edX against email subscription
> fix email unsubscription inconsistency after unenrollment

- cms/templates/home_page.html
- cms/templates/product_page.html
- cms/templates/resource_page.html
- ecommerce/templates/checkout_interstitial.html
- main/templates/404.html
- main/templates/500.html
- main/templates/base.html
- static/js/containers/App.js
fixes #419 
Accessibility: Bypass Blocks: bypass the header on site pages for screen readers
just use the screen reader tool to see if it loads Skip to main content link and on clicking that link screen reader should start from the main content
**With Screenreader**
**Without Screenreader**
> Accessibility: Bypass Blocks: bypass the header on site pages for screen readers

- ecommerce/admin.py
- ecommerce/factories.py
- ecommerce/forms.py
- ecommerce/models.py
- ecommerce/models_test.py
- ecommerce/templates/admin/ecommerce/change_form.html
- ecommerce/templates/admin/ecommerce/refund_control_row.html
- ecommerce/templates/refund_order_confirm.html
- ecommerce/templatetags/refund_controls.py
- ecommerce/urls.py
- ecommerce/views/v0/__init__.py
#465 
#456 
Adds ability to refund orders in Django Admin. Also updates the fulfill code to keep local enrollments when enrollments in edX fail. 
In Django Admin:
1. Find a Fulfilled Order
2. There should be a Refund Order button on the submit line
3. Clicking the button should bring up a simple form with options for reason, amount, and unenroll. Amount should be pre-filled with the purchase price of the order.
4. Leaving either reason or amount unfilled should re-render the form with an error message (in the same manner as it would in djadmin)
5. Successfully refunding the order should redirect you to the Refunded Orders list page with a success notification. A Transaction record should be created with the data being a dict of reason and amount, with their values being what was supplied …
> Handle refunded orders

- static/js/containers/pages/checkout/OrderHistory.js
- static/js/lib/queries/cart.js
- static/scss/cart.scss
#482 
Adds current page readout and Prev/Next buttons to the order history page.
As a user with <= 10 orders: 
* The Previous and Next buttons should not be functional
* The page readout should display "Page 1 of 1"
As a user with > 10 orders:
* The Previous and Next links should work as expected
* Reaching the end or beginning of the list should disable the Next or Previous link, respectively
* The page readout should display the current page and ceil(total records / 10) number of pages (i.e. 115 results = 12 pages)
> Add pagination links to the order history page

- ecommerce/models.py
- static/js/containers/pages/checkout/CartPage.js
#481 
Fixes #481 
Refer to 481 - the 500 error is due to the order object not having an "error" method, which is now resolved, so the 500 error should not be reachable anymore. In addition, the cart page now properly implements the loading screen on page load, so weirdness from half-loaded pages (noted as "sometimes the Place Order button doesn't work") should now no longer appear. 
If working locally, throttling should be applied to properly test the loading screen - otherwise the relevant API requests will likely load too fast to be testable. (I tested by setting Throttling to Slow 3G in Chrome devtools.)
> Handle error states better, fix for cart page loading status

- static/js/components/CartItemCard.js
- static/js/components/OrderSummaryCard.js
- static/js/containers/pages/checkout/CartPage.js
#493 
Adds a midpoint for the checkout page to make the transition between mobile view and full-width view better.
- Mobile view should not change at all, nor should full-width/desktop view.
- In between, the view changes to stack the cart items on top of the cart summary, and adds back in the "You are about to purchase" header. The card items display using the desktop-style view (small image on left, text on right) rather than the mobile view (image on top, text below). 
Add an item to the cart, then use the dev tools to turn on responsive view and switch between devices. You will need to cycle through between the [small, medium, and large breakpoints](https://getbootstrap.com/docs/4.6/layout/overview/) to see all three states - good choices for this in Chrome devtools are a phone …
> Add midpoint state between sm and lg to fix styling issues on cart page

- cms/models.py
#490 
- Uses the youtube controls for the youtube based videos for the closed captioning support
- Setup MitxOnline
- Add a product page
- Add a youtube URL in the video URL
- Play the video and make sure the closed captioning support is available
- Make sure that the design remains intact
(Optional)
We used [video.js](https://github.com/videojs/videojs-youtube) package in a recent PR(https://github.com/mitodl/mitxonline/pull/95) to support videos, but the closed captioning support was not added/enabled. So, we have now enabled youtube controls for that to make it similar to how it works in xPRO.
**After (Desktop)**
**After (Mobile)**
**Before (Desktop)**
**Before (Mobile)**
> refactor: use youtube controls for youtube videos

- ecommerce/views/v0/__init__.py
- static/js/containers/pages/checkout/OrderReceiptPage.js
#495  #496
* Adjusts Order History page to only show Fulfilled and Refunded orders
* Migrates styling changes (md breakpoint stuff) from the Checkout page to the Order Receipt page
* Adds sorting to the Order History page (created date, descending)
* Navigate to Order History page as a user with some orders - it should only display Fulfilled or Refunded orders, and they should be listed most recent first.
* Open the receipt page for an order and set view to something in the md breakpoint (768px <= width <= 991px). It should mirror the Checkout page. See https://github.com/mitodl/mitxonline/pull/494 for more details.
> Fixing some issues with order history/receipt views

- frontend/public/src/components/forms/ApplyCouponForm.js
fixes #516 
fix ecommerce accessibility coupon code field has no label
**BEFORE**
**NOW**
> fix ecommerce accessibility coupon code field has no label

- ecommerce/serializers.py
- ecommerce/urls.py
- ecommerce/views/v0/__init__.py
- ecommerce/views_test.py
#436 (to an extent)
Adds some simple APIs for working with discount codes via REST API. These are meant to be used for upcoming Refine development.
Navigate to /api/v0/discounts - you should be able to work through the API via the standard DRF interface.
The discount detail should also include redemptions (with detail) for the discount. 
* This is a backport of stuff I set up while testing out Refine - it made some intuitive sense to have a Refine console to manage discount codes (since they'll be used in flexible pricing). 
* These are limited to admin-level users but can be bumped down to staff or something else (depending on how we want to limit access to the Refine bits that haven't been done yet). Admin made the most sense now.
> Adds administrative discount APIs

- app.json
- frontend/staff-dashboard/src/App.tsx
- frontend/staff-dashboard/src/components/discounts/index.ts
- frontend/staff-dashboard/src/components/discounts/redemption-list.tsx
- frontend/staff-dashboard/src/components/discounts/user-assignments.tsx
- frontend/staff-dashboard/src/hooks/useAuthProvider.ts
- frontend/staff-dashboard/src/hooks/useDrfDataProvider.ts
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/discounts/create.tsx
- frontend/staff-dashboard/src/pages/discounts/edit.tsx
- frontend/staff-dashboard/src/pages/discounts/index.tsx
- frontend/staff-dashboard/src/pages/discounts/list.tsx
- frontend/staff-dashboard/src/pages/discounts/show.tsx
- main/settings.py
n/a
Adds CRUD operations for discounts to the Refine admin UI. Also adds in some infrastructure stuff:
- AuthProvider in the API that doesn't check for the CSRF token (which Refine doesn't know about)
- A DRF-aware DataProvider for Refine; this is mostly the simple data provider with a couple of methods reworked a bit to make them usable with a DRF-based API
Once the code is checked out and the refine app rebuilds, you should have a Discounts menu item on the left. Clicking that should show you the list of discounts in the system. Create button should work, as should edit and view. The view button in particular should additionally show you redemptions and assigned users (UserDiscounts) for that discount. (You can't add new UserDiscounts yet.) 
The things that needed adjustment in the data …
> Adds discounts to Refine admin

- docker-compose.override.yml
- frontend/public/src/components/CartItemCard.js
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
#523 
Hopefully the final fix for dashboard dates. 
As a user with enrollments, log in and navigate to the dashboard. The enrollments should display with the proper start date.
As a user with items in the cart, navigate to the cart. The cart items should display the course start date properly. Additional items (added manually through the Django admin) should also display properly.
A production build of the app may be useful for testing - the code works (and has worked) successfully on dev builds but failed once it was minimized.
> Reworked generateStartDateText to avoid short circuiting

- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/ecommerceTypes.js
- frontend/public/src/lib/courseApi_test.js
This will present the old form submit button if there's no product.
#561 
Fixes the Enroll Now button to enroll users if there's no product associated with the course. 
As a learner, attempt to enroll in a course that has no product. The Enroll Now button should be displayed and activating it should simply enroll you in the course (or, at least, attempt to).
> Added check to see if there's a product for Enroll button

- cms/serializers.py
- courses/serializers.py
- courses/serializers_test.py
- frontend/public/scss/dashboard.scss
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrollmentRoleTag.js
- frontend/public/src/flow/cmsTypes.js
- frontend/public/src/flow/courseTypes.js
#533 
Adds a tag to the enrolled item card on the dashboard to inform the learner of their enrollment status in the course. Adds an upgrade button if the learner is auditing the course (and there's an upgrade path). 
View the dashboard. Your audit enrollments should have a red "Enrolled in free course" and the verified enrollments should have a green "Enrolled in certificate course" badge. 
Any audit enrollments you have that have an upgrade path (i.e., there's a Product associated with them) should also show a Get Certificate button on the right side of the card. 
Enrollments with a related course page should have a link to the page at the bottom of the card. 
390w on mobile is copied from iPhone 12 Pro preset.
> Adds enrollment status and upsell button to dashboard enrollment cards

- ecommerce/constants.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- ecommerce/messages.py
- ecommerce/models.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- ecommerce/tasks.py
- ecommerce/tasks_test.py
- ecommerce/templates/mail/product_order_receipt/body.html
- ecommerce/templates/mail/product_order_receipt/subject.txt
- mail/constants.py
#532 
This is mostly a cross-port of the xPro receipt email code into MITxOnline. Upon successful payment, this will send the learner an emailed copy of their receipt. 
1. Ensure you have Mailgun credentials in your local environment, or you won't be able to send email. The credentials from RC can be used for testing.
2. Complete the payment process. 
3. You should receive an email from the system with the receipt for your purchase. It should look mostly like the email that is sent by xPro (see #532 for a screenshot of that).
Additionally, there's a pytest test for the serializer itself. You can manually send emails for other (completed) orders by loading the order and calling mail_api.send_ecommerce_order_receipt. 
Depending on the CyberSource settings, you still may get a CyberSource …
> Adds email receipts

- flexiblepricing/serializers.py
- flexiblepricing/views/v0/__init__.py
- flexiblepricing/views_test.py
- frontend/staff-dashboard/src/App.tsx
- frontend/staff-dashboard/src/hooks/useDrfDataProvider.ts
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/index.tsx
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
- main/views.py
#574 
Implements #574 - adds Flexible Pricing to the Refine admin and implements a page with status filtering. Also adds a few refinements to the DrfDataProvider (in Refine) and in the app's underlying DRF infrastructure.
Prepare a few Flexible Pricing requests. (See the documentation for this process.)
Check out and build the Refine admin, and navigate to it. Selecting the Flexible Pricing item on the left nav should pull up the flexible pricing records in the system, and the Status column should be filterable.
[Overall story](https://github.com/mitodl/mitxonline/issues/543)
[Financial Aid dashboard on MicroMasters](https://github.com/mitodl/micromasters/pull/5135) - design should basically match this.
> Adds flexible pricing list view to Refine admin

- cms/models.py
Fixes #594 
Adds a check for None in the currency field options generation code. (It checked for length > 0 but not `None` specifically.) 
Steps to reproduce are in #594 - you should see the form render successfully, and exchange rates without descriptions should render as just the currency code.
> Adds a check for exchange rate description when constructing the currency list

- .env.example
- docker-compose.yml
- frontend/staff-dashboard/src/App.tsx
#550 
Updates the Docker compose environment to pull in settings for the Refine admin from the .env file, and updates the data provider to use a variable for the data source URI rather than a hard-coded value.
The following settings can be set via `.env`:
* `MITX_ONLINE_ADMIN_CLIENT_ID`: the client ID used for OAuth2 authentication
* `MITX_ONLINE_BASE_URL`: the base URL for the MITxOnline application. (This already existed, but noting it since it's being used here now too.) 
* `MITX_ONLINE_ADMIN_BASE_URL`: the base URL for the Refine admin app
These are used in the Docker environment (and, thus, in the app) like this:
| Environment Variable | `.env` Setting Formula | Default |
| --- | --- | --- |
| `REACT_APP_OIDC_CONFIG_CLIENT_ID` | `MITX_ONLINE_ADMIN_CLIENT_ID` | …
> Allows for setting some Refine admin settings via .env

- flexiblepricing/views/v0/__init__.py
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
#575 
Adds a search pane to the Flexible Pricing admin page (in the Refine admin) to allow people to filter the request list by name. (Name, in this case, can be either full name, email address, or username.) 
Put in at least one Flexible Price request. Then, navigate to the admin and click Flexible Pricing on the left nav. You should see a Find Records card to the left of the table. Supplying a search term in the Search by Name field will limit the result list to records for the person you've filtered for (or will return no data, depending). Similarly, supplying a status in the Search by Status will limit the table to just records in that particular status. Supplying both will be performed with an AND operator. 
With results:
With no results: 
The filtering on the Status field has been …
> Adds free-form search on name fields to Flexible Pricing admin

- flexiblepricing/views/v0/__init__.py
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
fixes: #576 
fixes: #577 
PR added some front end logic for approving and resetting the flexible pricing from Refine Admin portal. A button to approve / Reset the flexible pricing option.
The statuses in the app are created, approved, auto-approved, denied, and reset. reset allows the learner to re-request flexible pricing for the given course/program.
Visit: `/flexible_pricing/` endpoint and approve and reset the status.
Video Demo --> https://watch.screencastify.com/v/8TLuJL6h6fMSOZthohvJ
> asadiqbal08/Added Approve and Reset button to Refine Admin

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/components/ReceiptPageDetailCard.js
- frontend/public/src/containers/pages/checkout/OrderReceiptPage.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/cartTypes.js
#534 
Adds a modal that is displayed when a learner attempts to unenroll from a certificate (paid) course instructing them to contact customer support, and then blocks the unenrollment.
Enroll in a certificate course. Then, attempt to unenroll from it using the dropdown menu on the Dashboard. You should be presented with a modal instructing you to contact customer support. 
Enroll in a free course. Then, attempt to unenroll from it using the dropdown menu on the Dashboard. The unenrollment should take place. 
There's no UX for this defined in InVision so just winged the copy - will be expecting changes.
> Adds message when paid learners attempt to unenroll

- requirements.in
- requirements.txt
#593 
Updates `mitol-django-payment-gateway`, `mitol-django-authentication`, `mitol-django-mail`, and `mitol-django-common`. Update to `payment_gateway` was to integrate the new username hashing code (see https://github.com/mitodl/ol-django/pull/71); the rest were upgraded to make the build work. 
All pytest tests should pass.
The username hashing can be tested by purchasing a certificate track course. The process should succeed, and the Customer ID displayed in the resulting transaction in the CyberSource EBC should show a 64-character hex string:
Additionally, set the user's username to be an email address (valid or not; it does need to contain at least an `@` and a `.` after the `@`). This will need to be done in the Django Admin. Then, purchase a certificate track course using that …
> Updates ol-django libraries

- frontend/public/src/components/UserMenu.js
- frontend/public/src/components/UserMenu_test.js
#620 
Adds an Order History link to the top nav menu.
Log into the application, then load a page (any page). The top nav menu should display an Order History link, and it should take you to `/orders/history/` when activated.
> Adds Order History to top menu

- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
fixes: #608 
As a staff member, when I change the status of a Flexible Pricing request, I'd like to provide a justification of why I am changing the status of the request. The justification should be one from a set of pre-defined justifications available in the app.
Visit the admin portal in Refine UI to test it.
> Show justification once status changed

- frontend/public/src/components/ReceiptPageDetailCard.js
fixes: #619 
Fixes the Receipt page issue when there is no discount code then the page renders empty.
Visit the receipt page with and without discount code.
> Fixes: Receipt page is empty when there is no discount code

- users/management/commands/find_username_conflicts.py
- users/management/tests/find_username_conflicts_test.py
#259 
Adds a management command to identify usernames that would conflict after normalization. This is step one of the process for resolving #259. 
The management command is `find_username_conflicts` and running it will load all user IDs and usernames from the database and run through them to see if a normalized username would be generated more than once. If the normalized username would be generated more than once, it outputs that normalized username with the IDs of the users that would cause a conflict. These can then be manually edited (in Django Admin or in the database directly). 
The command does not change usernames at all and the standard caveats apply to modifying usernames manually - they will need to be modified on the Open edX side as well. 
This command will need to be run …
> Adds management command to find possible username conflicts

- ecommerce/mail_api.py
- ecommerce/templates/mail/product_order_receipt/body.html
#638 
Fixes #638: removes some extraneous inline CSS from the email template and adjusts the send_ecommerce_order_receipt code to parse the Order's created_on (since that ends up becoming a string at some point).
Place an order. The receipt email should display the order date and should have proper spacing above the Payment Information block.
> Fixes spacing and order date on emailed receipts

- cms/models.py
- flexiblepricing/api.py
#650
Fixes #650 - pulls the learner's country from their profile when submitting their flexible pricing request so the auto-approve code has something to consider (outside of the default)
Submit a flexible pricing request for a course as a user in a country that has a threshold of < $75,000. The request should be for an income level above the threshold. It should auto-approve the request.
> Capture learner's country when saving flexible pricing request

- frontend/public/src/components/Header.js
- frontend/public/src/components/NotificationContainer.js
- frontend/public/src/components/ReceiptPageDetailCard.js
- frontend/public/src/components/TopAppBar.js
- frontend/public/src/containers/App.js
#537 
Moves the NotificationContainer component into the Header component, so screen readers will read notifications first when the page reloads (as in when a learner has completed purchasing a course). 
Verifying normal operation:
1. Log in.
2. Perform some action that generates a notification. (Going to the Dashboard and attempting to adjust Email Settings from the menu is a good choice here.) The notification should appear in the same spot it did - under the header - and should be closable. 
3. Attempt to purchase a course. The checkout process should complete successfully, and the notification should appear below the header and be closable. 
Verifying screen reader operation:
1. Log in. 
2. Enable screen reader - this was tested specifically with VoiceOver on macOS 12 and Narrator on …
> Move NotificationContainer into the Header component to assist with screen reading

- cms/models.py
#410 
Fixes wagtail warning regarding usage of `FieldPanel` instead of `StreamFieldPanel` for price field(Which is a `StremField`)
- In a course make sure you have added a price field, No move to this branch rebuild and check if the Price field on the course page still works fine.
- In a new course you can also try creating a Price field in the course through CMS and check that users can see that on the course details page.
- Check the logs and there should be no warning mentioned in the associated ticket
- Tests pass
> fix(warning): use StreamFieldPanel instead of FieldPanel

- docker-compose.yml
n/a
This makes a couple small changes to the `docker-compose.yml` file to make the services start up a bit more reliably locally:
1. Adds a healthcheck for the `watch` and `refine` containers that just pings the existing watchdog script. (This is required for the next bit for the watch container; added it to refine just for consistency.)
2. Adds a dependency on `refine` to `watch` so that they don't start up at the same time. 
After doing some troubleshooting with @annagav regarding her local instance not starting properly, I noticed that the `watch` container and the `refine` container seem to conflict with each other when they're starting up. (There's some package resolution that happens in each, and since they share the same `node_modules` folder one has a tendency to remove stuff that …
> Adds healthcheck to watch and refine containers; makes refine "depend" on watch

- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
n/a
Eliminates the filter dropdown on the Status header item and realigns the filter card to be horizontal.
Load the staff dashboard and navigate to the Flexible Pricing screen. The filter card should now run across the top of the page rather than down the left side. The Status dropdown filter in the table header should now also be removed (it was redundant).
> Adjusts Flexible Pricing dashboard to make the filters horizontal

- ecommerce/templates/mail/product_order_receipt/body.html
#619
The URL for the order receipt was bad; this tested OK locally but that was due to also having some local config set wrong. This also fixes a typo in the text ("Below you will find a copy of your receipt" vs. "Below you will find a copy of you receipt"). 
Generate a receipt email. you can do this either by creating a new order, or through the shell. (In the shell, I just import the Order model and the `send_ecommerce_order_receipt` function from mail_api and then run `send_ecommerce_order_receipt` on the last Order object to test.) The receipt link should be valid and the text immediately following it should be correct.
> Fixes link to order receipt in the email

- docs/source/configuration/open_edx.rst
Removal of out-of-date instructions.
Removes instructions in order to ensure that the reader will use the master branch for `devstack` instead of a specific version.  Removes instructions for the reader to clone the mitodl edx repo which is no longer required.
> Use master branch and don't clone mitodl edx

- docs/source/configuration/refine_admin.rst
Updates the refine admin configuration document to use the poorly formatted `//` in the redirect URL which acts as a workaround for a bug.  The bug should be fixed at some point, and this PR should be reverted after the fix is released.
Negative test - Set the redirect URL without the `//`
Positive test - Set the redirect URL with the `//` shown in this PR.
> Update refine docs to conform to poorly formatted URL

- courses/serializers.py
- ecommerce/serializers.py
- ecommerce/serializers_test.py
- frontend/public/src/constants.js
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
- frontend/public/src/containers/UpsellCardApp.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/cartTypes.js
- frontend/public/src/lib/util.js
https://github.com/mitodl/mitxonline/issues/670
Displays the course price, with the deducted flex price discount, for a logged in user who has been approved for flexible pricing.
1. Ensure you have the following already created: standard user, course, course run, flexible pricing tier, flexible price that is approved for the course and user.
3. Login to mitxonline
4. From the dashboard, click 'browse our courses'
5. Click on the course card
6. Click 'Enroll now'
7. A modal will display.  You should see the flexible pricing adjusted certificate price in the modal.
8. Click 'No thanks, I'll take the course....'
9. From the dashboard, click 'Course details'
10. You should see the flexible pricing adjusted certificate price in the card.
> Flexible pricing display personalized price

- docs/source/configuration/open_edx.rst
- nothing, this is a documentation change
n/a
Adds in the path to the file you need to edit to configure LMS settings in the Open edX config instructions.
Should be a path under "Configure MITx Online as a OAuth provider for Open edX" in the "In Open edX" section, and it should be to the right file.
> Changed to add in path to the file you need to edit for lms settings

- courses/api.py
- courses/api_test.py
- courses/serializers.py
- courses/urls.py
- courses/views/v1/__init__.py
- courses/views_test.py
#719 
Adds a new `program_enrollment` REST API that groups course run enrollments by program for the given user. Also updates the `get_user_enrollments` API function to include implicit program enrollments. 
Add an enrollment for a course run in a program. Then, visit http://mitxonline.odl.local:8013/api/program_enrollments/ - you should see the enrollment listed alongside the program that it belongs to.
> Adds code to group course run enrollment by program

- cms/models.py
- cms/models_test.py
- cms/templates/flexiblepricing/flexible_pricing_request_form.html
- flexiblepricing/models.py
- flexiblepricing/models_test.py
https://github.com/mitodl/mitxonline/issues/728
If a flexible price record has a status of 'reset', when the user visits the `http://mitxonline.odl.local:8013/courses/<COURSE>/flex-price/` they should be able to view the form fields and submit the form.
1. Create a `flexible price` record for a user and course or program.
2. Set the status of the `flex price` record to `reset`
3. Login as the user from step 1.  Navigate to `http://mitxonline.odl.local:8013/courses/<COURSE_FROM_STEP_1>/flex-price/`
4. Ensure that you can see the form and submit the completed form.
5. Ensure that a new `flexible price` record for the user and course or program has been created.
- Create a flexible price tier following: https://github.com/mitodl/hq/discussions/133
- The test at …
> 728: flexible pricing learner cant resubmit income after request has been denied reset

- frontend/staff-dashboard/src/hooks/useDrfDataProvider.ts
https://github.com/mitodl/mitxonline/issues/747
Pagination was not working within the staff-dashboard (refine). 
View a list page (such as https://<BASE_URL>/staff-dashboard/flexible_pricing) which is known to retrieve more than 10 results from the associated API.  Ensure that there are multiple pages shown in the bottom right of the list page.  Ensure that you can navigate to the other pages.
The default behavior _should_ have been that any list associated with more than 10 entries should display 10 entries on the first page and the remaining entries on subsequent pages, each showing only 10 entries.
> 747 - Fix pagination within Refine by using count API response attribute

- frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
#665
Fixes #665 - refactors the approval modal out into its own component so that the state of the approval doesn't become weird. This also refactors the dialog to use the Ant Design `<Select>` component rather than a bare HTML `select` and adds a no-choice option for requests that haven't had a justification set yet.
1. Log into the staff dashboard and navigate to the Flexible Pricing screen.
2. Attempt to change the status of a request that has a justification set. Do not change the justification. The change should succeed. 
3. Attempt to change the status of a request that has not had a justification set. Leave the justification field blank. You should receive a toast informing you to choose a justification. 
4. Change the justification of a request and save the change. The …
> Fixes error on justification field when changing a flex pricing request status 

- ecommerce/api.py
- ecommerce/models.py
- ecommerce/views/v0/__init__.py
- ecommerce/views_test.py
- frontend/public/src/constants.js
- frontend/public/src/lib/notificationsApi.js
- main/constants.py
https://github.com/mitodl/mitxonline/issues/676
Adding validation on checkout to payment view to see if user has already purchased for that course run, displaying a error message if that happens
- enroll a course on the frontend, but leave it in the cart
- go to /admin/ecommerce/order/ and find this order, manually change it to 'Fullfilled'
-  go back to frontend to enroll this course again, when you click on place your order, you should see
(Optional)
(Optional)
(Optional)
> add validation to block payment for the paid courserun

- courses/api.py
- courses/api_test.py
- courses/models.py
- courses/tasks.py
- courses/tasks_test.py
#762 
- Refactors the logic in enrollment to add a case when the free enrollment exists and user upgrades to paid
There are a couple of paths you should test it with (The enrollment should properly reflect the state as per the below scenarios):
1. A new user new enrolment _Unpaid_
2. A new user new enrolment _Paid_
3. User enrolled in _Unpaid_, now Pays and enrolles in _Paid Mode_
4. User enrolled unpaid, then _Unenrolls_, now _pays and enrolls again_
> fix: enrollment upgrade from free to paid version

- cms/serializers.py
- cms/serializers_test.py
- courses/serializers.py
- courses/serializers_test.py
- frontend/public/scss/dashboard.scss
- frontend/public/scss/product-details.scss
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
- frontend/public/src/containers/UpsellCardApp.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
Fixes https://github.com/mitodl/mitxonline/issues/677
In this PR, we have added an indication for financial assistance for the courses. Financial assistance indication is displayed on the following places:
- User Dashboard
- Course Detail Page
- Course Detail Page Upsell Modal
Follow these steps:
- Add financial assistance form for a course page in CMS by following https://github.com/mitodl/hq/discussions/133.
- Visit the course detail page and click on `Enroll` button. `Need financial assistance?` link is displayed in the popup modal.
- Enroll in the free version(audit mode) of the course.
- Visit Course Detail Page. You can see the `Need financial assistance?` link in the course upsell card.
- Visit the dashboard page from the user profile, you can see the `Financial assistance?` link …
> online-677 Indicate Financial Assistance links if available for a course

- ecommerce/serializers_test.py
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
- frontend/public/src/containers/UpsellCardApp.js
- frontend/public/src/lib/util.js
Just like James recommended in my prior PR but I never did...
https://github.com/mitodl/mitxonline/issues/770
Displays the course price in a format such as `$xxx.xx`.  
1. Login as a learner and navigate to a course that is not free
2. Click the "Enroll" button
3. A modal should appear which will display the certificate price in the top right.  Verify the price is in the correct format.
James suggested that I use `formatLocalePrice` in a prior PR and I completely forgot to ensure that I did.
Desktop:
Mobile:
> 770 - flexible pricing: too many decimal places

- authentication/pipeline/user_test.py
- authentication/views_test.py
- openedx/api.py
- openedx/api_test.py
- openedx/exceptions.py
- users/serializers.py
- users/serializers_test.py
https://github.com/mitodl/mitxonline/issues/734
Restricts a new `mitxonline` user from registering with a username that is currently taken by an OpenEdx user.  If a new `mitxonline` user attempts to use a username which is already taken by an OpenEdx user, they will be unable to submit the user registration form and presented with an error message.
1. Create an OpenEdx user with a known username.
2. Register a new user through `mitxonline` and attempt to use the same username as in Step 1.
3. Verify that you are unable to create a new user with the username from Step 1, and that you receive an error message.
If you are running `mitxonline` and `openedx` locally, you can also test out the workflow when `mitxonline` cannot connect to `openedx` by only running `mitxonline` locally.  You …
> 734 - registration validate username against openedx

- cms/templates/product_page.html
- frontend/public/scss/product-details.scss
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/entry/django.js
fixes: #767
The PR enables to select another date if available for enrollment.
- Checkout the branch.
- Visit `Course Enrollment page`.
- In `Start Date` box there should be link `More Dates` by clicking it should show the tooltip box
- In Tooltip by clicking any date should update the `Start Date` box
- Clicking on `Enroll now` should perform the Enrollment according to selected date
- If product is available in selected date of `Course Run` it should display Purchase Modal otherwise perform enrollment
- Test if you are enrolled in the selected date of `Course Run`
> Fix Issue 767: More dates for course enrollment

- micromasters_import/management/commands/queries/002_import_courserun.sql
- micromasters_import/management/commands/queries/003_import_enrollment.sql
https://github.com/mitodl/mitxonline/issues/701
This PR contains the queries need to run against MITxOnline to bring over DEDP courserun and enrollment data from MicroMaster
- Go to /admin/micromasters_import/courseid/ to map McroMaster course id to MITxOnline course for DEDP 
- run ```docker-compose run --rm web ./manage.py import_micromasters_data ```
18 courses migrated from MicroMaster RC
3 enrollments migrated
> add migration queries for courserun and enrollment

- main/settings.py
N/A - this fixes a small avoidable issue w/ configuration
This fixes the refine dashboard settings to have correct urls regardless of `SITE_BASE_URL` having a trailing slash or not. I wasted a bit of time trying to debug oauth issues related to this.
You should be able to login to the refine dashboard having a base url with and without a trailing slash.
> Switch some settings to use urljoin

- .gitignore
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Fixes #731
Updates the filter processing code in the Staff Dashboard's Flexible Pricing list screen to clear the Status filter when the blank option is selected. 
You will need to have some Flexible Price requests in the system to test. For best results, they should be a mix of statuses. 
1. Navigate to Flexible Pricing in the Staff Dashboard.
2. Filter by any status. Only the requests matching the status you selected should be shown.
3. Clear the filter by selecting the blank option at the top. Upon selecting the Filter button, all requests should be shown (i.e., it shouldn't be filtering by Status). 
Implementation detail: clearing the filter requires passing `undefined` as the option. So, the change here was just to check for something non-true and explicitly set the filter argument as …
> Updates status filtering to send an undefined if there's nothing selected

- frontend/public/scss/dashboard.scss
- frontend/public/src/components/ProgramEnrollmentDrawer.js
Fixes #826 
Changes the `overflow-y` on the program drawer to `hidden`, which allows the content to be scrollable, and adds an event handler if the drawer is visible to sync the scrolling of the drawer with the dashboard page. The event handler is removed when the drawer is toggled back off. 
Enroll in a program with many courses. You will need to enroll in a sufficient number of courses to extend the card list past the bottom edge of the viewport. Then, load the dashboard and activate the program drawer - the drawer should activate and scrolling should work.
> Fixes scrolling when the program drawer has items that extend beyond the bottom of the screen

- docker-compose.yml
n/a
Increases the startup period to 45 seconds and adds in another retry to give the JavaScript containers more time to complete initial build processes. 
Restart the service. The JavaScript containers should be able to complete their tasks before the healthcheck gives up on them (i.e., it should start successfully). The `refine` container is typically the one that takes the longest, so keeping an eye on that (`docker compose log -f refine` or `docker inspect --format "{{json .State.Health}}" mitxonline-refine-1 | jq` if you have `jq` installed) is a good idea.
> Adds some more time to the docker-compose watches

- frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
Fixes https://github.com/mitodl/mitxonline/issues/779
Displays `Documents in order` as a default choice in Staff Dashboard while approving a pending financial assistance request.
1. Setup financial assistance for a course using https://github.com/mitodl/hq/discussions/133. 
2. Visit the financial assistance form for a course and request financial assistance.
3. Visit the staff dashboard and go to the flexible prices tab.
4. Click on `approve` for the request that you just submitted.
5. Popup will show `Documents in order` as a default choice.
(Optional)
> online-779 Display `Documents in order` as default

- flexiblepricing/serializers.py
- flexiblepricing/views/v0/__init__.py
- flexiblepricing/views_test.py
- frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
- frontend/staff-dashboard/src/utils.ts
Fixes https://github.com/mitodl/mitxonline/issues/664
Adds additional data in the staff dashboard for Financial Assistance requests. This PR adds courseware information and discount information for a financial assistance request. While approving a request admin can also change the discount from the dropdown.
(Required)
- Setup financial assistance for a course/program using https://github.com/mitodl/hq/discussions/133.
- Submit a financial assistance request.
- Visit flexible pricing in Refine dashboard.
- In the flexible pricing list, you can see the `courseware readable id` and `Discount` information.
- When you click on approve button for a request, courseware information is displayed. Also, a dropdown for discounts is displayed. So, you can change the discount for a request. You can …
> Online-664 Add additional data to Financial Assistance Request Table and Dialog

- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
- frontend/staff-dashboard/src/styles/antd.less
Fixes https://github.com/mitodl/mitxonline/issues/815
Fixed width for Income field in financial assistance requests list. Also, for too long income number horizontal scrolling is added.
- Add a very long number in the income field for Financial assistance requests.
- Visit Flexible prices in the refine dashboard. Too long Income number is scrollable with fixed width.
(Optional)
> Online-815 Fix styling for income field

- docs/source/configuration/refine_admin.rst
Previously you need to use a double slash for the oauth callback URL used when configuring the refine connection.  With https://github.com/mitodl/mitxonline/pull/802, the double slash hack is no longer needed.
- Open the refine oauth configuration at http://mitxonline.odl.local:8013/admin/oauth2_provider/application/ and set the redirect URI to `http://mitxonline.odl.local:8013//staff-dashboard/oauth2/login/`.
- Confirm that the refine dashboard does not allow you to login successfully as an admin user.
- Update the redirect URI to `http://mitxonline.odl.local:8013/staff-dashboard/oauth2/login/`
- Confirm that the refine dashboard does allow you to login successfully as an admin user.
> Update refine callback URL to remove double slash

- frontend/public/src/components/ProgramEnrollmentCard.js
Fixes https://github.com/mitodl/mitxonline/issues/829
Clicking on the Program title opens the course drawer.
- Enroll in a course that belongs to a program i.e. DEDP.
- Clicking on the program title opens the program drawer instead of page reloading.
https://user-images.githubusercontent.com/52656433/184620437-916e16a4-2046-403f-9df3-bd64fe6d62cb.mov
> Online-829 Open program drawer when program title is clicked

- flexiblepricing/serializers.py
- frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
- frontend/staff-dashboard/src/styles/antd.less
- frontend/staff-dashboard/src/utils.ts
Fixes https://github.com/mitodl/mitxonline/issues/839
Improves Flexible pricing list view.
- Add a few financial assistance requests.
- Visit Flexible pricing in the staff dashboard.
- `Original Currency` & `Documents Sent` columns are removed.
- Updated the income column with `Original Income` and `Currency` added besides Income in USD.
- Updated `Name/Location` with User `Email`.
- Compact date format.
(Optional)
> Online-839 Improve Financial Assistance Request List View

- cms/models.py
None, Just noticed this sentry error https://sentry.io/organizations/mit-office-of-digital-learning/issues/3509592346/?project=5864687&referrer=slack
Fixes the usage of `datetime.now`, since the import was changed
Submit a Flexible pricing form
This seems to be a side effect of a recent PR Rebase/Merge https://github.com/mitodl/mitxonline/pull/740, which changed the datetime import.
> fix: datetime issue in flexible price form

- app.json
- cms/api.py
- cms/apps.py
- cms/signalreceivers.py
- cms/tasks.py
- main/settings.py
- requirements.in
- requirements.txt
Fixes #749 
Adds some receivers for some Wagtail signals that are sent when a page is (un)published or moved to invalidate the Fastly cache for the affected pages. This should ensure that new edits made in the CMS override the cache when they happen.
Fully testing this manually will attempt to invalidate pages in the Fastly cache. This will fail unless your system is configured to look like a system it knows about (e.g. you need to set up your testing machine to respond to `rc.mitxonline.mit.edu` locally for it to really work). However, you should be able to see log entries where the app queues and then invalidates the cache regardless of your local instance's settings.
Do any number of these operations:
1. Publish a page.
2. Move a page such that the URL for it will change.
3. Unpublish …
> Purges the Fastly cache for a page once the page has been modified

- ecommerce/api.py
- ecommerce/views/v0/__init__.py
Fixes https://github.com/mitodl/mitxonline/issues/860
Recalculates financial assistance discount for a basket each time the checkout page is loaded. Also, delete old BasketDiscount objects on the checkout page reload, and when the basket items are cleared.
- Visit the course detail page.
- Enroll modal will display the course price.
- Continue with enrollment.
- Cart will show the total price.
- Apply for financial assistance in the course. Try that the request is auto-approved.
- Visit the checkout page. You can see financial assistance applied.
- Update discount for the request from the staff dashboard.
- Visit the cart and the price is updated.
- Reset or Deny a request and visit the cart, you will see the total price for the course.
Course 1 with a total price:
Course 1 added to cart …
> Online-860 Calculate flexible price discount instead of using BasketDiscount

- cms/serializers.py
- cms/serializers_test.py
When trying to find the financial assistance form which may be a child of a program page, before checking a program page's child pages we need to make sure that the program page we are checking actually exists!
> Check for program page before checking for child pages

- courses/api.py
- courses/views/v1/__init__.py
- flexiblepricing/api.py
- flexiblepricing/api_test.py
- frontend/public/src/containers/ProductDetailEnrollApp.js
Fixes https://github.com/mitodl/mitxonline/issues/868
- Updates Course Runs API permission for anonymous users.
- Anonymous users cannot see enroll now button if enrollment is not started.
- Removes unused imports for the changed files.
- Create a course with course runs having enrollment dates in the future.
- Visit course detail for a logged-in user.
- Enroll now is not visible.
- Log out and visit the course detail again. Enroll now is still not visible.
- Now update the course run so that the enrollment start date is in past.
- Visit course detail for logged-in and anonymous users. Now enroll now button is there.
> Online-868 Hide enrolment button for anonymous users

- ecommerce/models.py
- ecommerce/models_test.py
- ecommerce/serializers.py
- ecommerce/views/v0/__init__.py
- ecommerce/views_test.py
- flexiblepricing/mail_api.py
#873
Some of the refactors were quite straightforward, e.g. The places we were filtering products based on `is_active` should use `objects`. For the places where were won't care for `is-active` were likely to use `all_objects`.
- Makes the default Model manager for Product to return active products only
- For all products uses `all_objects`
- Refactors the usage of Product query set on multiple places to either use `all_objects` or `objects` based on its usage
- Majorly this relies on code coverage but testing is needed
- In general checking, everything works just like before in every place the product is used
- I can think of `Cart`, `Dashboard`, `Course Details`, `Order History`, `Payment`, `Discounts`, `Flexible Pricing`
Try to reproduce the issue by putting the URL add URL manually …
> fix: active products to cart only

- cms/management/commands/purge_fastly_cache.py
- cms/tasks.py
- requirements.in
- requirements.txt
Fixes #749 
Fixes some bugs in the original PR https://github.com/mitodl/mitxonline/pull/838 namely:
- Doesn't use the Fastly API library anymore (the stable version is outdated and the updated version is pre-release and doesn't allow for single pages to be purged)
- Adds some better logging if it does fail (which it definitely will locally without proper setup)
This also adds in a management command to purge the entire cache. Purging everything results in a hard purge, where a single page request is handled with a soft purge. See [the documentation](https://developer.fastly.com/reference/api/purging/) for info but the gist of it is a hard purge removes everything right now where a soft one doesn't. 
To properly test, you will need to have your test instance set up to respond as …
> Fixes some issues with the Fastly API code

- ecommerce/models.py
- flexiblepricing/constants.py
- flexiblepricing/mail_api.py
Fixes #852
Updates the approval email text as noted in #852. This also updates the code to not assume the flexible pricing submission's courseware object is a Course. 
Approve a Flexible Pricing request. (For a full test, make sure to approve it with a discount for each of the three types - percent off, amount off, and fixed price.) The email should send successfully and the text in it should be correct.
> Update flexible pricing approval email to eliminate errors when sending

- ecommerce/models.py
- flexiblepricing/management/commands/configure_for_dedp.py
- flexiblepricing/management/commands/configure_for_dedp_test.py
Fixes #883
Adds a management command that bootstraps DEDP financial aid. This includes:
- making sure a DEDP program exists
- creating discounts for the tiers (or identifying and reusing discounts that already exist, if their parameters are correct)
- creating tiers for DEDP financial assistance requests
The command will also deactivate (by setting the expiration date to a date in the past) discounts that follow the naming scheme (`DEDP-fa-tierX-YYYY` where YYYY is the year), and will deactivate tiers that aren't associated with a current set of DEDP discounts. 
See the comment block at the top of the command `flexiblepricing/management/commands/configure_for_dedp.py` for an explanation of what your database should have in it after running the command. 
To …
> Adds setup command to bootstrap financial aid for DEDP

- ecommerce/api.py
- ecommerce/views_test.py
#895 
- Adds the missing import
- After Adding that import (I noticed that the `fulfill_completed_order` also had the wrong number of args so i had to fix that too)
- Fixes 500 error when basket is checked out with zero value
- Adds a test to avoid this kind of error with zero value basket in future
- Setup this branch
- Create a discount with 100% or full value off
- Apply the discount at checkout
- Click checkout (User should not see 500 error, instead he should be redirected to dashboard properly)
- You can also follow the testing instruction from [this PR](https://github.com/mitodl/mitxonline/pull/462) that was initially created.
- Try to reproduce this error on the main first
- The zero value checkout was added in https://github.com/mitodl/mitxonline/pull/462/files
- But [another …
> fix: basket checkout with zero value

- cms/templates/product_page.html
- frontend/public/scss/product-details.scss
- frontend/public/src/containers/ProductDetailEnrollApp.js
Fixes #854 
Swaps clickable elements in the course run date picker from `<a>` tags to `<span>` so they don't cause the URL to change. Also removes the dependence on `localStorage` for storing the selected course run (as noted, it should default to the most recent course run). 
Load a course page that has multiple active course runs. Clicking the More Dates link should not cause the URL to change. Selecting a date in the popover should, additionally, not cause the URL to change. The selection should not survive a page refresh.
> Fixes nav issues when a course date is selected

- ecommerce/api.py
https://github.com/mitodl/mitxonline/issues/894
Log error message when reason_code in cybersource payload is any number other than 100 
Not sure the best way to see the log for the payment failure locally. But I modify the code ```if reason_code and reason_code == "100":```to confirm it's logged in mitxonline-web-1 container
> add error log for transactions' reason code any number other than 100

- cms/templates/flexiblepricing/flexible_pricing_request_form.html
Related to https://github.com/mitodl/mitxonline/pull/856
When the user fills out a flexible pricing form for a program the approval message shows a button to go to dashboard. For comparison, an individual course flexible pricing request shows the user "Get Certificate" button, that adds the course to the basket and takes user to checkout.
To test this Fill out the flexible pricing form( once for a course and another for a program), receive a discount and test:
1)For a course the Get Certificate button. It should take you to checkout page with the product in the cart.
2) For a program Go to Dashboard button
Flexible pricing form for course:
After clicking Get Certificate:
Flexible Pricing for program:
> Program Flexible Pricing approval page

- frontend/public/src/components/EnrolledItemCard.js
https://github.com/mitodl/mitxonline/issues/884
Refer to the screenshot - if the "Get Certificate" button is hidden, then we should also hide the upgrade description (shown with the grey background).
1.  Create a Course and Course Run but no Product.
2. Enroll in the Course Run from step 1.
3. View your Dashboard and ensure that you don't see the "Get Certificate" button or upgrade description.
4. Create a Product associated with your Course Run.
5. View your Dashboard and ensure that you do see the "Get Certificate" button and upgrade description.
6. Change your Course Run Enrollment's mode to any value other than "audit"
7. View your Dashboard and ensure that you don't see the "Get Certificate" button or upgrade description.
8. Revert the Course Run Enrollment's mode back to "audit"
9. …
> Hide description if certificate is also hidden

- courses/api.py
- courses/api_test.py
None, FIxes sentry error https://sentry.io/organizations/mit-office-of-digital-learning/issues/3549741560/?project=5864687&referrer=slack
Fixes a sentry error with certificate generation when course run end_date is not set or None.
Just checking that certificate generation handles end dates now when not set.
> fix: certificate error when end_date is not set

- cms/templates/product_page.html
- frontend/public/scss/product-details.scss
Fixes #885 
Adds the text specified in #885 to the bottom of the course about page. This is currently constructed with `clear:both` on the container so that it falls underneath everything above it. (Notably, it should fall beneath the upsell card on a course about page that's very short and also has an upsell card. See screenshot.) 
Observe any course about page. The text should be at the bottom, before the footer.
Demonstrating flow:
Mobile:
> Adds OFAC messaging to the bottom of the course about page

- courses/serializers.py
Fixes #920
Wraps the check for a courserun's related course page in a `try/except` - if the learner is enrolled in a course run that doesn't have a page (like, for instance, a proctored exam), the check for the page will end up throwing a `RelatedObjectDoesNotExist` exception. 
Create and enroll in a course that does not have a CMS page. Then, view the dashboard. You should see course cards as per usual and you should not see the invite to enroll in courses.
> Fixes API error when learner is enrolled in a courserun with no related page

- frontend/public/src/components/ProgramEnrollmentCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
Fixes #904
Adds some accessibility attributes to parts of the program drawer to make it more apparent to screen readers. 
You will need an account that is enrolled in a program. 
Activate your screen reader (tested with Apple VoiceOver) and navigate to the dashboard. Activating the program drawer (either by clicking the X Courses or the program title) should put the focus in the program drawer and it should read the data that's presented there.
> Adds accessibility attributes to make the program drawer work better with screen readers

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
- frontend/public/src/containers/pages/DashboardPage.js
- frontend/public/src/lib/queries/enrollment.js
https://github.com/mitodl/mitxonline/issues/910
Fixing issue when user enrolls from course in a program 
- Close the program drawer so that user can see the confirmation message
- Program enrollment card is updated to reflect unenrollment on the dashboard
- Enroll a course from program and a course that's _not_ program
- Unenroll from a course in a program should now looks like this:
(# course is updated as well)
- unenroll from a course that is not a program should still work 
(i made this course not part of a program)
(Optional)
(Optional)
(Optional)
> 910 dashboard doesnt refresh when user unenrolls from course in a program

- ecommerce/views/v0/__init__.py
https://github.com/mitodl/mitxonline/issues/935
Fixing 500 error when checking out course from external source - edx  
- The external checkout instruction can be found in this [PR ](https://github.com/mitodl/mitxonline/pull/626)
- As instructed in other PR, you could manually pass course_id to URL like this:  http://mitxonline.odl.local:8013/cart/add?course_id=course-v1%3AMITx%2B14.310x%2B3T2022 (make sure courserun and product setup locally)
- It should then directs you to the checkout page instead of receiving 500 error
> fix 500 error on external course checkout

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
Fixes https://github.com/mitodl/mitxonline/issues/943
Updates enrolled course text. If a course is started then `Active -` with Red color is displayed with the course start date else `Starts -` is displayed with the course date.
- Enroll in a course run with a start date in the Past.
- Visit the dashboard and the course description shows `Active -` with the start date.
- Now enroll in a future course run.
- Visit the dashboard and the course description shows `Starts -` with the start date.
Course Started:
Course Start Date in Future:
> Online-943 Update course start string

- ecommerce/serializers.py
- ecommerce/serializers_test.py
Fixes https://github.com/mitodl/mitxonline/issues/941
- Hides discount of 0 value. Only Fixed price type zero value discounts are applied to the cart.
1 - Manual
- Create a discount from admin and do not check `for flexible pricing option`.
- Add a product to the cart. Visit the cart and apply the discount coupon.
- Zero-value discounts won't show up unless they are Fixed price type discounts.
2 - Financial assistance
- Another method is to create financial assistance tier and create a discount for that tier with zero value. 
- Submit financial assistance request so that the 0 value discount is applied. 
- Discount won't show up on checkout unless it is of fixed price type.
Fixed Price - 0 Value
Percent/Dollars off - 0 Value
Percent off - 100 Value
Dollars off - 100 Value
> Online-941 Filter zero value discounts on checkout

- cms/signalreceivers.py
- flexiblepricing/utils.py
- flexiblepricing/utils_test.py
n/a so far
Adds a signal receiver to check FlexiblePricingRequestForms for the required fields when one is published. If the fields aren't in there, the receiver will add them in for you.
The fields in question are the Your Income and Income Currency fields. 
There are three different ways to test:
1. Create a new Flexible Pricing Request Form with no form fields defined. After publishing it, edit it; the required fields should be in there.
2. Create a Flexible Pricing Request Form with only one of the fields defined. After publishing it, edit it; the missing field should be added. 
3. Edit a Flexible Pricing Request Form that has the form fields already in it and rename one of the required fields. No change to the form should be made (but there will be a log message from the signal …
> Adds a check to make sure flexible pricing forms have the right fields in them

- micromasters_import/management/commands/queries/003_import_enrollment.sql
- micromasters_import/management/commands/queries/008_import_combined_final_grade.sql
https://github.com/mitodl/mitxonline/issues/658
- Adding a migration script to bring over grades from MicroMaster
- Limit to learners who have taken the exam and passed
- Modify the enrollment query to those who have taken the exam and passed
- Similar setup foreign data connection as https://github.com/mitodl/mitxonline/pull/859
- It needs the mapped course id http://mitxonline.odl.local:8013/admin/micromasters_import/courseid/
- Run docker-compose run --rm web ./manage.py import_micromasters_data
- Check the imported course run grade http://mitxonline.odl.local:8013/admin/courses/courserungrade/
**Test result**
- Migrated 1 enrollment from MicroMaster RC
- Migrated 2 grades from MicroMaster RC 
(Note that there isn't a migrated enrollment for MITx/14.73x/2013_Spring because there is no …
> add query to migrate grades from MicroMaster

- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
Fixes #940 
Provides a refresh button for the Flexible Price list view in the staff dashboard, so you don't have to reload the page (and, currently, log back in) to see new requests.
You will need to have some flexible price form submissions to make this work. Additionally, it would be advisable to throttle your speed (using the Network tab in the dev tools) so the API call takes a sec; at least for me locally, the API call finished too fast to notice the changes to the button.
Log into the Staff Dashboard, then navigate to Flexible Pricing. You should see a button next to the table title that says "Refresh". Clicking the button should change the text to "Refreshing..." and cause the icon in the button to spin until the table has reloaded.
* Should there also be a Last Refreshed timestamp …
> Adds a refresh button to the Flexible Pricing Request list page in staff dashboard

- cms/models.py
- cms/models_test.py
- cms/templates/product_page.html
- courses/models.py
- ecommerce/models.py
- ecommerce/models_test.py
- flexiblepricing/api.py
Fixes #954 
Adjusts the code for the Price box on a product page (i.e., a course page) to display the learner's approved flexible pricing amount if they have requested flexible pricing and the request has been approved. This also changes the link so that it adds the course to the cart, rather than directing them to the flexible pricing request form. If the learner does not have a flexible pricing request (or it's been denied or reset), or if an anonymous user is viewing the page, the text specified in the CMS is displayed as per usual.
To test, you will need a course with a page and a relevant flexible pricing request form (either for the course itself or for the program it's in).
1. View the course page while logged out. The text for the Price card should be displayed (but it should not …
> Updates product pages to display approved flexible pricing amounts if one exists

- courses/serializers.py
- courses/serializers_test.py
- flexiblepricing/views/v0/__init__.py
- frontend/staff-dashboard/src/interfaces/index.d.ts
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
https://github.com/mitodl/mitxonline/issues/950
Adding a static field 'type' to courseware object in /api/flexible_pricing/applications_admin/. (Identity as program or course)
```       
"courseware": {
"title": "Data, Economics and Development Policy",
"readable_id": "program-v1:MITx+DEDP",
"id": 1,
"type": "program"
},
```
Adding a drop-down for choosing from existing courses/programs with financial aid requests
Go to Flexible pricing from the staff dashboard: http://mitxonline.odl.local:8013/staff-dashboard/flexible_pricing
The dropdown "Search by Course/Program" should list all the existing courses/programs from flexible pricing requests
Search a specific course or program, flexible pricing requests table should only display that course or program
The clear icon is also added to …
> adding course/program as filter on flexible pricing staff dashboard

- frontend/staff-dashboard/src/App.tsx
- frontend/staff-dashboard/src/hooks/useAuthProvider.ts
- frontend/staff-dashboard/src/index.tsx
- main/oidc_provider_settings.py
- main/settings.py
https://github.com/mitodl/mitxonline/issues/942
A user who does not have `is_staff` == `true` will receive an error message and be unable to login to the staff dashboard (http://mitxonline.odl.local:8013/staff-dashboard/).  A user with `is_staff` == `true` will be able to login to the staff dashboard.
This PR also allows the user to refresh the browser tab and not be forced to login again.  This is done by only checking if the user is authenticated after the auth has loaded.  While the auth is loading, the text "loading..." is shown.
1. Configure the refine application in `mitxonline`
2. From within an Incognito window, attempt to login to the refine/staff dashboard with a user who has `is_staff` = `false`.  Verify that you are unable to login and receive an error message.
3. From within …
> 942: unauthorized user can access staff dashboard

- flexiblepricing/admin.py
none
I found it difficult to test and debug while not able to see which flexible price was for which course and tier.
Adding list_display for FlexiblePriceAdmin and FlexiblePriceTierAdmin
Go to /admin/flexiblepricing/flexibleprice/ and see the display
> Adding list_display for FlexiblePriceAdmin

- courses/api.py
- courses/api_test.py
- courses/management/commands/manage_certificates.py
- courses/management/commands/test_manage_certificate.py
- courses/utils.py
#881 
Adds a command to manage below operations:
- Certificate revoke/unrevoke
- Grade override/Certificate creation
- Certifiicate creation
**Criteria & Conditions (For operations in the command)**
1. A course run (Course Run's `courseware_id`) is needed for all the operations in the command
2. _Grade override and revoke/un-revoke_ operations are supported for a single user only, so for these operations, the command will specifically need a user
3. The _Create_ operation is supported for single or all users
1. If a user is provided while running `--create` the operation will run only for that specific user
2. If a user is not provided while running `--create` the operation will for all the enrolled users
**Overall behavior**
1. The command will not check the eligibility of the course run …
> feat: Add command for certificate management

- flexiblepricing/serializers.py
- flexiblepricing/urls.py
- flexiblepricing/views/v0/__init__.py
- frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx
https://github.com/mitodl/mitxonline/issues/950
This is to fix the course/program filter implemented in https://github.com/mitodl/mitxonline/pull/965
On RC https://rc.mitxonline.mit.edu/staff-dashboard/flexible_pricing, it only displays one course in the dropdown, there should be 12 courses/programs there 
It appears to only return the distinct course/program from https://rc.mitxonline.mit.edu/api/flexible_pricing/applications_admin/?l=3&o=0
The previous approach is also flawed as it's computing the DISTINCT course/program from the result of ` api/flexible_pricing/applications_admin/, ` in the frontend
This PR is to fix the dropdown "Search by Course/Program",  it should return a complete list of DISTINCT courses/programs from flexible pricing requests, with no limit.
Go to Flexible …
> get complete list of courseware in flexible pricing request

- cms/templates/certificate_page.html
- courses/models.py
#967 
- Open certificate page
- Validate start and end date on certificate template page
- If the course run is self-paced the end date should be the created date of certificate
In below screenshot the end date is certificate created date because the course run is self-paced (I've manually set `is_self_paced` flag as `True`)
In below screenshot the end date is course run end date because the course run is not self-paced (I've manually set `is_self_paced` flag as `False`)
> display certificate start and end date on template

- test_requirements.txt
N/A
This is an attempt to fix the requirements so that #980 can be generated successfully, currently it's conflicting on two points: a) it's pinning to 3.2.1, which conflicts with requirements.txt which is pinned to 3.2.0 b) it's using the legacy `factory_boy` package.
Tests should pass.
> Fix factory-boy package name and pin

- courses/models.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- ecommerce/messages.py
- ecommerce/models.py
- ecommerce/tasks.py
- ecommerce/tasks_test.py
- ecommerce/templates/mail/order_refund_message/body.html
- ecommerce/templates/mail/order_refund_message/subject.txt
Fixes #957
Adds a new email message that gets sent when an order is refunded. The text of the messages is in the issue (#957). 
Automated tests should work.
The easiest way to trigger the refund is through a Django shell; this method does not require that your system be able to accept callbacks from CyberSource. (Refunding through the Django Admin does attempt to perform the refund through CyberSource.) 
From a shell, load a FulfilledOrder, then call the "refund" method:
```
from ecommerce.models import FulfilledOrder
order = FulfilledOrder.objects.first() # change this accordingly
response_data = { "id": "an id" } # the only required field here is id 
order.refund(api_response_data=response_data, amount="50", reason="testing") # change amount and reason accordingly
```
This should …
> Adds an email message that is sent when an order is refunded.

- frontend/staff-dashboard/src/components/flexiblepricing/statusmodal.tsx
Remove undoable
https://github.com/mitodl/mitxonline/issues/780
Changes the [mutationMode](https://refine.dev/docs/advanced-tutorials/mutation-mode/) used when updating a Flexible Price Request in the staff-dashboard from `undoable` to `optimistic`. 
You must have the Refine staff-dashboard configured as explained [here](https://github.com/mitodl/mitxonline/blob/main/docs/source/configuration/refine_admin.rst).  You must also have at least two Flexible Pricing Requests submitted for a single user.
With this fix in place.
1. Login to the staff-dashboard as a staff user.
2. Navigate to http://mitxonline.odl.local:8013/staff-dashboard/flexible_pricing.
3. Reset one of the Flexible Pricing requests.
4. Verify that there is no countdown shown to cancel the change.
5. Reset the other Flexible …
> 780: Flexible Pricing: Resetting two Flexible Pricing Requests from the same user will spam their emai

- main/sentry.py
- main/settings.py
- openedx/api.py
https://github.com/mitodl/mitxonline/issues/934
This PR is just to add username to the error log in sync_enrollments_with_edx, and also add [send_default_pii](https://docs.sentry.io/platforms/python/guides/django/#configure) to sentry configuration to associate user to errors in general.
I will fix the bug in next PR
For the sentry configuration, we can't test it locally. 
For the error log, it can be ran like this
``` docker-compose run --rm web ./manage.py sync_enrollments --user rlougee@mit.edu```
In my case, it complains about my _unenrolled_ course that couldn't find a match on edx. It's marked inactive on both local and edx. I will fix this bug in next PR, but you could see the username is logged here
```Syncing enrollments for user 'rlougee' (rlougee@mit.edu)
[2022-09-21 14:18:22] …
```
> 934 add user to sync enrollments with edx error log and pass send_default_pii to sentry configuration

- ecommerce/mail_api_test.py
- ecommerce/models.py
- ecommerce/tasks_test.py
n/a
Adds the call to queue the order receipt email to the post-commit hook for the transaction when fulfilling an order, so the email task gets the order after the state has changed (rather than in the middle, which means it processes it as pre-transaction and throws an error). 
Complete an order. You should get the receipt email.
> Updates the order fulfillment code to wait for the transaction to complete before sending message

- ecommerce/serializers.py
- main/settings.py
Fixes #1050 
This removes an import that was causing the Zen of Python to be printed when running management commands. It also adjusts the logging settings for `cssutils` so that it doesn't visibly complain about the non-standard but necessary CSS rules for email clients when a command sends an email. 
Run a management command that results in an email being sent. (`create_enrollment` was the one noted in the original issue.) The command should run and whatever output it's supposed to generate should appear, but you should _not_ get the Zen of Python or a bunch of warnings.
> Cleans up some extraneous messaging when running management commands

- frontend/public/scss/footer.scss
Fixes https://github.com/mitodl/mitxonline/issues/1048
Adds top margin for footer to add some spacing.
Visit the dashboard with and without enrolments.
> Online-1048 Add top margin for footer

- frontend/public/scss/common.scss
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
https://github.com/mitodl/mitxonline/issues/1036
Disables (grey out) the "Enrolled" button and adds some text informing the user they are enrolled but the course has not started yet on the Course about page when a user is enrolled in a course before the CourseRun start_date.
1. Create a course run with a start date in the future.
2. Enroll your test user in the course run from step 1
3. Visit the Course about page (Dashboard -> "course details" on the course card)
4. Ensure the "Enrolled" button is greyed out and the additional text below the button is shown.
> 1036 enrolled button on about page links to course before it has started

- flexiblepricing/management/commands/create_product_for_program_courses.py
- flexiblepricing/management/commands/create_product_for_program_courses_test.py
https://github.com/mitodl/mitxonline/issues/1030
Adds a management command to create products for each course in a program. 
It defaults to creating an 'inactive' product for the DEDP program with a standard price of $1000. 
(Make sure course and course run for DEDP exists)
- Run ``` ./manage.py create_product_for_program_courses``` will create 'inactive' products for the DEDP program with a standard price of $1000.  
- Note that running it multiple times as it is (without passing -- active argument) will create redundant inactive products because unique constrain only works for _active_ product and also `ProductsQuerySet` filters out inactive products automatically
- Run ``` ./manage.py create_product_for_program_courses  --program  <readable_id>``` will create 'inactive' products for …
> Adding management command to create products for DEDP program

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/lib/courseApi.js
https://github.com/mitodl/mitxonline/issues/1051
When viewing the dashboard, any course cards for a course which have an `end_date` which is prior to the current date will display "Ended" and then the date on which they ended.
1. Create a Course Run with an `end_date` in the past.
2. enroll your test user in the Course Run.
3. Go to the Dashboard page.
4. Verify that the course card on the dashboard shows "Ended" and the `end_date` from the Course Run.
> 1051: Don't display "active" on the dashboard when it is past the course run's course_end date

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
Fixes https://github.com/mitodl/mitxonline/issues/1035
Display upsell messages in the dashboard when e-commerce is enabled.
- Set `ENABLE_UPGRADE_DIALOG` to False.
- Enroll in the audit version of a course. 
- Visit the dashboard, Enrolled card should not display the upsell message.
Flag Disabled:
Flag Enabled:
> Online-1035 Display upgrade dialog when Ecommerce enabled

- courses/models.py
- ecommerce/mail_api.py
- flexiblepricing/mail_api.py
https://github.com/mitodl/mitxonline/issues/1044
Formats all of the emails from `mitxonline` where the courseware title is shown to include the courseware number in the format of <courseware number> <courseware title>.
This change impacts the following emails:
1. Refund email
2. Flexible Price email (accepted, reset, pending manual approval) 
Trigger a refund email following the instructions listed on this [PR](https://github.com/mitodl/mitxonline/pull/1000).
Trigger flexible price emails by setting up a Flexible Price following [these instructions ](https://github.com/mitodl/mitxonline/blob/main/docs/source/ecommerce/flexible_pricing.rst).  Then submit a flexible price request for your user and change the flexible price request status through the [refine-staff …
> 1044: when referring to a course in email don't include the full course

- frontend/public/package.json
- frontend/public/webpack.config.js
- yarn.lock
https://github.com/mitodl/mitxonline/issues/1061
This PR adds [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) to help us understand what's in the bundles generated by the webpack build process.
Right now it is configured only to run for the production webpack build. (It doesn't affect the production bundles, though, just generates a sibling report.html file.) 
1. Run
```sh
docker compose run --rm --env NODE_ENV=production watch yarn workspace mitx-online-public run build
```
The build should succeed.
2. In yoour browser, open `/frontend/public/build/report.html`. It should show something like the diagram below.
We recently added this to ocw-hugo-themes in https://github.com/mitodl/ocw-hugo-themes/pull/855
> add webpack-bundle-analyzer

- courses/management/commands/upgrade_eligible_users.py
Fix https://github.com/mitodl/mitxonline/issues/960
This is a management command that take in a file and upgrades learners in their current enrollment
Create a csv file that has data of a learner in your local mitxonline environment, that is auditing a a current course.
In the csv file add a record: <learner_email>, <course_run_key>
Run the command `./manage.py upgrade_eligible_users input_file.csv`
The enrollment should get upgrades to 'verified'.
> Upgrade legacy learners that paid and are enrolled, have exam attempt

- frontend/public/src/lib/util.js
- frontend/public/src/lib/util_test.js
#1069 
- Fixes the frontend when discount price is more then actual price and the price shows negative value.
Good steps mentioned in #1069 
Are there any other places you think this should be fixed too?
> fix: show zero for negative prices

- courses/models.py
- ecommerce/mail_api.py
- ecommerce/mail_api_test.py
- flexiblepricing/mail_api.py
https://github.com/mitodl/mitxonline/issues/1044
Formats all of the emails from `mitxonline` where the courseware title is shown to include the courseware number in the format of <courseware number> <courseware title>.
This change impacts the following emails:
1. Refund email
2. Flexible Price email (accepted, reset, pending manual approval) 
Trigger a refund email following the instructions listed on this [PR](https://github.com/mitodl/mitxonline/pull/1000).
Trigger flexible price emails by setting up a Flexible Price following [these instructions ](https://github.com/mitodl/mitxonline/blob/main/docs/source/ecommerce/flexible_pricing.rst).  Then submit a flexible price request for your user and change the flexible price request status through the [refine-staff …
> 1044: when referring to a course in email dont include the full course

- openedx/api.py
https://github.com/mitodl/mitxonline/issues/934
Fixes the error log "Found local enrollments with no equivalent enrollment in edX" which contains _unenrolled_ courses from edx and locally. This PR is to filter out the unenrolled courses from local_only_ids with minimal side effects, so these don't get logged as errors 
Examples: 
https://sentry.io/organizations/mit-office-of-digital-learning/issues/3612208558/events/bc0d92f3212f4963bf87033adc75efda/?project=5864687
https://sentry.io/organizations/mit-office-of-digital-learning/issues/3612208558/events/a53c870c4aa545ac954a09c32e699b25/?project=5864687
Additional Notes:
The edx API `get_student_enrollments() `seems only return active enrollments, It's also being used in other repo like MicroMaster, if it's intended to include inactive …
> update local only enrollments error to filter out unenrolled

- micromasters_import/management/commands/queries/008_import_combined_final_grade.sql
N/A
This PR is to fix the `letter_grade` and `grade` for CouseRunGrade in the MM migration query to match with production 
- letter_grade: It's either 'Pass' or null 
- grade: It's between 0 to 1 with 2 decimals (Per discussion with Nathan, we round it to 3 decimals. We can cleanup later if needed)
Example from production:
Not passed: https://mitxonline.mit.edu/admin/courses/courserungrade/24600/change/
Passed: https://mitxonline.mit.edu/admin/courses/courserungrade/2421/change/
Example response from edx
{"username":"xxxxx","email":"","course_id":"course-v1:MITxT+11.S952x+2T2022","passed":true,**"percent":0.55,**"letter_grade":"Pass"}
Current on RC
https://rc.mitxonline.mit.edu/admin/courses/courserungrade/232/change/
Run ```./manage.py import_micromasters_data```
Go to django admin, the …
> convert the migrated combined grades to float field with 3 decimals

- ecommerce/admin.py
https://github.com/mitodl/mitxonline/issues/1086
This PR is to make the Order Admin pages as view only. It affects Order, Fulfilled Order, Pending Order and Refunded Order
Go to the order admin page http://mitxonline.odl.local:8013/admin/ecommerce/order/
Open any order, it should be readonly
> make order admin page readonly

- courses/management/commands/upgrade_eligible_users.py
None
Update the management command `upgrade_eligible_users` to save users that are not currently enrolled in mitxonline, so that they can receive coupons.
The input file should look something like:
```
useremail@example.com,course-v1:MITxT+14.310x+3T2022
```
To test this PR you would need an existing user in your local instance but not enrolled in this course. Then you
run the command `./manage.py upgrade_eligible_users <file_name.csv>`.
It should create a file with your record that is missing the enrollment.
> Save users with no enrollment into file

- main/middleware.py
Fixes #1006 
(potentially)
Adds URLs with `/courses/` to the `CachelessAPIMiddleware`. This should turn off Fastly caching for the course pages. (Since the course pages have some server-generated output on them, we don't want Fastly caching them.) 
Open devtools and load a course page. You should see the `Cache-Control: private, no-store` header in the response for the request.
> Adds course pages to the "don't cache" list

- courses/api.py
- courses/api_test.py
- requirements.in
- requirements.txt
https://github.com/mitodl/mitxonline/issues/842
Adds additional logic to handle receiving a list of CourseModes from the `edx-api-client` as well as only updating `mitxonline` CourseRuns if there is an edx CourseMode with a "verified" mode.
I would follow all of the steps listed in this prior PR: https://github.com/mitodl/mitxonline/pull/919.
I would then add two CourseModes in edx for a single CourseRun in `mitxonline` while ensuring that the CourseMode with a higher `ID` has a mode equal to `audit` and no upgrade_deadline value.
Because we were previously only looking at the first CourseMode returned from the edx API, there could be instances where that CourseMode had an upgrade_deadline that was empty or did not match the verified upgrade_deadline which we intended to have synchronized …
> 842: sync coursrun upgrade deadline with edx

- courses/models.py
- courses/models_test.py
Adjusts the Course model's `course_number` property to no longer call the `get_course_number` method from `ol-django` and instead extract the course number from the Course's `readable_id` attribute.  
The reason why `get_course_number` cannot be used is because that requires the `courseware_id` which is a property of `CourseRun` only.  
Unit tests should pass.
I tested this by generating an Acceptance email related to a Financial Assistance request (https://github.com/mitodl/mitxonline/pull/1076), but you could also just open an Django shell, retrieve the first Course object, and read that Course object's `course_number`.
In both cases, if the Course has a `readable_id` equal to 'course-v1:TestX+Test101', then the `course_number` should be equal to 'Test101'.
The unit test is pretty basic …
> Fix course model course number property

- ecommerce/admin.py
Fixes https://github.com/mitodl/mitxonline/issues/1115
Uses raw_id_fields for order in Transaction admin for Django Admin.
Visit a transaction object in Django Admin. The order should be a raw id field.
> 1115 Use raw id field for order in transactions admin

- ecommerce/admin.py
- flexiblepricing/admin.py
Fixes https://github.com/mitodl/mitxonline/issues/1102
Uses raw_id_fields for discount in Django admin.
- Visit `/admin/flexiblepricing/flexiblepricetier/`,  `/admin/ecommerce/userdiscount/` and `/admin/ecommerce/discountproduct/`.
- Add a new instance  or edit an existing one. The discount should be a raw id field with a search as well.
> 1102 Use raw id field for discount in admin

- ecommerce/api.py
- ecommerce/views/v0/__init__.py
Fixes #1116
Adds a status code check alongside the reason code check when processing the CyberSource payload post-payment. If the reason is `ACCEPT` _or_ the status code is `100`, the `process_cybersource_payment_response` call should fulfill the order. 
This also updates the status code check to log an error message if it falls through the bottom, so we can see what it's doing. (The "unknown error" only occurs if the order isn't in one of the states that we expect, and it was only logging to info so errors weren't being captured on production.) 
Submit an order. It should work as expected - you should be redirected to the dashboard and you should see the successfully enrolled message. You should only receive one set of enrollment and receipt emails.
> Adds additional error reporting; accepts transactions with status code 100

- ecommerce/views/v0/__init__.py
Fixes #1116 (moreso)
If the learner's order is already processed (as it might be if the callback is hit before the learner completes loading the redirect back to MITxOnline from CyberSource), the `CheckoutCallbackView` should now redirect the user to the dashboard with the proper result message, rather than getting confused (since the order's no longer Pending in that case). 
Automated tests should pass. Callbacks really need to work for this to be tested manually. 
Attempt to purchase a course. You should see the correct message when you've completed your order.
> Updates the checkout redirect code to handle processed orders

- main/middleware.py
Fixes https://github.com/mitodl/mitxonline/issues/1114
Adds URLs with `/checkout/` to the CachelessAPIMiddleware. This should turn off caching for `/checkout/to_payment`.
- Visit checkout page.
- Place an order and monitor network.
- You should see the `Cache-Control: private, no-store` header in the response for the request `/checkout/to_payment`.
> 1114 Add /checkout/ to no cache urls

- frontend/public/src/lib/courseApi.js
Fixes https://github.com/mitodl/mitxonline/issues/1141
Displays the end date when the course ended instead of the start date.
- Enroll in a course.
- Set course end to a past date.
- Visit the dashboard.
- It should display `Ended - {end_date}`
> 1141 Display end date when course ends on dashboard

- ecommerce/admin.py
Fixes https://github.com/mitodl/mitxonline/issues/1143 & https://github.com/mitodl/mitxonline/issues/1144
Fixes search and use raw_id_fields for foreign keys in Ecommerce admin.
Test search for the following models in Django Admin:
1. Basket Item
2. Discount Product
3. User Discount
Check that all the fields where data can grow are raw id fields in the following models:
1. Basket
2. Basket Item
3. Discount Product
4. User Discount
5. Basket Discount
6. Discount Redemption (CHANGED TO READONLY FIELDS)
> 1143&1144 Fix search and improve loading for e-commerce admin

- courses/api.py
- courses/api_test.py
https://github.com/mitodl/mitxonline/issues/1148
Sets the course_run_enrollment's `edx_enrolled` value equal to False when the edx API call, to modify an existing course_enrollment record's `mode` from `audit` to `verified`, fails.  This ensures that the edx API call is attempted again when the `retry-failed-edx-enrollments` task is performed periodically.  Ultimately this ensure that we synchronize the enrollment mode between `mitxonline` and edx even if the edx API calls fail.
Tester should have `devstack` and `mitxonline` running locally.
- Before starting `mitxonline`, I modified this section [here](https://github.com/mitodl/mitxonline/blob/7f4246df904f3557e28f3c662f2780bfd810b100/main/settings.py#L797-L801) so that the task to sync course modes runs more often.   
- Create a course, …
> 1148: course-enrollment-upgrading-is-not-ever-synchronized-with-edx-if-the-original-update-request-fails

- frontend/staff-dashboard/src/App.tsx
- frontend/staff-dashboard/src/components/layout/sider/index.tsx
- frontend/staff-dashboard/src/hooks/useAuthProvider.ts
- frontend/staff-dashboard/src/index.tsx
- frontend/staff-dashboard/src/pages/login.tsx
- users/serializers.py
- users/views_test.py
Fixes #1089 
Updates the Staff Dashboard Refine application to use Django sessions rather than having its own OAuth2 integration:
- This eliminates the need to log into the Staff Dashboard separately from the main MITx Online application. (To that end, the login screen is removed, and the logout functionality logs you out of MITx Online entirely. We may want to revisit that.) 
- Some minor changes were made to the User serializer to add the necessary authorization flags to the session check endpoint (`/api/users/me`). 
- Some more minor changes were made to the User serializer to report back the Django permissions set for the current user. We don't use this as of yet but this provides the ability to use the standard Django permissions system to define access for the Staff Dashboard app …
> Changes staff dashboard to use Django sessions rather than OAuth2

- config/default.vcl
- docker-compose.yml
Fixes #205 
Adds a [Varnish cache](https://varnish-cache.org/) container that sits in front of the nginx container for development. The Varnish cache is to replicate the Fastly cache that exists on the RC and production instance. It only caches Django content (so we don't muck with any reloading stuff that happens with the JavaScript/React assets). 
This also increases the `start_period` and `interval` for the `watch` and `refine` containers - on my machine at least, either one of these can take over 2 minutes to start up cold so this should ensure everything actually starts up. 
After restarting (you will need to bring your stuff down and then re-`docker compose up` it), you should be able to load your local instance normally. Inspecting the network tab in devtools should show the …
> Adding simple Varnish config file and service block to the Compose environment

- config/default.vcl
Re-fixes #1160
Updates the local Varnish config - Django uses the host setting to build URLs and that was being set wrong, causing failures elsewhere.
In my testing, the easiest way to check would be to create a new user account - you'll get an email from the system, and you should be able to verify that the hostname is correct.
> Some changes to the Varnish config

- users/management/commands/create_user.py
Part 1 of #1152 
This adds a management command that will create and optionally enroll a new user in the system. The enrollment is done using the existing `create_enrollment` command.
Run the management command: 
`./manage.py create_user <username> <email> <firstname> <lastname> <displayname> <countrycode> [--enroll <courseware>]`
This should create the user and, if you've supplied one or more `--enroll` flags, enroll them in the specified courseware object (either a course run or a program run).
> Adds a management command to create and optionally enroll a user

- courses/management/commands/create_courseware.py
Part 3 of #1152 
Adds a management command to generate courseware objects. These can be programs, courses (optionally with a course run), or a standalone course run.
To create a program: `create_courseware program <program id> <program title> [--live]`
To create a course: `create_courseware course <course id> <course title> [--live] [--program <program id>] [--program-position <int>]`
.. with a course run, append: `--create-run <run tag> [--run-url <course URL>] [--self-paced]`
To create a course run: `create_courseware courserun <course id> <run title> --run-tag <tag> [--run-url <course URL>] [--self-paced]`
This command does nothing in edX/devstack - you will need to create the courses there. (However, it doesn't allow for specifying the dates because the assumption is that you'll do …
> Adds a management command to create courseware objects

- cms/api.py
- cms/api_test.py
- cms/management/commands/create_courseware_page.py
Part 2 of #1152 
Adds a command in to make a really simple about page for the specified courseware object. The object must exist, as well as the index page that it should reside under. The Title and Description will be pulled from the object and the page will be created as a draft. The user will have to go in and fill out the rest of the info on the page to make it live (there's only so much content data in the a course or program record). 
1. Create a new course and/or program. (This doesn't have to exist in edX. Don't create a CMS page manually for it.)
2. Run `create_courseware_page <coursewareid>`. It should create the courseware page successfully.
3. Run the same command again. It should fail as there should already be a courseware page set up.
4. Check …
> Adding management command to create a really basic courseware about page

- README.md
- docs/source/commands/configure_instance.rst
- docs/source/commands/create_courseware.rst
- docs/source/commands/create_courseware_page.rst
- docs/source/commands/create_product.rst
- docs/source/commands/create_user.rst
- docs/source/commands/index.rst
- docs/source/configuration/ecommerce.rst
- docs/source/configuration/index.rst
- docs/source/configuration/quickstart.rst
- docs/source/configuration/refine_admin.rst
- docs/source/ecommerce/flexible_pricing.rst
- docs/source/index.rst
- ecommerce/management/commands/create_product.py
- main/management/commands/configure_instance.py
- users/management/commands/create_user.py
Fixes #1152 (this is the last part of that issue)
Adds a management command that will bootstrap a fresh MITxOnline instance. This involves:
* Running `configure_wagtail`
* Creating a new DEDP program
* Creating two courses to match the default ones you get with devstack (one of which gets added to the DEDP program), with a run for each, and then syncing that up with devstack (if that's configured)
* Creating product pages for the program and courses
* Creating a financial assistance form for the program
* Creating a new learner account and enrolling them in one of the courses
* Creating products for the course runs
So, the only steps you would need to do after checking out MITxOnline for the first time would be:
* Running migrate
* Running createsuperuser
* Performing the setup to talk to …
> Adds wrapper command to bootstrap a fresh MITxOnline instance

- micromasters_import/management/commands/queries/010_backfill_paidcourserun.sql
https://github.com/mitodl/mitxonline/issues/1167
This PR is to back-fill PaidCourseRun for any migrated MicroMasters orders.
Run `./manage.py import_micromasters_data --num 010`
Then check http://mitxonline.odl.local:8013/admin/courses/paidcourserun/, it should list all the paid courseruns for _imported_ MicroMaster orders where is in fulfilled
> add a migration to backfill PaidCourseRun for the legacy orders

- frontend/public/src/components/forms/RegisterEmailForm.js
- frontend/public/src/lib/urls.js
Fix #1181 
Add honor code link to account creation dialog
Try to create a new account, in the dialog you should be able to see the Honor Code link.
Before:
After:
> Add honor code link to account creation dialog

- courses/models.py
- ecommerce/admin.py
Fixes https://github.com/mitodl/mitxonline/issues/1191
Adds the following Enhancements for Product Admin:
- Adds read-only field in the list display which shows the Readable ID/Courseware ID and Title of the object.
- Allows search on CourseRun/Program Title and Courseware/Readable ID.
- Updates the product change view and displays Courseware/Readable ID and Title of the CourseRun/Program.
- Adds a couple of list filters.
- Visit Product admin
- Verify that the `Content Object` field is visible in the List view. Also, Search should work for it as well.
- Verify the list filters.
- Change a product.
- Verify that the Object subtitle is updated with its Courseware/Readable ID and Title.
> Enhance Product admin search and List display

- courses/management/commands/create_courseware.py
- courses/models.py
- courses/models_test.py
- courses/serializers.py
- courses/serializers_test.py
- docs/source/commands/create_courseware.rst
- frontend/public/scss/dashboard.scss
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/components/ProgramCourseInfoCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
- frontend/public/src/flow/courseTypes.js
- frontend/public/src/lib/courseApi.js
- static/images/done.svg
Fixes #1190 
Fixes #1193 (the code doesn't work in that way anymore so that issue is moot)
This PR adds grouping of courses in the program drawer according to the program's set requirements. It also resets some of the styling attributes for the enrolled item cards and program drawer to better match the InVision design here: https://projects.invisionapp.com/d/main?origin=v7#/console/21535972/468431707/preview?scrollOffset=0 
To summarize, this:
* Changes the program drawer to display a "Program overview" that consists of a total course count, not enrolled count, and passed course count
* Groups the available courses in the program by their status as an elective or a requirement in the course
* Updates the item cards in the program drawer to display an Enroll message when the user isn't …
> Re-groups and tags enrollments in the program drawer

- frontend/public/src/components/EnrolledItemCard.js
https://github.com/mitodl/mitxonline/issues/1206
Adds some spacing to the links in the course card (shown in the mock-up linked in the issue).  Also makes the "course(s)" link on the program card into a link instead (shown in the mock-up linked in the issue).
- Enroll your user into a program which has a few courses as requirements.  
- Create the CMS pages for the program and courses, along with a certificate page for the program.  
- Create a certificate for your user for one of the courses and the program.  
- Create a program run enrollment and course run enrollment for your user, making sure each enrollment is "verified".
- View the course enrollment and program enrollment cards on the user's dashboard.  Ensure that the links are spaced correctly and that the "Course(s)" link on the …
> 1206 dashboard course detail and view certificate links are too close together

- docs/source/commands/generate_discount_code.rst
Lists needed more spacing to render properly. This is just a documentation update.
> fixing list formatting in generate_discount_code.rst

- cms/templates/product_page.html
- frontend/public/scss/product-details.scss
- frontend/public/src/entry/django.js
https://github.com/mitodl/mitxonline/issues/1207
Ensures that a keyboard only user and users using a screen reader are able to access the "More dates" popover and select different dates to enroll in.
1. Pull down this branch
2. Navigate to a course page which has multiple course runs that start on different dates.
3. Enable a screen reader.
4. Use the 'tab' button in order to navigate to "More Dates".
5. Click the enter key on the "More Dates" button and ensure that the popover is shown. 
6. Tab through the popover options and ensure each option can be navigated to using the 'tab' button and that date is read by the screen reader.
7. Press the 'enter' button on one of the dates.  Ensure that the date selected is updated on the course page and the focus goes back to the 'More Dates' …
> 1207 accessibility more dates popup on course pages lacks keyboard controls

- ecommerce/admin.py
n/a
Adds the reference number field to the searchable fields in `BaseOrderAdmin` and `FulfilledOrderAdmin` (which doesn't subclass `BaseOrderAdmin`). This should make it less annoying to try to find orders based on the reference number. 
In an instance that has orders:
1. Navigate to Django Admin
2. Test that you can search by the reference number
> Adds "reference_number" to the searchable fields in order admins

- app.json
- courses/api.py
- courses/api_test.py
- courses/management/commands/check_program_requirements.py
- courses/tasks.py
- docs/source/commands/check_program_requirements.rst
- docs/source/commands/index.rst
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
- main/settings.py
Closes #1242
Four things:
1. Updates the Program Drawer to flatten the list of courses if there's no requirements tree. This was throwing an error otherwise as it was assuming there was something there; not having a requirements tree is an error condition but it should have been handling it gracefully.
2. Adds a `check_program_for_orphans` function that checks for a) the requirement tree's existence, and 2) course membership within the tree. 
3. Adds a management command, `check_program_requirements`, to scan programs for potentially problematic requirements trees.
4. Adds a scheduled Celery task to do the tree check automatically (defaults to daily at 3AM). 
1. Create a program with a course, a course run, and a course run enrollment for your test learner.
2. In the database, manually …
> Updates program drawer to handle empty requirements trees; adds function to check for invalid trees

- courses/mail_api.py
- courses/mail_api_test.py
Fixes #1247 
Fixes the URL that gets put into the partner school sharing email so it goes to the right place.
Send a partner school sharing email (see #1247 for details). The link should go to the right URL, and not to DRF.
> Fixes the URL in the partner school email

- frontend/public/scss/dashboard.scss
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/containers/pages/DashboardPage.js
https://github.com/mitodl/mitxonline/issues/1253
Makes sure that screen readers are able to clearly communicate that the user has toggled between the "My courses" and "Programs" tab of the dashboard by announcing the respective tab name when either of the navigation options are selected.  
This also fixes an issue with the "three dot" menu on the course card to ensure that the screen reader will only read the menu title and not "more_vert".
1. Have mitxonline up and running with a program and course created, program run and course run created, and your user enrolled in both.
2. Navigate to http://mitxonline.odl.local:8013/dashboard/?enable_programs
3. Turn on your screen reader.
4. Use the tab key to navigate to the "My courses" and "Programs" navigational options.
5. Focus on the …
> 1253: dashboard courses and programs tabs aren't screen reader accessible

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
https://github.com/mitodl/mitxonline/issues/1252
Removes the "In Progress" badge from the course card on the dashboard.  Cleans up some of the logic regarding whether a a course run is before the start date, in progress, or ended.
1. Have mitxonline up and running with an administrator user.
2. Create a course and associated course run which has a start date in the future.
3. Enroll your user into the course run.
4. Visit http://mitxonline.odl.local:8013/dashboard/ and ensure that the course card description shows "Starts"
5. Modify the course run from step 2 to have a start date that is before the current time.
6. Visit http://mitxonline.odl.local:8013/dashboard/ and ensure that the course card description shows "Active"
7. Modify the course run from step 2 to have an end date that is …
> 1252: dashboard course should not be in progress and ended at the same time

- frontend/public/src/components/ProgramEnrollmentDrawer.js
Fix #1259
Remove the not enrolled course count which sometimes shows negative numbers
Go to the dashboard and check out the program drawer
> Program drawer remove not enrolled

- courses/urls.py
- courses/views/v1/__init__.py
- courses/views_test.py
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/components/EnrolledProgramList.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/courseTypes.js
- frontend/public/src/lib/queries/enrollment.js
Closes #1251.
Adds the option to unenroll from a program in the program UI. If selected, the learner is unenrolled from the program (creating a specific enrollment record for the program with change status set to "unenrolled" if necessary), but _does not_ affect the enrollment of any individual courses. This also updates the `program_enrollments` API to respect program unenrollments when calculating the learner's program enrollments. As an added bonus, this also fixes the accessibility on all the modals in the `EnrolledItemCard.js` so that the contents of each modal actually get read by the screen reader (this was not the case previously, afaik). 
1. Ensure your learner account is enrolled in some programs, either implicitly (via an enrollment in a course in a program) or explicitly (with …
> Updates program UI to enable unenrollments

- courses/api.py
- courses/api_test.py
- courses/management/commands/create_verified_enrollment.py
- openedx/api.py
- openedx/api_test.py
#1179 
Follow-up PR for #1129 
(Required)
(Optional)
(Optional)
(Optional)
> Edx verified force enrollment after enrollment end date

- courses/api.py
- courses/api_test.py
- courses/management/commands/manage_program_certificates.py
- courses/management/commands/test_manage_program_certificate.py
- fixtures/common.py
#1041 
- Management command to manually revoke, un revokes, or create a certificate for a program for the given User.
- Checkout to the branch
- Program certificate will only be created if the user has earned certifications of all required courses for a given program
- Following operations can be performed
1. Generate a Program certificate for a user
`./manage.py manage_program_certificates --create --program <program_readable_id> --user <username or email>`
2. Forcefully Generate a Program certificate for a user using `-f` or `--force`
`./manage.py manage_program_certificates --create --program <program_readable_id> --user <username or email> -f`
**Revoke/Un-revoke Program Certificates**
3. Revoke a program certificate for a user
`./mange.py manage_program_certificates --revoke --program …
> feat: management command for creating, revoking program certificates

- courses/serializers.py
- courses/serializers_test.py
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/courseTypes.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
Closes #1238 
Updates the program drawer to use the requirements tree for titles and course listings rather than the flattened requirements in the API call. Updates the program serializer to include the requirements tree in its output.
The program drawer should work as it has. The titles should now be the titles from the nodes of the requirements tree, instead of "REQUIRED" and "OPTIONAL". 
(No actual UI changes here so just desktop screenshots.)
Before:
After:
> Updates the program drawer to use the requirements tree

- cms/serializers.py
- cms/serializers_test.py
- courses/serializers_test.py
- frontend/public/src/components/ProgramCourseInfoCard.js
- frontend/public/src/flow/cmsTypes.js
Closes #1288 
Fixes the Program Info Card (used in the program drawer to display course info when there's no enrollment) to look for the course details page in the course, rather than in the course run, which should fix the rendering issue.
To test, you will need a program that has several courses in it. Your test learner needs either an explicit enrollment in the program or enrollment in one of the courses. The courses should have CMS pages attached to them - to fully test, at least one _should not_ have a CMS page. 
Open the program drawer for the program. All courses that have a CMS page should also have a Course Details link, and that link should go to the CMS page, regardless of the learner's enrollment in the course. Courses that do _not_ have a CMS page should not display the …
> Fixed program info card to render course details link properly

- courses/management/commands/import_courserun.py
Fix for https://github.com/mitodl/mitxonline/pull/1295 (Please take a look at the comments in this PR)
Actually, fixes a value in courseware path generation that we missed in https://github.com/mitodl/mitxonline/pull/1295
Same steps as mentioned in https://github.com/mitodl/mitxonline/pull/1295
> fix: Fix courseware URL in command

- frontend/public/src/components/ProgramEnrollmentDrawer.js
Fix #1294
Update course message in the program drawer if already enrolled. Updates the logic that decides which course card to show.
Go to the student dashboard, open the program drawer and make sure that courses that the user is already enrolled do not show a button to enroll
> Update course message if already enrolled

- frontend/public/src/containers/pages/DashboardPage.js
#1293 
Don't show the programs tab if a user is not enrolled in any program by visiting this URL https://rc.mitxonline.mit.edu/dashboard/?enable_programs
- Checkout to this branch
- Unenroll from all programs if enrolled and check you should not see the programs tab on the dashboard `$local_host/dashboard/?enable_programs`
Before:
After:
> fix: don't show programs tab if user isn't enrolled in a program

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
#1078 
fixes issue #1078 for accidental course unenrollment
- Checkout to the branch
- Get enrolled in an audit course
- Got to the dashboard and click on the unenroll button of the enrolled course
- You'll see a modal for confirming the unenrollment
- If click on unenroll you'll be unenrolled from the course. clicking on cancel will close the modal
- If the `enrollment_end` date is passed the message will be `Are you sure you wish to unenroll from [Course Name] You won't be able to re-enroll`
- If `enrollment_end` date is in the future the message will be `Are you sure you wish to unenroll from [Course Name] You won't be able to re-enroll after [formatted end date and time]`
- Clicking on unenroll for verified enrolled courses you'll see the previous modal asking to contact support for …
> fix:dashboard confirmation dialog for unenrolling from courses

- courses/models.py
n/a
Updates `grade_percent` to return a Decimal that's rounded half even to 2 places rather than the default. This was causing a test to fail randomly. 
The test that fails is `courses/serializers_test.py::test_serialize_course_run_enrollments_with_grades` and the problem is that the grade is stored as a decimal and the grade calculation (which then uses a `Decimal` object and divides it) ends up adding precision where it's not really needed. (So, grade is .78 and then it gets multiplied by 100 and due to floating point math ends up being 77.99999 or something.)
> Fixes the course model to round the grade (fixes a flaky test)

- courses/management/commands/import_courserun.py
Closes #1306 
Updates the call to `get_or_create` so that single courseruns create the underlying course successfully. If you tried to import a course run for a course that existed, this would fail because the call to `get_or_create` to retrieve the course was malformed.
Create a new course run for an existing course in edX, then import using `import_courserun --courserun`. The command should complete successfully.
Create an entirely new course in edX, then import using `import_courserun --courserun`. The command should complete successfully. 
Noticed this reviewing #1305
> Fixes import_courserun to handle courses that exist already

- courses/api.py
- courses/management/commands/manage_certificates.py
- courses/management/commands/test_manage_certificate.py
Closes #1319 
Updates the `manage_certificates` command to wrap batched certificate generation in a try/except, so if there's an existing revoked certificate, it'll just skip over those instead of failing.
Automated tests should work.
1. Create a certificate for a learner.
2. Revoke that certificate (either through `manage_certificates` or through Django Admin). 
3. Run `manage_certificates` to generate certificates for the course run in question. If your error logging is set low enough, you should see a log message when it tries to make a certificate for the revoked learner, but it shouldn't fail. 
To test this fully, you'll need to have grades in edX that can be synced.
> Updates manage_certificates to handle revoked certificates better

- frontend/public/src/components/ProgramCourseInfoCard.js
Fix https://github.com/mitodl/mitxonline/issues/1309
remove enroll button and financial aid assistance from the program drawer
Go to user dashboard, open the program drawer and check that courses that you not enrolled in do not show enroll button.
> Program Drawer: remove enroll button

- frontend/public/src/components/ProgramCourseInfoCard.js
Related to #1314 
add padding for the course info
Before:
After:
> add the row back for formatting

- courses/models.py
- courses/serializers.py
- courses/serializers_test.py
https://github.com/mitodl/mitxonline/issues/1326
Sets the grade returned from the `LearnerRecordSerializer` to have only 2 decimal places.  That serializer is used on the program records page (http://mitxonline.odl.local:8013/records/1/)
1. Have `mitxonline` up and running locally.
2. Set `ENABLE_LEARNER_RECORDS=True` in the .env file.
3. Have a user enrolled into a course run for a course that is a requirement of a program.  Create a course run grade for the course run, and set the grade value as a repeating decimal.
4. Create a partner school record through Django Admin.
5. Navigate to the `mitxonline` Dashboard (http://mitxonline.odl.local:8013/dashboard/?enable_programs&enable_lr).
6. Go to the programs tab and open the program drawer by clicking on the program card.
7. Click "view …
> 1326: decimal grades on the learner record

- frontend/public/src/factories/course.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
Fixes a bug which was caused when viewing the program's course-drawer for the following configurations:
1. A program which has required courses and no elective courses.
2. A program which has elective courses and no required courses.
1. Enroll your user into a course run for which the corresponding course is a required course in a program.
2. Visit http://mitxonline.odl.local:8013/dashboard/?enable_programs#program_enrollment_drawer
3. Navigate to the "program" tab and then click on the card shown.
4. With this branch running, you should be shown the course associated with the program.  With the current master branch, you should see a blank screen and console errors in the browser.
> Fix: Program courses drawer won't open if program has no elective or required courses

- courses/management/commands/test_unenroll_enrollment.py
- courses/management/commands/unenroll_enrollment.py
#1335 #1321 
Management command to unenroll a user from enrollment
- Checkout to the branch
- Enroll in a course run with edx enrollment
- Test the command with the below options (to test the failed enrollment you can turn off the local edx server)
**Unenroll enrollment**
1. Unenroll enrollment for user
`./manage.py unenroll_enrollment -—user=<username or email> -—run=<course_run_courseware_id>`
**Keep failed enrollments**
2. Keep failed enrollments
`./manage.py unenroll_enrollment -—user=<username or email> -—run=<course_run_courseware_id> -k or --keep-failed-enrollments`
> feat: unenroll without a refund

- courses/management/commands/manage_certificates.py
#1328 
Fix for the incorrect message of the `manage_certificates` command
- Enroll a user into a course run as auditing.
- Create passing grades for that user in edX.
- Run `docker-compose run --rm web ./manage.py manage_certificates --create --run=<COURSE_RUN_ID>`
- The Previous message for the audit user was `Processed user <AUDIT_ENROLLED_USER> in course run <COURSE_RUN_ID>. Result - Grade: already exists (passed: True), Certificate: already exists`
- The new message should be `Processed user <AUDIT_ENROLLED_USER> in course run <COURSE_RUN_ID>. Result - Grade: already exists (passed: True), Certificate: ignored`
> fix: incorrect output from manage_certificates command when auditing

- ecommerce/signals.py
Closes #1337 
Uses `on_commit` to ensure that the post_save signal function for products doesn't try to sync to hubspot until after the save is committed to the database.  
- Temporarily modify the `husbpot_sync.task_helpers.sync_hubspot_product` function to just do something simple like this:
```python
def sync_hubspot_product(product):
print(Product.objects.get(id=product.id).description)
```
- In a django shell, run:
```python
from ecommerce.signals import *
from ecommerce.models import *
from courses.models import *
CourseRun.objects.filter(run_tag__startswith="fruntag_test").delete()
Product.objects.filter(description__startswith="PR 1351 Product ").delete()
course = Course.objects.first()
for i in range(20):
cr = CourseRun.objects.create(course_id=course.id, title=f"Test Run {i}", …
```
> Use on_commit in signal to avoid trying to sync a product to hubspot before it's comitted to the db

- ecommerce/admin.py
Fixes [Sentry Issue](https://sentry.io/organizations/mit-office-of-digital-learning/issues/3882322266/?project=5864687&referrer=slack)
- Fixes admin search for Discount Redemptions.
- Adds order info in the list display
- Visit `/admin/ecommerce/discountredemption/`
- Verify that order information is visible.
- Verify that the search is not breaking and is working fine as well.
> fix: Fix admin search for redeemed discounts

- cms/api_test.py
- cms/models.py
https://github.com/mitodl/mitxonline/issues/1354
- Fixes a bug with product listing on the home page, Which shows unpublished courses too, and opening them leads to a 404 page.
- Reproduce the issue with the steps mentioned in https://github.com/mitodl/mitxonline/issues/1354
- Set this branch up, Switch between `published/unpublished` for a course and check that you don't see unpublished pages on Home Page and vice versa.
Setup a couple of courses with cms pages
**After - Active Products only**
**Before - All Products**
NOTE: I should be adding some tests for this too. (To be added soon, before i finalize the PR)
> fix: show only published/live product pages on home page

- frontend/staff-dashboard/src/components/discounts/discounts.tsx
The create form was checking for values before rendering, causing it to not to render on RC.
n/a
Removes a check for values before rendering the discount form.
Try to create a discount using the staff dashboard. You should get an empty form, and you should be able to create the new discount successfully.
Editing an existing discount should also work as expected.
> Removes check for values before rendering the create discount form

- frontend/public/src/containers/pages/records/LearnerRecordsPage.js
https://github.com/mitodl/mitxonline/issues/1344
Changes the Course ID column from displaying the readable course ID to, now, displaying the course number.
1. Enroll a user into a course which is associated with a program.
2. Visit http://mitxonline.odl.local:8013/dashboard/?enable_programs&enable_lr
3. Click the Programs tab
4. Click on the course from step 1.
5. Click on "View program record"
6. Verify the Course ID column displays the course number only.
> Only display course number

- courses/serializers.py
Fixes https://sentry.io/organizations/mit-office-of-digital-learning/issues/3885865905/?project=5864687&referrer=slack
Adds a check to fix an error while setting a grade object attribute.
Testing instructions are taken from the main learner records [PR](https://github.com/mitodl/mitxonline/pull/1237).
- Ensure that you have a learner account enrolled in a program.
- Generate grades and certificates for the learner.
- Using Django Admin, also create some partner school records.
- View the learner's dashboard and open the program drawer. You should see the View Program Record link.
- Now delete the grade for one of the courses. Make sure that the learner records are still fine.
> fix: Fix program learner record when there is no grade

- courses/management/commands/import_courserun.py
Fixes https://github.com/mitodl/mitxonline/issues/1349
- Adds a new flag `--block_countries` to create `BlockedCountry` objects.
- `--block_countries` is a comma-separated list of country names to block enrollments.
- Make sure that your integration with edX is working fine.
- Create a new course in edX locally.
- Import the course using `import_courserun` command and provide an argument to block countries like `--block_countries='pakistan,united states of america'`. You should see success messages for the blocked countries.
- Visit `/admin/courses/blockedcountry/`. Blocked Country objects should be created.
> feat(import_courserun): add ability to block countries

- openedx/api.py
- openedx/api_test.py
Closes #258 
Makes some changes to the `repair_faulty_edx_users` API call: 
* If the call to create the user account in edX fails with a 409 specifically, this should ignore that error and continue. (Otherwise, it should re-raise the exception that is generated.)
* After creating the edX auth tokens, it should now check to see if there's an OpenEdxUser record as well, and should create a new one if there isn't one. 
1. Create two users manually (via Django Admin) in both MITx Online and Open edX. 
* Note that the Open edX account _must_ have a profile for this to work. (Specify anything here; it's enough for it to have the record at all.) If you're testing a failure mode, then don't specify a profile.
* The Open edX account password doesn't matter. 
* The usernames and email addresses …
> Updates repair_faulty_edx_user to reconnect edX users

- frontend/public/scss/learner-records.scss
- frontend/public/src/containers/pages/records/LearnerRecordsPage.js
https://github.com/mitodl/mitxonline/issues/1346
Makes visual and functional improvements to the leaner record page.
**Configure learner record**
1. Create a couple courses, course runs.  Enroll you user into the courses which will create a course run enrollment and course run grades entry.  Create a Program, Program run, Program run enrollment for your user.  
2. Visit https://rc.mitxonline.mit.edu/dashboard/?enable_programs&enable_lr
3. Click the "My Programs" tab.
4. Click the program card.
5. Click "View program record".
6. Verify that the desktop UI looks clean.
7. Switch to a mobile screen view and verify the UI looks clean.  The MIT logo should disappear and the table should become a list group.
8. Click allow record sharing.
9. Click share.
10. Copy the link.
11. Visit the link …
> 1346 learner record UI improvements

- frontend/public/src/components/ProgramEnrollmentDrawer.js
- frontend/public/src/lib/util.js
- main/features.py
- main/utils.py
- main/utils_test.py
Closes #1372.
Removes the `ENABLE_LEARNER_RECORDS` flag, so the records are available by default.
Go to the dashboard. You should be able to see your learner record from the program drawer without having to append anything to the URL.
> Enables learner records.

- frontend/public/src/components/ProgramCourseInfoCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
- frontend/public/src/containers/pages/DashboardPage.js
Fix the badge sizing.  Remove unnecessary keys.  Fix key for found enrollments.  Fix font size error.
https://github.com/mitodl/mitxonline/issues/1377
Resolves a few issues:
1. The "In Progress" badge shown on course cards in the program drawer were not sized uniformly.
2. An error was showing on the program drawer page for items of a list not having unique keys.  This was caused by the key value being set to a value which was undefined.
3. There was an error showing 
1. Have a program, program run, and program run enrollment for the user.  
2. Create two courses and add them as requirements in the program.  
3. Create a course run for each course that has a start date before now and an end date after now.  
4. Enroll your user into one of the course runs.
5. Navigate to …
> Fixes sizing on program course badge, list keys, font size styling

- cms/models.py
- cms/models_test.py
- courses/admin.py
Fixes https://github.com/mitodl/mitxonline/issues/1365
Syncs courseware title with CMS Product page title.
- Update CMS Product page i.e. CoursePage or ProgramPage
- Verify that the title is synced with the Courseware object title either by visiting Django Admin or through the APIs.
> feat: Sync courseware title with CMS page title

- frontend/public/scss/course-cards.scss
https://github.com/mitodl/mitxonline/issues/1384
Removes some static definitions for height of `h1` and `p` tags in the course cards shown on the homepage.
1. Configure a course, course run, and associated CMS pages.
2. Modify the CMS course page to have a very long title and description.
3. Visit the mitxonline homepage (http://mitxonline.odl.local:8013/)
4. Ensure that the title and description do not overlap each other when zoomed in on different browsers.
5. Also ensure that the space between the description and the course date (at the bottom of the course card) is not strangely large (as shown in one of the screenshots below).
Below is the large spacing between description and date.
> 1384: Fix for heading and description height

- frontend/public/src/factories/course.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
https://github.com/mitodl/mitxonline/issues/1366
Fixes an error when the requirements and, or electives nodes have been removed from a program.  This also adds a test for handling when a program has both a requirements and electives node, but courses defined as requirements or children (which has caused issues in the past).
1. Have mitxonline setup with a program with the elective and requirements sections deleted in Django admin, program run, course associated with the Program, course run, and all required CMS pages. 
2. Enroll your user in the course through the frontend
3. Visit the dashboard (http://mitxonline.odl.local:8013/dashboard/)
4. Click on the "My programs" tab
5. Click on the program card to open the program's course drawer.
6. Verify that the course is shown in the drawer …
> 1366: Fix and tests for undefined program course nodes

- courses/views/v1/__init__.py
- courses/views_test.py
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
- frontend/public/src/lib/queries/enrollment.js
Closes #1379
- Adds some logic to `create_enrollment_view` to respond with an API-esque response
- Updates the frontend logic to proactively hit the `/enrollments/` API when the user clicks Enroll Now
- Redirects the user to the dashboard if they cancel out of the upsell dialog
- Tests for above
Testing enrollment creation:
1. Attempt to enroll in a course that has a product. You should see the upsell dialog.
2. In a separate tab, open your dashboard. You should see the new course (and you will see the enrollment notification). 
Testing message persistence:
1. Attempt to enroll in a course that has a product. You should see the upsell dialog.
2. Close the dialog by _clicking the X_. You should be redirected to the dashboard, where you should see the enrollment …
> Updates enrollment upsell dialog to immediately create enrollments

- courses/api.py
- courses/api_test.py
- docs/source/commands/regenerate_edx_auth_tokens.rst
- openedx/api.py
- openedx/management/commands/regenerate_edx_auth_tokens.py
- openedx/management/commands/retry_edx_enrollment.py
- openedx/tasks.py
Closes #1395 
Makes the system regenerate the learner's authentication tokens when enrollment fails because they're invalid. This also adds a command to manually force the tokens to be regenerated. 
Enrollments will fail if the user's auth tokens (i.e., their `OpenEdxApiAuth` record) is in one of these states:
1. Nonexistent.
2. In place, but the access token has expired and the refresh token has been revoked in edX. 
In these cases, the code will take the following actions:
* If the learner themselves is enrolling in a course, the regeneration function will be queued for asynchronous execution. The enrollment will still fail but the system should fix the issue in the background. (Ideally, the system is also set to store enrollments when they fail and the enrollment will be tried again …
> Updates enrollments to regenerate auth tokens if they're invalid

- hubspot_sync/task_helpers.py
- hubspot_sync/task_helpers_test.py
Closed https://github.com/mitodl/mitxonline/issues/1414
If any kind of exception occurs when a hubspot task helper function calls a celery task, log the exception instead of raising it.
- Set up hubspot integration as described in the README (you can use the same token as RC)
- With all your docker instances running, try this in a shell (assuming you already have 2 `Order` objects):
```python
from hubspot_sync.task_helpers import *
from ecommerce.models import Order
for order in Order.objects.all()[:2]:
sync_hubspot_deal(order)
```
- The above should work without errors or log statements.
- Kill your redis instance (`docker kill mitxonline_redis_1`)
- Run the following:
```python
for order in Order.objects.all()[:2]:
sync_hubspot_deal(order)
```
- The above should generate two exception …
> Log any exception thrown by hubspot task helpers

- courses/models.py
Fixes [Sentry Issue](https://mit-office-of-digital-learning.sentry.io/issues/3914598815/?project=5864687&referrer=slack)
Fixes generic relations with FlexiblePrice and FlexiblePriceTier models.
Context:
As mentioned in the [Django docs](https://docs.djangoproject.com/en/4.1/ref/contrib/contenttypes/#django.contrib.contenttypes.fields.GenericRelation), the default field names for the content type and object id are `content_type` and `object_id`. For flexible pricing, we have `courseware_content_type` and `courseware_object_id`. So, We should mention these while creating a generic relation.
- Go to the Django Shell and test that the relations are working fine by doing `course_object.tiers/flexible_prices.all()`
- You can also try to delete a course object from the Django admin.
> fix: Fix flexible pricing generic relations

- openedx/management/commands/sync_enrollments.py
https://github.com/mitodl/mitxonline/issues/1437
Outputs an error message and exits the `sync_enrollments` command when the user is not found.
1. Checkout this branch
2. Have mitxonline up and running
3. Run `docker-compose run web ./manage.py sync_enrollments --user <USER_ID>`.  Replace `<USER_ID>` with a value which is not associated with any users in your environment.
4. Verify that `Could not find User with id=<USER_ID> (case-insensitive)` is output to the terminal and the command exits.  No other error messages should be present in the terminal.
> fix: sync_enrollments command error message and exit

- openedx/management/commands/retry_edx_enrollment.py
Closes #1439
Updates the call to `enroll_in_edx_course_runs` to include the enrollment mode when it attempts to retry the enrollment, so the user's current status (as stored by MITx Online) is reflected in edX.
1. Enroll a user in a course in the audit mode.
2. Manually change their enrollment to verified in Django Admin in MITx Online.
3. Run `retry_edx_enrollment` for the user, and specify the `-f` flag to force it.
4. Check the resulting enrollment in edX. It should be verified.
> Updates the command to include the enrollment mode when retrying enrollments

- docs/source/commands/refund_fulfilled_order.rst
- docs/source/commands/regenerate_edx_auth_tokens.rst
- ecommerce/management/commands/refund_fulfilled_order.py
Fixes #1426 
Adds a new management command, `refund_fulfilled_order`, that will do a "dry refund" of a fulfilled order. That is, this will update the status of the order to "refunded" and will adjust the learner's enrollments, but will not attempt to refund the learner's money via CyberSource. 
1. Complete a transaction in the system.
2. Run `refund_fulfilled_order` using the reference number. Specify each flag separately and check the outcome - if `--audit` is specified, the enrollment should be converted to an audit one, and if `--unenroll` is specified, the enrollment should be unenrolled.
> Adding command for manually "refunding" the user's enrollment

- docs/source/commands/configure_tiers.rst
- docs/source/commands/index.rst
- docs/source/conf.py
- flexiblepricing/management/commands/configure_tiers.py
- flexiblepricing/management/commands/configure_tiers_test.py
Closes #1434
Updates the `configure_tiers` command so that it can be used for individual courses as well as programs. We've had a few instances where courses that don't belong to programs needed financial assistance tiers, so this needed a bit of updating to be able to handle that. 
1. Create a course. (For testing, I used the `create_courseware` command: `create_courseware --live --create-run 1T2023 --start 2023-01-01 --end 2023-01-1 course course-v1:TIMxT+12.345x "Test Course for Tiers"`
2. Run the `configure_tiers` command, specifying the course: `configure_tiers --course course-v1:TIMxT+12.345x`
3. Check that everything ran successfully.
4. Re-run `configure_tiers` for a program and make sure that also works properly. 
Optionally, run tests with …
> Updated configure_tiers to work with courses as well as programs

- ecommerce/api.py
- ecommerce/api_test.py
Closes #1432
Corrects a call to `set_rollback`; sets it to just roll back the transaction when a refund attempt is processed and the payment gateway returns an error. Raises an exception in this case as well, rather than just returning false. 
You would have to mock out the payment gateway API to return an error (as this hits a CyberSource API to do its job) but if you have a transaction that has an error and was returning `Error: set_rollback() missing 1 required positional argument: 'rollback'`, it shouldn't do that anymore. 
There are transactions on prod that have this - they're regular credit card transactions, not PayPal ones, so not sure what the actual error is (because the syntax error ends up taking precedence).
> Fixing a call to `set_rollback` that was incorrect; adding a test

- frontend/public/src/components/forms/ProfileFormFields.js
- frontend/public/src/containers/pages/profile/EditProfilePage.js
- frontend/public/src/containers/pages/profile/EditProfilePage_test.js
Closes #1457
Two things:
* Moves the Highest Level of Education field above the "Are you a..." field in the extended profile fields (and thus moves it up out of the conditionally-displayed fields)
* In the edit profile form's onSubmit handler, changes the page refresh method to use window.location.refresh rather than pushing a new browser history entry. (This should prevent people from hitting back and getting the profile page over and over again, and also makes it so that the feature flag keeps working if you specify it in the URL.) 
These fields are hidden behind a feature flag; you'll either need to set `FEATURE_ENABLE_ADDL_PROFILE_FIELDS` or append `?enable_addl_profile_fields` to the URL.
1. Load the Profile page.
2. You should see the Highest Level of Education field below the …
> Moves Highest Level of Education field up

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/constants.py
Closes #1461
Changes the behavior of `refund_order` to prevent it from trying to catch exceptions that happen during the refund process. 
Changes the list of refund success states to remove duplicate as as successful state.
While this is really meant to be run from within the Google sheets processing code, you can call `refund_order` from a Django shell if you'd rather not set all that up. 
1. Complete a transaction in the system.
2. Refund your transaction. 
3. Attempt to process the refund transaction again. An exception should be raised - CyberSource won't let you refund a transaction twice. 
4. If you do have Google Sheets integration set up, you should see an error message in the refunds sheet. 
I think we regarded "duplicate" as a success state to allow the Google automation the …
> Changes refund_order to let exceptions bubble up, removes duplicate as a successful state

- main/templates/base.html
- main/templatetags/noindex_meta.py
https://github.com/mitodl/mitxonline/issues/1455
Blocks search engines from indexing `mitxonline` pages in non-production environments using a `<meta>` tag with the `noindex` value described here: https://developers.google.com/search/docs/crawling-indexing/block-indexing.  
The `<meta>` tag is included in the header of each `mitxonline` page if the value of the `MITX_ONLINE_ENVIRONMENT` environment variable does not equal 'prod' or 'production'.  The default value for this environment variable is 'dev'
1. Pull down this branch.
2. If `MITX_ONLINE_ENVIRONMENT` has not been added to your `.env` file, then start `mitxonline`.  Otherwise, set `MITX_ONLINE_ENVIRONMENT` equal to `dev` in your `.env`.
3. Visit any page in your local instance of `mitxonline` and view the page source.  Ensure that …
> 1455: Adds templatetag for noindex in non-prod

- frontend/public/src/components/forms/ProfileFormFields.js
https://github.com/mitodl/hq/issues/886
Adds a `typeError` to the validation for the State field that says "State is a required field" rather than the default yup error (which is very programmery). 
1. Log in with an account that either doesn't have a country/state set or has one set to a country that doesn't have states (so not US or Canada)
2. Set the country to US or Canada
3. Open the State field, but don't select anything. Instead, click to a different field.
4. Validation should run and you should see the "State is a required field" error message.
https://share.cleanshot.com/167R3ykMmtl8vrKPS5lt
> Adds friendlier error message when State is unset

- ecommerce/api_test.py
- ecommerce/models.py
Closes #1467 
Adds some code to remove discount redemptions when a pending order is declined. 
1. Start an order that has a discount attached to it and progress into the CyberSource part of it. (Don't complete the order). 
2. From a Django shell, load the order and call `decline` on it.
3. The order should change status to Declined, and the discount redemptions should be cleared for the order.
> Declining an order clears discounts associated with the order

- courses/api.py
- courses/api_test.py
- frontend/public/src/lib/courseApi.js
https://github.com/mitodl/mitxonline/issues/977
Enables the "Enroll now" button to be displayed on a course page in mitxonline when that course meets the following requirements:
- Has an end date in the past
- Has no enrollment end date, or an enrollment end date in the future.
- Has an upgrade deadline in the past
Since the course's upgrade deadline is in the past, the course certificate related pricing and upsell card functionality are not shown to the user.  The user is only able to enroll in the course with the `audit` mode.
1. Create a course and associated course run.  The course run should meet the requirements stated in the section above.
2. View the course page within `mitxonline` and verify that you can view the "Enroll now" button and are able to enroll in the course.
3. Ensure …
> 977: allow enrollment in archived courses

- openedx/api.py
- openedx/api_test.py
#1445 #1458
- Fixes permission error on checking the enrollment `code: 403, content: {"developer_message":"You do not have permission to perform this action."}`
1. Add the mitxonline user's course enrollment record in edx and mitxonline, but the mitxonline record has to be `Edx enrolled` equal to `false`.  
2. Add edx course mode expiry before any call to `retry_failed_edx_enrollments()`.
3. Validate that no more `EdxApiEnrollErrorException` exception is raised for this case after this PR
4. And `Edx enrolled` will be changed to `true`
> fix: retry_failed_edx_enrollments should check for existing enrollments (permission fix)

- courses/api.py
- courses/models.py
- courses/tasks.py
- courses/tasks_test.py
- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/tasks.py
- ecommerce/tasks_test.py
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
Closes #1466 
- If the learner's payment is refunded, we now bump the enrollment to audit instead of completely unenrolling them.
- Learners can now unenroll from certficate track (verified) enrollments at will (but this won't result in a refund).
Learners unenrolling from the certificate track will unenroll from the entire course, _and_ this will clear their `PaidCourseRecord` entry for the course so they can enroll again. (The checkout process checks the `PaidCourseRecord` table for an existing purchase of the course to prevent duplicate purchases.)
Testing unenrollments:
1. Enroll in and upgrade your enrollment for a course. 
2. From the Dashboard, select Unenroll from the menu.
3. You should get a dialog asking you to confirm. The dialog should note that unenrolling will not refund …
> Allows verified learners the ability to unenroll; adjusts flow for refunds

- cms/models.py
- cms/models_test.py
- courses/models.py
- courses/models_test.py
https://github.com/mitodl/mitxonline/issues/1483
Resolves an error that is thrown when a user visits a course page and meets the following requirements:
1. The associated course has no active course runs.
2. The user has an approved flexible price request for the associated course
1. Create a course, a course run with an enrollment end date in the past, course CMS page, flexible pricing page, product, discounts, flexible price tiers, and approved flexible pricing request for your user.
2. Visit the course page and ensure that no errors are thrown.
3. To ensure that you have everything configured correctly, I would recommend recreating the error using the main branch of mitxonline.
> Course page 500 error for expired course runs and flex price

- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/factories.py
- ecommerce/models.py
- ecommerce/models_test.py
- ecommerce/tasks.py
- ecommerce/views/v0/__init__.py
- main/utils.py
Closes #1485 
Updates the discount validity check to only consider the discount to be consumed if the redemption is for a Fulfilled order. Previously, this would consider all discount redemptions to have consumed the discount, so if the learner's payment attempt fails or never completes (iow, the state remains Pending or changes to Declined or Canceled or Refunded), the learner couldn't reuse their code.
There is an edge case where a one-time code can be redeemed more than once successfully. The learner(s) would have to have entered the code and started the checkout process at the same time (as once any order hits Fulfilled the code would be consumed and the system would error). There's a check for this that's present in the ecommerce API and a task defined but it's not set up to run on a …
> Adjust discount redemption checks to only consider orders in Fulfilled state for validity

- courses/api.py
- requirements.in
- requirements.txt
**NOTE** 🚧 This has a counterpart in edx-api-client, That should be tested/reviewed along with this PR https://github.com/mitodl/edx-api-client/pull/98
#1340 
- Syncs `certificate_available_date` with edX from within course details sync
- Setup a course(s) in edX and MITxOnline (edX should be on upstream `master` https://github.com/openedx/edx-platform that contains at least https://github.com/openedx/edx-platform/commit/0ff7c5b13f28cb5a8784d5a39d8a63347810e9c7)
- Enable `certificate display behavior` in edX by adding a waffle switch `certificates.auto_certificate_generation`, you should see `certificate_available_date` field in edX studio in the `Set date` section, now set a date here
- Open the shell in MITxOnline, and do the following:
```
from courses.tasks import sync_courseruns_data …
```
> feat: sync certificate_available_date with edX

- openedx/api.py
- openedx/api_test.py
https://github.com/mitodl/mitxonline/issues/934
https://github.com/mitodl/hq/issues/498
Adds logic to match the `is_active` value when checking Edx for existing course enrollments.  Previously, we would assume that an enrollment already exists in Edx even if the `is_active` value for that Edx enrollment was `False`.  This meant that we would not send a `POST` request to Edx to update the existing enrollment which lead to user's having an active enrollment in mitxonline and an inactive enrollment in Edx.
- Have both mitxonline and devstack running locally.
- Have a course configured in mitxonline (using the quick start commands).
- Ensure that you have followed the instructions here: https://github.com/mitodl/mitxonline/blob/main/docs/source/configuration/open_edx.rst
- Enroll in a course, …
> Resolve local enrollments found without matching edx enrollment

- cms/templates/certificate_page.html
- cms/templates/product_page.html
- frontend/public/src/components/CartItemCard.js
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/ProgramCourseInfoCard.js
Closes mitodl/hq#653
Closes mitodl/hq#659
Removes the alt text from the course images in these locations:
- Course detail page (was course title)
- Cart page (was course title)
- Dashboard (was "Preview image")
It does not remove the alt text from the featured item cards on the homepage as they were already an empty string.
Removes the alt text from the MIT logo on the certificate page. 
Load any of the pages in question: course detail page, cart, dashboard, or certificate. The affected images should have an empty string as the alt text and screen readers should not attempt to describe the image.
> Removing unnecessary alt texts from images

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
- frontend/public/src/containers/pages/DashboardPage.js
https://github.com/mitodl/hq/issues/703
1. Link to the program drawer on the dashboard, program tab, program card should read "Program's courses" through a screen reader instead of "2 courses".  
2. Tab navigation should be trapped to the program drawer when it's displayed.  
3. When opening the program drawer, screen readers should pronounce the program title.  Some readers will pronounce a description which would be "X courses, Y passed" where X and Y are the number of courses and those passed, respectively.   In order to verify this, you may need to view the "accessibility" tab in the Google Chrome developer tools.
4. The first element of focus in the program drawer should be the "X" close button in the top left.
1. Have mitxonline up and running with a course and associated program. …
> 703: accessibility improvements for dashboard and program drawer

- frontend/public/src/components/forms/RegisterDetailsForm.js
- frontend/public/src/components/forms/RegisterDetailsForm_test.js
https://github.com/mitodl/hq/issues/1104
Updates the registration form to:
1. Display an error message if the user does not input a year of birth.
2. Perform validations only when the user submits the form.  Not when the user tabs between fields.
- Start the registration process within mitxonline.
- Press tab to move through the registration form.  Verify that no error messages are displayed.  Error messages should only display after you hit the submit button.
- When asked for your year of birth, enter nothing.  Hitting submit on the form should then present the error message "Year of Birth is a required field".
> 1104: Perform validation on year of birth field during registration

- cms/templates/flexiblepricing/flexible_pricing_request_form.html
- frontend/public/scss/auth.scss
- frontend/public/scss/product-details.scss
- frontend/public/src/components/forms/ChangeEmailForm.js
- frontend/public/src/components/forms/ChangePasswordForm.js
- frontend/public/src/components/forms/ProfileFormFields.js
https://github.com/mitodl/mitxonline/issues/1508
https://github.com/mitodl/mitxonline/issues/1511
1. Updates the profile page, financial assistance form, additional details modal (shown when clicking on enrolled course title), change email form, change password form, register form; to not pronounce "star" when screen readers read the label for required fields.  
2. Required fields on the forms referenced in 1 are marked so that the screen reader will now pronounce "required".
3. Required fields on the forms referenced in 1 are set so the browser will no longer allow the form to be submitted if these fields are empty.
4. Refactors the year of birth field within `ProfileFormFields.js` to be reused in multiple places.
5. For the flexible price form, this PR uses the testify statement next to …
> 1508: screen readers should not pronounce * ("star") for labels

- frontend/public/src/components/forms/ProfileFormFields.js
mitodl/hq#1128
Compresses the professional demographic fields down so they take up less space, allowing the additional fields modal to fit above the fold on smaller viewports, and reduces the need for scrolling to view the form and submit button.
Using a user that does not have the additional fields flag set and is enrolled in a course, attempt to navigate into the course. You should see the Provide More Info modal. Selecting Professional from the "Are you a" choices should show the additional professional demographic fields (Company, Job Title, etc.), and the bottom of the modal including the submit button should be viewable if your window is greater than about 850 pixels tall. 
We can try migrating the fields to the right of the modal as even with these changes the modal will still …
> Reworks extra fields form to compress things so the modal fits above the fold on smaller viewports

- frontend/public/src/components/forms/ApplyCouponForm.js
https://github.com/mitodl/mitxonline/issues/1509
Using a screen reader on the http://mitxonline.odl.local:8013/cart/ page, if you focus on the "Apply" button, you should hear "Apply discount" instead of "Apply".
1. Login to mitxonline.
2. Begin enrollment into a product-based course.
3. At the http://mitxonline.odl.local:8013/cart/ page, verify that screen reader will pronounce "Apply discount" when focusing on the "Apply" button.
> Add aria-label to apply button

- courses/api.py
- courses/api_test.py
- courses/management/utils.py
#1487 
This PR is a minor fix as per this [comment](https://github.com/mitodl/mitxonline/issues/1487#issuecomment-1478561939)
- Local MITxOnline and edX should be running
- Enroll in any course run in any mode
- The course in which you enrolled must have another unexpired course run
- Run this command
`defer_enrollment --user <USER_EMAIL> --from-run <CURRENT_COURSE_RUN_ID> --to-run <UPCOMMING_COURSE_RUN_ID>`
- `--from-run` should be the Course Run Id in which you are already enrolled
- `--to-run` should be the Course Run Id in which you want to enroll
- Both course run Ids should be of the same Course
> fix: management command for deferring users with course mode

- frontend/public/src/components/forms/ProfileFormFields.js
https://github.com/mitodl/mitxonline/issues/1506
Provides screen readers with better context for the checkboxes below "Are you a" on the profile form.
1. View the profile form.
2. Using a screen reader, navigate between the checkboxes under "Are you a".  The screen reader should pronounce "Are you a <option>", such as, "Are you a student".
> 1506: Provide screen reader context for user profile forms

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/containers/pages/DashboardPage.js
https://github.mit.edu/mitxonline/mitxonline-issues/issues/123
https://github.com/mitodl/hq/issues/703
1. When using a screen reader, visiting either the course or program tab on the dashboard should not read all of the records in the list.  
2. Visiting the program drawer should announce that "you are currently inside of a dialog" and not "you are currently inside of a group"
It's helpful to compare RC with this branch running locally in order to understand the differences.
> 123: remove use of aria-hidden and aria-live on dashboard

- authentication/pipeline/user.py
- authentication/pipeline/user_test.py
- authentication/serializers.py
- authentication/serializers_test.py
- authentication/views_test.py
- frontend/public/src/components/forms/EmailForm.js
- frontend/public/src/components/forms/LoginPasswordForm.js
- main/settings.py
- users/serializers.py
- users/serializers_test.py
- users/views_test.py
https://github.com/mitodl/mitxonline/issues/1538
https://github.com/mitodl/mitxonline/issues/1536
1. User records that have `is_active = False` should not allow the user to login.
2. For the password and email login screens, if a valid user record matching the email is not found or their password does not match the user record, an error message should be displayed to the user.
1. Go through the registration process for a new user.
3. Once the user is created, go through Django admin and set `is_active = False`.  Logout with that user.
4. Attempt to log back in with that user.  The email login screen should present an error that the user was not found.
5. Through Django admin and set `is_active = True`
6. Attempt to log back in with that user but stop once you reach the password login …
> 1538 users are still able to log in using a retired email account

- test_requirements.txt
None, The package is gone from PyPI, and we should remove it.
More info on [this slack thread](https://mitodl.slack.com/archives/G3A5RSFDJ/p1681318942371839) and the following conversation.
- Removed the codecov package from `test_requirements.txt`
Make sure the CI checks pass.
> fix: remove codecov because it's gone from PyPI, the codecov action would do it anyway

- frontend/public/src/components/forms/ProfileFormFields.js
https://github.com/mitodl/mitxonline/issues/1541
Brings back the react component to display error messages from the serializer for the username field in the registration form.
Begin the registration process.  When asked to enter a username, enter a username that matches an existing user.  Submit the form and verify that an error message is shown indicating you need to pick another username.
> 1541: Add back the username is taken error message in the registration form

- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
https://github.com/mitodl/mitxonline/issues/1549
Fixes a bug that would cause the program record page to be blank if the program didn't have any elective or required courses, or if either of those sections were absent.
1. Create a program that has 1 or more required courses, but does not have any elective courses.
2. Enroll your user into the program.
3. From the program drawer, open the program record page.
4. Verify that the program record page displays correctly.
5. Remove the elective courses section from the program record within Django Admin.  Save the program record.
6. Verify that the program record page displays correctly.
I made the `walkNodes()` method public in order to make testing easier.  Not best practice, but also makes things easier for future developers to update and …
> 1549: Fixes program record with null nodes and no children with tests

- frontend/public/src/components/OrderSummaryCard.js
- frontend/public/src/components/UserMenu.js
- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/containers/ProductDetailEnrollApp_test.js
- frontend/public/src/containers/UpsellCardApp.js
- frontend/public/src/containers/pages/checkout/CartPage.js
- frontend/public/src/containers/pages/checkout/OrderHistory.js
- frontend/public/src/containers/pages/records/LearnerRecordsPage.js
Update for Bootstrap v5.
https://github.com/mitodl/hq/issues/1294
Resolves a bug that would clip the dropdown menu on the right side of the screen when a user's full name was short (2 characters).
1. Update your user's full name to "aa".
2. Click on the dropdown menu in the top right of the screen and ensure it is completely visible and not clipped.
This also updated "text-right" to "text-end" and "text-left" to "text-start" to comply with Bootstrap 5.
> 1294: Update "right" and "left" to "end" and "start"

- frontend/public/scss/top-app-bar.scss
- frontend/public/src/components/TopAppBar.js
https://github.com/mitodl/hq/issues/1295
The hamburger menu was not functional when screens were _medium_ width (https://getbootstrap.com/docs/5.0/layout/breakpoints/#available-breakpoints)
1. Set the width of your browser screen to each of the breakpoints mentioned in the link shared above.  Verify that you can view whichever menu is shown based on the browser screen size.
This PR removes the css transition that comes with Bootstrap navbars.  Previously, we wouldn't display the animation and would only shown the navbar options after the animation completed.  Removing the animation speeds this up.
There is also some general refactoring to cleanup reused code.
> 1295: learner menu stops functioning at a particular width range

- frontend/public/scss/layout.scss
- frontend/public/scss/order-history.scss
- frontend/public/src/containers/pages/checkout/OrderHistory.js
Fix https://github.com/mitodl/hq/issues/718
Updates the order history page to display a proper table so that screen readers work.
Go to orders history page. Make sure it looks good. Then use a screed reader to go over the order history structure.
> Order History Page table makeover

- frontend/public/scss/product-details.scss
- frontend/public/src/containers/UpsellCardApp.js
Sets the background color of the upsell card badge to a lighter red color if bg-danger is used.
https://github.com/mitodl/hq/issues/1302
Sets the background color of the danger badge to a lighter red which allows the red text to be seen.
1. Enroll your user into a course for free.
2. Ensure that the course enrollment is synced with edx (or at least `Edx enrolled` is set to `True` for the course run enrollment).
3. Visit the course about page and verify that the "Enrolled in free course" badge is styled in the same way as the attached screenshot.
> 1302: Set bg-danger to lighter red

- fixtures/common.py
- users/serializers.py
- users/serializers_test.py
The additional info dialog doesn't ask for a state if you're in the US or Canada, so if your account doesn't have one specified, that fails and it results in annoying the learner. So, this updates to only check the state if one is sent in the payload. (The front end validation on that field for the forms that have Country and State will require the learner to specify it there.)
https://github.com/mitodl/hq/issues/1332
Updates the state field validation in the serializer to only run if the state is specified. If left blank, it should consider that a valid value.
1. Create a new account, or identify an existing one to use for this. 
2. Enroll them in a course. 
3. Via Django Admin, change the legal address saved in the account to have country set to `US` or `CA` …
> Update legal address validation to check state validity only if specified

- frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
n/a
There was some test stuff added to the `RegisterAdditionalDetailsPage` page title that slipped through checks - this just removes that. 
Either register a new account or go to `/create-account/additional-details/` with an existing account. The page title should be `MITx Online | Register`.
> Reverts the page title on the additional details page

- requirements.txt
Also gets rid of the chardet dependency.
Updates the `requests` package.  This removed the dependency on the `chardet` package which is out of date (https://github.com/mitodl/mitxonline/pull/993).  
Tests should pass.  All uses of request should continue to function as expected - this can be tested by creating a user and ensuring the `openedx.models.OpenEdxApiAuth` record is created and matching the associated record in edx.  When in RC, additional verifications such as recaptcha and refunding orders can be easily tested.
> Update requests package

- openedx/api.py
- openedx/api_test.py
- openedx/exceptions.py
- openedx/management/commands/update_edx_profiles.py
- users/models.py
https://github.com/mitodl/hq/issues/1118
Three things:
- Updates the fields that are sent when a learner's account is created in edX. Prior to this, the code always sent the user's country as "US"; now it sends the code that the learner has specified and the state they're in if they're in the US. 
- Adds an API that allows for this data to be re-sent to edX. This syncs name, country, and state (if in the US) and can be amended to sync other data if we feel the learner profile in edX needs to be more complete.
- Adds a management command to sync a particular user, or all users. 
Initial field sync:
1. Create a new account.
2. Specify a country and (optionally) state (depending on country selection).
3. Verify the account information in the LMS Django Admin. The country and state should be …
> Updates fields that are sent to edX and adds profile sync

- frontend/public/src/containers/pages/register/RegisterDetailsPage.js
- users/serializers.py
- users/serializers_test.py
https://github.com/mitodl/mitxonline/issues/1580
Updates the UserSerializer to throw a validation error if the email address isn't actually unique. While there was a database constraint on this, that considers case differences as unique. So, the email validation function has been expanded to do a case insensitive search for the email address, and to also strip whitespace before doing the check. 
This also adds some code to the RegisterDetailsPage component to display an email error using the standard user notification system (since we don't expose the email field on the form). 
1. Open two separate browsers or browser sessions (incognito, etc.)
2. Navigate to the Create Account page in each.
3. Supply an email address in one in all lowercase.
4. Supply the same email address in the other …
> Throw an error if the user manages to get to the registration screen with the same email

- users/models.py
- users/models_test.py
#1588 
If the user's in the US and has not specified a state, the `us_state` property in `legal_address` should just be None. 
1. Update a user account to have the country set to US and no state specified (you may need to set this up in Django Admin).
2. Attempt to update the edx profile for that user with the `update_edx_profiles --user` command. This should succeed.
> Fixes us_state to return None if there's no state; adds a test for that

- flexiblepricing/data/country_income_thresholds.csv
https://github.com/mitodl/mitxonline/issues/1583
Adds the income threshold for Argentina which is used to automatically detect financial aid eligibility.
1. Get this branch running locally
2. Follow the instructions in this PR https://github.com/mitodl/mitxonline/pull/590 in order to load currencies.
3. Run `docker-compose run web ./manage.py load_country_income_thresholds flexiblepricing/data/country_income_thresholds.csv`
4. Verify that 'AR' has been added here: http://mitxonline.odl.local:8013/admin/flexiblepricing/countryincomethreshold/
5. login to your local instance of MITx Online.
6. Set your user's country to Argentina.
7. Apply for financial aid for a course and enter the user's income as more than 50000 USD.
8. Verify that the financial request was automatically approved here: …
> Add AR Argentina

- frontend/public/src/components/ProgramEnrollmentDrawer.js
https://github.com/mitodl/mitxonline/issues/1598
There was a stray `aria-hidden` attribute on the program drawer; this removes it. (This was the only one I could find via grep.) 
The issue with the program drawer noted in https://github.com/mitodl/mitxonline/issues/1598 should be resolved - there's a lot there so it's better to reference the original issue. 
I couldn't find the first issue - I didn't see any `aria-live` attributes anywhere other than in the notification container (which would actually need one). The ticket for this came out pretty soon after the PR @collinpreston mentioned was merged so this might have been fixed already.
> Removes a stray aria-hidden attribute

- cms/models.py
- cms/models_test.py
- cms/templates/flexiblepricing/flexible_pricing_request_form.html
https://github.com/mitodl/mitxonline/issues/1605
Populates the cart with the product related to the flexible price request when a user clicks the "Get Certificate" button from the approved flexible price request screen.
- Use a course run with a start date and start enrollment date in the past, and end date in the future, which is also configured with a course that has flexible pricing configured.
- Apply for flexible pricing on the course.
- Through the staff dashboard (http://mitxonline.odl.local:8013/staff-dashboard/), approve your flexible pricing request.
- Navigate back to the flexible pricing request screen and you should be presented with a button labeled "Get Certificate".
- Verify that when you click this button you are redirected to the cart page which contains the course run …
> 1605: get certificate button on approved flexible price leads to empty cart

- .github/workflows/ci.yml
- .pre-commit-config.yaml
- hubspot_sync/tasks.py
- hubspot_sync/tasks_test.py
- requirements.in
- requirements.txt
Closes #1350 
- Uses the new version of mitol.hubspot_api which can handle conflicts caused by a Hubspot contact having 2 emails associated with different mitxonline users
- Modifies the batch create/update tasks to try syncing contacts individually (to hit code above) if any API exceptions occur when running batch sync operations.
- Ask for access to the mitxonlinedex sandbox account for hubspot if you don't already have it.
- Copy the `HUBSPOT_*` settings values from RC to your .env file
Part 1:
- Create a new user in mitxonline, something like `fake_user+1@gmail.com`
- Find the contact in hubspot (may take a minute or so to show up) and add a secondary email to that contact: `fake_user+2@gmail.com`
- Create another new user with that same email - `fake_user+2@gmail.com`
- Check back on …
> Use new hubspot_api version and try to sync contacts individually if a batched sync chunk fails

- authentication/serializers.py
- authentication/serializers_test.py
https://github.com/mitodl/hq/issues/1374
Queries users by their `User` record's email address instead of their `SocialAuth` records email address during the login process.
1. Using an existing user or register a new user, go to the Accounts page (http://mitxonline.odl.local:8013/account-settings/)
2. Update the user's email address to include a period before the @ sign (`myname@email.com` -> `my.name@email.com`). Gmail will treat both of these emails as the same.
3. Confirm the email change using the link in the email you receive.
4. Logout of MITx Online.
5. Verify that you can log back into MITx Online.
When a user changes their email address, their social auth record is removed.  Before this PR, the login screen would search for a matching social auth record, if found the user would be …
> Find user by account email not social auth email

- RELEASE.rst
- cms/models.py
- cms/models_test.py
- cms/templates/flexiblepricing/flexible_pricing_request_form.html
https://github.com/mitodl/mitxonline/issues/1615
Fixes an issue in the most recent release which was thrown when user's viewed the flexible pricing form for Programs.  Programs don't have an `active_products` attribute which is used to derive the product ID that is used to populate the Cart from the approved Flexible Pricing page.
1. Configure a Program, Program Run, Product associated with the program, Page and Flexible Price form for the Program through CMS, and a user.
2. View the program page.  You can find the Program page's URL from within the CMS.
3. Apply for Flexible Pricing on the program.
4. Approve the flexible pricing request through http://mitxonline.odl.local:8013/staff-dashboard/
5. From the program page, launch the flexible pricing request form again (same as step 3). …
> Fix flexible pricing page for programs

- hubspot_sync/tasks_test.py
- requirements.in
- requirements.txt
Closes #1619 
Updates mitol/hubspot_api app to the latest version.
The testing instructions for [this older PR](https://github.com/mitodl/mitxonline/pull/1607) should still work as described.
Also try this:
- Manually create a new contact in the mitxonlinedev sandbox account of Hubspot.
- Register a new user in mitxonline with the same email address.
- After verifying email, fill out the user/profile details.  There should be no hubspot ApiExceptions in the log and the details should soon be mirrored for the hubspot account you created manually.
> Update mitol/hubspot_api app

- openedx/api.py
- openedx/api_test.py
- openedx/tasks.py
- users/models.py
- users/models_test.py
- users/views.py
- users/views_test.py
Closes #1620
Addresses issues raised in https://github.com/mitodl/hq/issues/1118
- Adds gender, year of birth, and level of education fields to the list of fields we now sync with edX.
- Updates the user profile API to sync the profile data on save. 
You will need to have a working edX instance for this - either Tutor or devstack should work (tested on Tutor). 
Manual sync:
1. Change an account's user profile gender, year of birth, or highest education fields via Django Admin/dbshell/other method that's not the normal frontend.
2. Run `manage.py update_edx_profiles --user <username>` where `<username>` is the username you edited. 
3. Check the data in edX - I found this was easiest to do using the Swagger interface (ex: http://local.overhang.io:8000/api-docs/#/user/user_v1_accounts_read …
> Expands edX profile sync.

- main/settings.py
Removes the scheduled cron task which syncs all of the MITx Online users with HubSpot.  This was run on 05/25/2023 and all MITx Online users, except 85, were synced.  There is no need to run this task nightly since it should only be run when new User fields are intended to synced to HubSpot contacts.
> Remove scheduled cron task to sync all HubSpot contacts

- frontend/public/src/containers/pages/checkout/OrderHistory.js
Fix https://github.com/mitodl/hq/issues/718
Add row header to order history table
Use a screen reader to make sure that it reads the row index.
> Add row header to order history table

- courses/management/commands/create_local_enrollments.py
https://github.com/mitodl/mitxonline/issues/1597
Adds a management command to create local enrollments from edx in bulk.
e.g.
```
./manage.py create_local_enrollments --runs course-v1:edX+E2E-101+course course-v1:edX+DemoX+Demo_Course
```
It doesn't handle updates to local enrollments if exist or there are enrollment changes on edx
1. Make sure courses are created in your local edx instance and MITx Online app. If not, create courses from admin/course_overviews/courseoverview/ for edx, and admin/courses/courserun/ for MITx Online app
2. Create some enrollments on your local edx instance from admin/student/courseenrollment/.  To access this URL, `student.courseenrollment_admin` switch needs to be created
3. Run `./manage.py create_local_enrollments --runs <COURSE IDs>`, you should see the …
> add management command to create local enrollments from edx

- frontend/public/scss/receipt.scss
- frontend/public/src/components/ReceiptPageDetailCard.js
https://github.com/mitodl/hq/issues/1521
Updates the receipt code in the frontend to use the global support email setting. It was hardcoded (twice, once incorrectly) before.
Updates the stylesheet to make room for the support email address.
Open a receipt. The email address listed under Support should be support@mitxonline.mit.edu both in the text and in the URL.
(See the top left to see what Bootstrap breakpoint is being targeted for the first 4.)
> Updates the email address on the frontend to use the value from settings

- courses/api.py
- courses/api_test.py
- courses/management/commands/defer_enrollment.py
- courses/management/utils_test.py
none
Make deferral functionality atomic and clarify errors when it is not successful.
If any api call to edx is not successful abort the whole procedure and write an appropriate message.
You can test it  by running a management command `defer_enrollment`:
`manage.py defer_enollment --user <username> --from-run <from_course_run_id> --to_run <to_course_run_id> `
If the api call to edx fails then you should see an appropriate message, and the whole operation should be aborted. Check that locally the enrollment was not set to 'deferred'.
And if you run it with another argument `--keep-failed-enrollments` then it should defer the enrollment locally even though the call to edx failed. Then it should still complete the deferral locally.
> Make deferral functionality atomic and clarify errors

- openedx/api.py
- users/models.py
- users/models_test.py
- Adds lookup tables for gender and US state
- Adds some edx-specific properties for gender and US state
- Updates the profile sync API to use the edx properties
Closes #1649 
@collinpreston noted that the edX profile sync was failing; some investigation found that the gender codes and states that edX uses are a subset of the ones supported in MITx Online. This PR adds lookup tables for those and adds some edx-specific properties that the sync API will now use.
Change your country to United States and state to one of the ones listed in `EDX_STATE_CHOICES`. The choice should sync to edX when your profile is saved, or if you manually sync from the command line.
Change your country to United States and state to one of the ones _not_ listed in `EDX_STATE_CHOICES` (such as American Samoa). The …
> Adds validation for edX profile fields

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/ProgramEnrollmentDrawer.js
https://github.com/mitodl/hq/issues/703
1. Removes `aria-haspopup`.
2. Removes `aria-flowto`.
3. Uses `aria-describedby` instead of `aria-description`.
4. Enables the Program Dashboard to close when the escape key is pressed
1. Enroll a user into a Program.
2. From the Dashboard, open the Program tab and Program Dashboard.
3. Ensure that the screen reader performs as expected by identifying the modal and description.
4. Ensure that pressing the escape key will close the Program Dashboard.
> 703: navigation drawer component not screen reader accessible round 2

- ecommerce/api.py
- ecommerce/api_test.py
If the supplied order was paid for via PayPal, throw an exception immediately and quit.
Closes #1654
In `refund_order`, if the order contains a transaction that's a PayPal one, throw an exception with an appropriate error message and stop processing. This should ensure a more useful error message gets written to the Google Sheet.
Automated tests should pass. Full testing will require that you have a refund workflow set up (including the Google Sheets integration). Test by completing checkout using PayPal as the payment method, and then attempting to refund through the sheet; you should get a "PayPal: Order x contains a PayPal transaction" error.
> Updating refund_order API to check for PayPal

- courses/api.py
- courses/api_test.py
- courses/management/commands/test_unenroll_enrollment.py
- courses/serializers.py
- courses/views/v1/__init__.py
- courses/views_test.py
- ecommerce/api.py
- ecommerce/models.py
- ecommerce/models_test.py
- hubspot_sync/api_test.py
- hubspot_sync/conftest.py
- hubspot_sync/management/commands/configure_hubspot_properties.py
- hubspot_sync/serializers.py
- hubspot_sync/serializers_test.py
- users/serializers.py
https://github.com/mitodl/hq/issues/904
1. When a user enrolls into a course, a Deal is created in HubSpot along with Line items that contain information on the `enrollment_mode` and `change_status` related to the user's enrollment in the associated course run.
2. When a user proceeds to upgrade or pay for the certificate track (verified) for a course run, the existing `PendingOrder` is used for initializing the checkout workflow.
3. At the time of checkout, if there are no PendingOrders associated with the user that contain Line items matching the products found in the cart, then a new PendingOrder is created.
4. When a user unenrolls from a course run, the Line item in HubSpot is updated.
5. When a user has a FulfilledOrder but their associated CourseRunEnrollment is not synced with …
> 904: tracking audit enrollments for mitx online courses in hubspot

- courses/api.py
- courses/api_test.py
- courses/management/commands/test_unenroll_enrollment.py
- ecommerce/factories.py
https://github.com/mitodl/mitxonline/issues/1662
Handles the scenario where a user un-enrolls from a course which is not associated with an Order or Line object in MITx Online.  These situations exist for audit enrollments prior to 06/08/2023 when Orders and Lines are created at the time of enrollment.
1. Enroll into a course run.
2. [Through Django Admin](http://mitxonline.odl.local:8013/admin/ecommerce/order/), delete the associated Order created.  This will replicate the environment that enrollments prior to the merging of https://github.com/mitodl/mitxonline/pull/1644 look like.
3. Through MITx Online, unenroll your user from the course from step 1.
4. Verify that no errors are shown in the logs.
> Handle un-enrollment prior to audit enrollment Order creation feature

- courses/api.py
- courses/api_test.py
- courses/management/commands/test_unenroll_enrollment.py
- hubspot_sync/task_helpers.py
- hubspot_sync/tasks.py
https://github.com/mitodl/mitxonline/issues/1666
1. Handles the return from the filter query for Line objects correctly.
2. Handles any exception returned by HubSpot as to not hinder the user from unenrolling from the course.
- Enroll a user into a course.
- Verify that an Order object is created in MITx Online for the enrollment.
- Unenroll from the course.
- Verify no errors are being displayed in the logs and the user is able to unenroll.
- Enroll a user into a course again.
- Remove or comment out your HubSpot settings from your `.env` file.
- Restart MITx Online and attempt to unenroll from the course again.
- Verify that the user is not hindered from unenrolling from the course.
> Handle HubSpot exceptions when unenrolling from a course

- ecommerce/models.py
- ecommerce/models_test.py
- ecommerce/views_test.py
- flexiblepricing/api_test.py
- requirements.in
- requirements.txt
- test_requirements.txt
Closes #1630 
https://github.com/mitodl/hq/issues/1498
Adds some date checking to the `save` method in the Discount model:
- Expiration date, if specified, should be after activation date (if it too is specified)
- Expiration date, if specified, should not be in the past
Create a Discount with an expiration date in the past. You should receive an error.
Create a Discount with an activation date in the future, and an expiration date before that. You should receive an error.
Create a Discount with no activation or expiration date. This should be successful.
Create a Discount with either an activation date or an expiration date in the future. This should be successful.
> Adding date checks to Discount model

- courses/management/commands/create_verified_enrollment.py
- courses/views/v1/__init__.py
- ecommerce/api.py
- ecommerce/management/commands/refund_fulfilled_order.py
- ecommerce/models.py
- ecommerce/models_test.py
- hubspot_sync/management/commands/create_order_from_course_run_enrollments.py
https://github.com/mitodl/mitxonline/issues/1664
A recent PR ([ref](https://github.com/mitodl/mitxonline/pull/1644)) now creates an Order object when a user enrolls into a course.  The Order object's information is synced with HubSpot which allows Marketing team members to view user enrollment information.  **This PR** intends to add a management command that will create an Order for each of the existing audit enrollments.
1. Setup a Course, CourseRun, Product, User, and the CMS page for the course.
2. Configure the required HubSpot environment variables in your `.env` file.
3. Enroll your user into the Audit track of the course by clicking the "Enroll now" button but not purchasing the course.
4. Through Django Admin, delete the Order associated with your enrollment: …
> 1664: management command to create Order from enrollment

- frontend/public/src/components/EnrolledItemCard.js
Part of #1685 
The course count in the program cards in the My Programs tab was incorrect - it was looking through the program requirements, but we have a flat list of courses in the data structure that can be used instead.
Add a program with a nested operator and course requirements within that operator. (Use DEDP as an example of this - you can take one elective, or one of a set of two electives, to satisfy the electives requirement.) The course count should display the correct number.
> Fixes the course count on cards in My Programs

- courses/migrations/0033_populate_letter_grades.py
- courses/migrations/0034_backfill_enrollments_from_certificates.py
- courses/utils.py
https://github.com/mitodl/mitxonline/pull/1651
https://github.com/mitodl/mitxonline/pull/1687
Fixes course migrations conflict on the main branch
`
Static file directory was missing: /home/runner/work/mitxonline/mitxonline/frontend/public/build Static file directory was missing: /home/runner/work/mitxonline/mitxonline/frontend/staff-dashboard/build CommandError: Conflicting migrations detected; multiple leaf nodes in the migration graph: (0031_backfill_enrollments_from_certificates, 0031_populate_letter_grades, 0032_add_related_programs_table in courses). To fix them run 'python manage.py makemigrations --merge'
`
Run migrations from 0030
```
manage.py migrate --fake courses 0029 (run this if you have already applied 0030_remove_course_position_in_program.py)
manage.py migrate courses …
```
> fix courses migration conflict

- courses/api.py
- courses/api_test.py
- courses/management/commands/test_manage_program_certificate.py
https://github.com/mitodl/mitxonline/issues/1691
This was a regression that was introduced with https://github.com/mitodl/mitxonline/pull/1685.
Required: User, program, 3 courses.
Using a program which has electives like:
- Minimum of 2 course certificates from the following courses:
- Course1
- Only one certificate is counted from the courses below:
- Course2
- Course3
- Add course certificates for your user for Course2, Course3.
- A program certificate is generated for your user.
> 1691: program certificate generation does not adhere to nested program electives

- hubspot_sync/api_test.py
- hubspot_sync/serializers.py
- hubspot_sync/serializers_test.py
https://github.com/mitodl/mitxonline/issues/1702
Until recently, the Line serializer did not rely on CourseRunEnrollment.  There is the possibility that old data exists for a learner who unenrolls or has no enrollment for an Order and Line.
1. Create a user, course, course run, product.
2. Create an order for your user referencing the items from step 1.
3. Run the following management command `sync_db_to_hubspot --deals create`.
> 1702: line serializer cannot handle orders with no current enrollment

- ecommerce/api.py
Fixes # https://github.com/mitodl/mitxonline/issues/1705
remove the atomic block and rollback
tests should pass
The atomic block is not needed since we are not updating the database. After the api call to Cybersource was made usually a second attempt doesn't work: `Error: Declined - The transaction identifier sent with this request has already been used in the last 60 days`
> Refund Order: remove atomicity and rollback

- micromasters_import/management/commands/queries/008_import_combined_final_grade.sql
- micromasters_import/management/commands/queries/013_add_missing_enrollments_from_certificates.sql
https://github.com/mitodl/hq/issues/1561
This PR is to modify `letter_grade` in the grade script for MicroMasters import. It also adds a new script to populate the missing enrollments after certificates migration as enrollments might be deleted from MM
Run `docker-compose run --rm web ./manage.py import_micromasters_data --num 013` for the new script
If you need to run other scripts, please follow [this](https://github.com/mitodl/mitxonline/tree/main/micromasters_import#local-setup) instruction 
There are some MM users who register on MITx Online after we ran the initial migration in Oct 2022, those users data are still in MicroMasters so we need to run micromasters_import script to bring over their enrollment/grades/certificates
> Update MM grade import, add missing enrollment import script

- ecommerce/models.py
- ecommerce/models_test.py
Closes #1715 
When a learner attempts to check out, their basket is converted to a pending Order. If there's already a pending Order for the learner with the same items in it, the system will reuse that existing Order. This is fine, but if the pending Order had discounts applied to it, those discount redemptions will stick around in the new order - they don't have an effect on the amount charged but they do count as redemptions for the discount, which could potentially result in a discount code becoming invalid when it shouldn't. (And, it definitely causes issues for reporting as we only support a single discount per order.) 
This adds some code to delete any DiscountRedemptions that exist for the order if it's being reused. Any discounts applied are applied to the user's basket first, so …
> Clears discounts when reusing an existing PendingOrder

- courses/api.py
- sheets/deferrals_plugin.py
Related to https://github.com/mitodl/ol-django/issues/123
Adds an option to process only change of enrollment mode in deferral google sheets functionality
Make sure you have google-sheets-deferrals set up and it is getting processed from your local mitxonline instance.
In Django admin make sure you have an active enrollment for a course run.
Open the Deferrals Request Form and create a request without providing "To Run".
The request should get processed successfully, and the enrollment should change mode to "audit".
> Add unverify option to google sheets plugin

- cms/serializers.py
- courses/serializers.py
- courses/serializers_test.py
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/courseTypes.js
Closes #1714 
- Adds a ProgramPageSerializer
- Updates the ProgramSerializer to include the featured image if there is one (same logic as for courses - you get the MIT dome if there isn't one)
- Updates EnrolledItemCard to include the featured image
- Fixes tests and types accordingly
You will need to make sure your local copy can serve static images uploaded via Wagtail. (For me, this involved making some minor adjustments to the `docker-compose.yml` and the `nginx.conf.erb` files.) 
1. In Wagtail, update a program page for a program that you're enrolled in so that it has a featured image. 
2. Navigate to the dashboard and switch to the My Programs tab when it appears.
3. Observe. The program you updated should show the new image, and any remaining ones should get the standard MIT dome …
> Added support for featured images in programs

- ecommerce/admin.py
- ecommerce/api.py
- ecommerce/api_test.py
- sheets/refunds_plugin.py
Fixes https://github.com/mitodl/mitxonline/issues/1671
Updates the refund_order to return error messages along with the success value.
Have google sheets refunds setup and running locally, being processed by your local mitxonline instance.
Submit a request that has order reference number missing, or missing transaction for the order, or order not being in a "Fulfilled" state.
In the Refunds tab you should be able to see these errors in the error column
> Refund Order should return propper error message

- hubspot_sync/api.py
- hubspot_sync/api_test.py
- hubspot_sync/management/commands/create_order_from_course_run_enrollments.py
- hubspot_sync/task_helpers.py
- hubspot_sync/task_helpers_test.py
- hubspot_sync/tasks.py
- hubspot_sync/tasks_test.py
https://github.com/mitodl/mitxonline/issues/1718
This PR makes a few improvements to the current HubSpot api in MITx Online, specifically:
1. Retrieves all objects (User, Order, Product, Line) in one database query when making batch update/create calls to HubSpot.
2. Passes objects (User, Order, Product, Line) as parameters when possible to avoid repetitive database queries.
The steps below just ensure that everything still functions as expected.  To really test whether this PR will improve the speed of bulk create/update requests to HubSpot, we will need to test this in RC.
1. Configure MITx Online with HubSpot (ask if you need assistance with this).
2. Create a new product through Django Admin.
3. Register a new user in MITx Online and verify that a new contact is created in HubSpot.
4. …
> 1718 improve hubspot bulk update database queries

- Procfile
https://github.com/mitodl/mitxonline/pull/1733
In order to test https://github.com/mitodl/mitxonline/pull/1733 in RC, we must have the hubspot task queue added to the "worker" dyno.  This is because there is no "extra-worker" dyno in RC.
I believe we can only test this once it's in RC.
> Add hubspot task queue to worker dyno

- ecommerce/models.py
- ecommerce/models_test.py
#1734 
Updated the discount redemption code slightly to help eliminate the possibility that discounts aren't reapplied from the basket if the order is reused. (I think the issue is that clearing the old discounts from the order object works, but then the order object becomes stale and at that point the basket discounts can't be reattached. The fix is to just explicitly refresh the order object.) 
This will be easiest to do with Django Admin open in a separate window from the app. (I have been testing with a new user account so things are easier to see.) 
0. Ensure either financial assistance or a set of discounts are set up in the system. 
1. Create an order in the system. Progress to the CyberSource portion of it and ensure the proper price is set, then abandon the cart manually (go back …
> Updates the discount redemption cleanup code to be more resilient

- cms/models.py
- cms/models_test.py
- cms/templates/product_page.html
- frontend/public/scss/product-details.scss
Fixes https://github.com/mitodl/hq/issues/1647
Updates more dates popup. Removes the link for the future course runs(enrollment date in future). Also, display the enrollment date for such runs.
Create 2-course runs. One with an enrollment date in the past and one with an enrollment start date in the future. Visit the course detail page. Verfiy that the more dates pop up has 2 runs, 1 is a clickable link and other one is just date with enrollment start date as well.
> feat: remove link and add description for unenrollable runs in more dates

- courses/serializers.py
- courses/serializers_test.py
- courses/views/v1/__init__.py
Related to #1738
If the program doesn't have a page, the frontend will crash because it expects a featured image. This adds a default featured image if there's no page, so it doesn't. 
1. Create a new program. (Manually using the Django Admin is the recommended method so you don't inadvertently get a page created or anything.) 
2. Create a program enrollment for one of your accounts.
3. Log in and navigate to the dashboard.
4. Click the My Programs page. You should see the new program.
> ProgramSerializer should now return default image if there's no program page

- courses/serializers.py
- courses/serializers_test.py
Fix https://github.com/mitodl/mitxonline/issues/1742
This PR filter only grades earned in a verified more of enrollment for display on the Learner Records page.
1. create a course run grade for your user
2. create a verified enrollment for that course run
3. view Program records, the grade should show
4. then set the enrollment to audit
5. Check the Program Records again, now the grade should not be there
> No audit grades in program records

- courses/forms.py
https://github.com/mitodl/mitxonline/issues/1694
Add validations to the Program Django Admin page to display error messages instead of throwing a 500 error if the requirements tree contains misconfigurations.
1. Ensure you have a couple courses created in your MITx Online instance.
2. Click "ADD PROGRAM" from http://mitxonline.odl.local:8013/admin/courses/program/
3. Define the title and readable ID to be anything unique.
4. Expand the "Required Courses" section.
5. Change the Operation from "All of" to "Minimum # of".
6. Verify that the Value field is displayed.
7. Enter 1 in the Value field.
8. Delete the Elective Courses section.
9. Change the Title to "Elective Courses".
10. Add a course to the Elective Courses section.
11. Verify that the program can be saved.
12. Select the program …
> 1694: added stipulations to program electives causes 500 error in Django admin

- courses/forms.py
https://github.com/mitodl/mitxonline/issues/1758
With the program configuration created from the steps to reproduce (in the issue), a program certificate will never be attainable by a learner. This is because, even if the learner earns course certificates from all 3 courses defined under electives, only a single course certificate from the two courses belonging to the nested operator will be counted. So there is no way to earn the required 3 applicable course certificates to satisfy the elective requirement.
1. Visit http://mitxonline.odl.local:8013/admin/courses/program/
2. Select "ADD PROGRAM"
3. Define a Title and Readable id
4. Expand the "Elective Courses" section.
5. Set the Value to 3.
6. Click "Add Requirement".
7. Click "Add Requirement".
8. On the item created from step 6, add a …
> Django Admin course validation for Program nested elective operators

- courses/views_test.py
- hubspot_sync/tasks_test.py
https://github.com/mitodl/mitxonline/issues/1764
Improves the integrity of some tests which expected results in a certain order.  Ordering was not integral to the tested functionality.
Tests should pass.
> Ignore ordering in tests where it doesn't matter

- courses/management/commands/import_courserun.py
Closes #1680
Fixes a minor error when creating a standalone course using import_course. (This came about after testing the command for #1680.) The command would try to add a program to the new course (even if the program was None), which would cause an error because there's no FK to Program anymore.
Full test:
1. In Studio, create three courses. 
2. In MITx Online, create two matching courses (but no courseruns) and assign them to a program. (These can be all electives, all requirements, or a mix.)
3. Run `manage.py import_courseware --program <your program> --run-tag <run tag>`. It should pick up the course runs from edX successfully. 
4. Run `manage.py import_courseware --courserun <the remaining one>` (add whatever other flags you like). It should pick up the courserun and create the …
> Updates import_course a bit for program requirements

- courses/serializers.py
Related to https://github.com/mitodl/hq/issues/1525
Some users have a passing grade, payment, and certificate but no verified enrollment for a course run.
This PR attempts to show grades only if the user enrolled in verified track or received a certificate.
Set up your data to test that the following grades are showing up on the Program Records page:
1) The user has a grade and a certificate for course
2) The user has a grade and a verified enrollment for a course run (the grade may be failing)
> Program records: show verified grades or grades with certificate

- flexiblepricing/management/commands/configure_tiers.py
Closes #1781 
mitodl/hq#2025
Just changes the default tiers to be whole-number percentages. They were decimal but that isn't correct now.
Run `configure_tiers` for a course. You should get the proper discount amounts (0%, 25%, 50%, and 75%) and not ones that are < 1.
> Fixing amounts for the default tiers for the configure_tiers command

- courses/api.py
- sheets/deferrals_plugin.py
N/A
Makes sure the a failed status is returned if enrollment to a course run was not successful.
Removes the atomic block and allows for repeating reruns of the deferral procedure. This is helpful if this deferral request was already processed and partially succeeded.
If an api call was made to to edx to uneroll a user but they already have been unenrolled edx would return 400 and the deferral procedure would throw an error.
There are few things to check:
1) There have been cases where the deferral would not succeed and no exception would get raised, and the row would get marked as completed. An example here https://github.com/mitodl/hq/issues/2009
I was not able to fully replicate that scenario locally, but I would like to pass a message to deferral result for better messaging.
2) If the …
> Deferrals better message

- frontend/public/src/lib/util.js
- frontend/public/src/lib/util_test.js
#1075
This PR removes `assertRaises`. It was not being used, and was causing part of `chai` (our assertion library) to be included in the frontend bundle.
**Before**:
**Now:** 
Everything should work as before.
> remove assertRaises

- cms/management/commands/convert_faculty_to_pages.py
n/a
Noticed that trying to convert instructors to pages for a single course failed - this fixes that.
Run `convert_faculty_to_pages --only <course>` for a course (ideally, one with old-style faculty members in it). The command should run successfully.
> Fixes per-course instructor page migrations

- courses/api.py
- courses/api_test.py
- courses/management/commands/create_verified_enrollment.py
- ecommerce/api.py
- ecommerce/api_test.py
- ecommerce/mail_api_test.py
- ecommerce/models_test.py
- ecommerce/serializers_test.py
- ecommerce/tasks_test.py
- ecommerce/views_test.py
- openedx/api.py
- openedx/api_test.py
Fixes https://github.com/mitodl/hq/issues/1773
We are going to mark courses as invite-only in edX to stop direct enrollments in edX. It will require us to force the course enrollments to bypass invitation checks. This PR forces all the course enrollments.
- Make sure that the MITxOnline / edX integration is working
- Enable `COURSES_INVITE_ONLY` in edX.
- Check out this branch in MITxOnline.
- Verify Audit / Verified Enrollment/Unenrollment, Also, test 100% discount enrollments.
- Verify the following management commands:
- defer_enrollment
- transfer_enrollment
- unenroll_enrollment
- refund_fulfilled_order
- retry_edx_enrollment
- create_enrollment
- create_verified_enrollment
> feat: force all enrollments

- main/utils.py
- main/utils_test.py
https://github.com/mitodl/hq/issues/1981
@JenniWhitman added the PostHog libraries in https://github.com/mitodl/mitxonline/pull/1809 - this adds the settings (`POSTHOG_API_HOST` and `POSTHOG_API_TOKEN`) to the JS `SETTINGS` global so we can use it in the React app. (Basically, I did this already for another PR but splitting it out to not make people wait on it.) 
You'll have to have a Posthog account set up. There's a free tier. You can also self-host it (but that's a lot more stuff to do). You'll also need to follow the instructions at https://github.com/mitodl/hq/discussions/2116 - the easiest method is to use the "JS SDK - component level listening" section to just grab a feature flag out in somewhere (choose a component!) and see if it works or not. You should see some analytics and …
> Adds the PostHog settings to the JS settings so we can use it in React

- frontend/public/src/components/EnrolledItemCard.js
https://github.com/mitodl/hq/issues/2024
This PR fixes the " Enrolled in certificate track" label to count for audit enrollment with a certificate. Currently, if a learner had audit enrollment but earned a certificate (records that migrated from MM) doesn't display " Enrolled in certificate track" on the dashboard, even though there is a link to "view certificate", this PR is to fix that inconsistency.
Before
After 
- Create audit enrollment, passing grade, and certificate for a run
- Go to My Course or My Program on your dashboard
- "Enrolled in certificate track" should now display
- Create verified enrollment, and passing grades for a run, labels should not be affected
> Update to Enrolled in certificate track label to count for audit enrollment with certificates

- courses/api.py
- courses/api_test.py
None
When an enrollment is deferred we always want the enrollment to be verified instead of copying the mode of the enrollment of the "from course".
There has been a case where the user was deferred to a course successfully but set to audit. I don't know why the "from course" was in audit mode, but I think it is safe to assume that when the deferral procedure is run we want to enroll the user in a verified mode.
This would allow for a deferral of cases that were partially complete. 
Try to run the deferral management command while having current 'verified' enrollment for a "From course". Make sure that the user get's successfully unenrolled from the course, and enrolled into the verified mode of the "To course".
Then try the same with an 'audit' enrollment. The same result should proceed.
> When deferring enrollment set to verified

- hubspot_sync/api.py
- users/serializers.py
- users/views.py
https://github.com/mitodl/hq/issues/2182
This PR allows full name get updated on user profile from dashboard. Currently full name isn't updated on MITx Online but it gets updated on edX because `sync_hubspot_user` is called before the update on`CurrentUserRetrieveUpdateViewSet` runs so User.name gets overwritten.
- Go to http://mitxonline.odl.local:8013/profile/
- Edit `Full Name`, `First Name`, `Last Name`, updates should go through locally
- Check `Name` field on your edX instance, it should be updated to match with `Full Name` from MITx Online
- Check  `First Name`, ` Last Name` field of contact in Hubspot `rl-mitxonline-dev`
Full Name on MITx Online doesn't map to any field in Hubspot
> update full name on user profile

- frontend/public/scss/meta-product-page.scss
- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/containers/UpsellCardApp.js
Part of #1773
The text on the Enrolled button wasn't aligned properly, and the upsell card was appearing erroneously when the new design is turned on. This fixes both of those issues.
Additionally, after a discussion with @JenniWhitman , I've reworked what gets imported by default in here to just pull in the framework stuff and global variables into the feature flagged CSS loader. This should keep different flagged features from stepping on each other. This should be functionally equivalent to the previous code - it should all work the same.
Toggle the new design on and go to a course that you have an audit enrollment in. The text for the Enrolled button should be centered in the button, and you should not see the upsell card.
Toggle the new design off and reload the page a couple of …
> Fixes text alignment for the Enrolled button, hide the upsell card in new design

- app.json
- courses/api.py
- courses/api_test.py
- main/settings.py
Fixes https://github.com/mitodl/mitxonline/issues/1675
Increase the window for certificate generation (and current grade syncing) to 30 days. After 30 days current grades on edx get frozen and do not get updated anymore.
Checkout the tests. Tests should pass.
Make sure that course runs with certificate_available_date in the past still get processed as long as it has been less than a month.
> New extended certificate generation window

- cms/models.py
Fixes https://mit-office-of-digital-learning.sentry.io/issues/4435442344/?environment=rc&project=5864687&query=is%3Aunresolved&referrer=issue-stream&stream_index=0
Added a conditional for un-authenticated users to generate and store a session uuid to track each user's session in the feature flag history 
Load up the application, make sure you are not logged in. You should be able to navigate around and in the [posthog event history](https://app.posthog.com/events), see a random UUID on your requests - but it should be the same UUID for your requests.
The home page should no longer 500 whether you are logged in or not.
> Anonymous user handling for posthog

- frontend/public/webpack.config.js
#1075 
This PR changes how filenames are generated by webpack: Now, filenames only change when content changes. If you change a CSS file, the JS filename will not change.
1. Enter the `watch` container: `docker compose exec watch bash`
2. Run production build: `yarn workspace mitx-online-public build --clean`, `ls frontends/public/build`.
- note the filenames for `requirementsAdmin` chunk
3. Make a temporary change to `requirements.scss` 
4. Run production build: `yarn workspace mitx-online-public build --clean`, `ls frontends/public/build`.
- note the filenames for `requirementsAdmin` chunk
- The JS file should have the same name, the CSS file should have a different name.
> Make hashed webpack output filenames more stable

- cms/models.py
https://github.com/mitodl/mitxonline/issues/1842
Removes a duplicate method which was introduced in this PR: https://github.com/mitodl/mitxonline/pull/1816/
All tests should pass and the ProductPage model should function as expected.
> 1842: duplicate ProductPage get_context method in model

- cms/models.py
- main/features.py
- main/settings.py
Fixes https://github.com/mitodl/mitxonline/issues/1850
Removed the initialization of the posthog client from features.py and models.py and created the client in settings to be imported as used.
Ensure feature flags still work and can be toggled while active. Trying to come up with a meaningful load test, but it might need to happen on RC (anything I've thought up is more cumbersome than I think we should be doing for this)
I ended up using more of this: https://posthog.com/tutorials/django-analytics#installing-and-using-the-library than the documentation as documentation's method looks like it's importing the client, but really importing the library without a client connected and does not yet work.
> Posthog refactor 

- main/features.py
https://mit-office-of-digital-learning.sentry.io/issues/4447043519/events/ac4b94e2c30541f1b8961a32a0605775/
Removes the extra line in the posthog call
> Fix the inclusion of an extra variable in the posthog call

- cms/templatetags/expand.py
https://github.com/mitodl/mitxonline/issues/1856
Fixing 500 error on About section if text is less than 2 paragraphs
When there are more than 2 paragraphs, and Show More is displayed
When there is only 1 sentence, display the original text
Edit About section from a course cms page
- add one sentence there, make sure no 500 error
- add more than one paragraphs, 'Show More' should be displayed. It can be toggled which implemented in https://github.com/mitodl/mitxonline/pull/1816
> fix expandable Read More 500 error

- cms/templates/home_page.html
- frontend/public/scss/home-page/home-page-hero.scss
- frontend/public/scss/variables.scss
Closes https://github.com/mitodl/hq/issues/2304
This takes the Figma definition for the extra gradient to go from image to a dark blue on the outside of 1440px width. 
Load it up, run it, compare it to the [Figma](https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?node-id=1592%3A7054&mode=dev).  Try various sizes, but do note there's an issue with the video component styling that will be addressed in a separate PR.
> Home Page New Hero Background Fix

- main/urls.py
https://github.com/mitodl/mitxonline/issues/1870
Removes a duplicate URL path.
- http://mitxonline.odl.local:8013/catalog/ should still be accessible when `ENABLE_NEW_DESIGN = True`
- http://mitxonline.odl.local:8013/catalog/ should display a 404 page when `ENABLE_NEW_DESIGN = False`
> 1870: Remove duplicate catalog URL path

- cms/templates/product_page.html
- cms/templates/videojs_tag.html
- cms/templatetags/videojs.py
- frontend/public/scss/product-page/product-details.scss
Closes #1880
The relevant VideoJS CSS was located in a set of CSS selectors that meant it wouldn't be applied on the new design product page, which broke the player. This moves those styles where they will apply, and makes some tweaks to the styles to make videos fit better in the sidebar.
This also adds a new `videojs` tag that can be used to drop our standard VideoJS tag, and will allow us to make global changes to this (as we'll be able to update the tag template in one place). 
YouTube embed:
HLS embed:
Set up a course with a video URL. Viewing the course should give you a play button and video controls (in some fashion - embedded ones for HLS video, YouTube ones for a YouTube video).
> Updating video player CSS to work better in the new design

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
- frontend/public/src/lib/courseApi.js
Fix https://github.com/mitodl/hq/issues/2319
Don't show green label "Course Passed" if there is no certificate.
This green label "Course Passed" shouldn't show, if there is no certificate.
create a passing grade for user and a revoked coure run certificate. Check the dashboard course card enrollment info. It should not show the certificate and not show the "Course Passed" tag.
> Course passed if has course run certificate

- frontend/public/scss/footer.scss
close https://github.com/mitodl/hq/issues/2251
adjusts layout for **mobile landscape** screen per Bilal's feedback. All other views should not be affected
After
Before
Compare this branch with https://rc.mitxonline.mit.edu/ for mobile landscape screen
> footer css updates for mobile landscape screen

- frontend/public/scss/home-page/home-page-hero.scss
Fixes https://github.com/mitodl/mitxonline/issues/1896
Remove the z-index which is no longer necessary
Open the home page, click the drop down on the top right while logged in - you should see it, it should not be covered by the hero.
> Hero sits over dropdown because of carousel z index change

- frontend/public/src/containers/ProductDetailEnrollApp.js
The course page was removed from the courserun API response in [an earlier PR](https://github.com/mitodl/mitxonline/pull/1872), but the More Dates selector depended on it being there to determine which course run to show you. This PR changes that logic to something more simple - either you've selected a course run or you haven't. 
Fixes mitol/hq#2396 partially
If a course run has been selected, use that instead of the default (which is just the first courserun that appears in the list when we go to fetch them). 
Set up a course with multiple concurrent runs. (For my testing, I made two with run tags ending in A and B so it'd be obvious which is which.) Then, load the course page. You should see the More Dates selector. 
Clicking Enroll Now without choosing a course in the More Dates …
> Updates the code behind the More Dates selector to work without the course page

- frontend/public/src/containers/ProductDetailEnrollApp.js
- frontend/public/src/lib/util.js
Updates https://github.com/mitodl/hq/issues/2353
Updates https://github.com/mitodl/hq/issues/2388
This takes the posthog setup into one place, out of the util function, and removes most of the config options.  I also turned on posthog debug when environment is dev to assist in debugging.
Load pages - the flags should still work and you should see the ph cookie is not very small (126 bytes give or take, instead of over 1500 as on RC presently). when using locally, should see posthog request info in console. You should also see user data for posthog in the session storage. There should not be events generated for everything you do on the page any more in the posthog application.
Will have a follow up PR to swap to the React SDK instead. This one will help alleviate short term 400 issues.
> Swap posthog to use js sdk with minimal settings

- frontend/public/src/components/CourseProductDetailEnroll.js
https://github.com/mitodl/mitxonline/pull/1900
https://github.com/mitodl/mitxonline/pull/1900 fixed an issue with the course selector in the More Dates section, which then didn't get migrated into the Program Page code (which split out the upsell stuff into separate components for course and program pages). This re-adds it to the new course page component.
See testing parameters in https://github.com/mitodl/mitxonline/pull/1900 - it should be exactly the same.
> Re-add the fix from PR 1900 to the reworked product page components

- cms/templatetags/course_list.py
Closes mitodl/hq#2427
After deploying the program page code to RC, I was getting 500 errors on some programs - turns out there were courses missing CMS pages in some of the programs. This fixes the `course_list` template tag to handle that case better by not listing the course (since you can't enroll in it if there's no CMS page anyway). 
Create a program with some (>2) courses in it, and set up CMS pages for the program and two of the courses. Leave one course page unpublished. 
Navigate to the program page. You should see the page, and you should only see a course page for the course with a published CMS page.
Publish the remaining course page. The course should show up in the program. 
Optionally create and publish a course page for any other courses in the program. They should appear …
> Skip courses if they don't have a published CMS page

- cms/api_test.py
- cms/models.py
- main/templates/partials/featured_product_card.html
Fixes https://github.com/mitodl/hq/issues/2375
adds self paced on the relevant run to the context & logic to make it visible on the page.
Having a CMS page for a self paced and a non self paced course. Non self paced should show the relevant start date (next in the future, or recently passed with enrollment still open), self paced should show "start anytime".
> Self paced dates -> start any time

- cms/templates/product_page.html
- frontend/public/src/components/CourseInfoBox.js
Fixes https://github.com/mitodl/hq/issues/2344
Adds a link in for the certificate track on the right hand side.
Adds prerequisites to the nav bar and about sections, if it is present.
1. Have a course with prerequisites (and preferably other data as well) set
2. Go to that course, you should see Prerequisites in the gray nav bar below the title. This section should display with whatever information you entered.
3. Click the link on the right hand side of the page "What's the certificate track?" and make sure it goes to the zendesk article Peter linked in the issue.
4. On another course, without prerequisites set (or the same, but without prerequisites), make sure the section & nav are gone.
The program links are working for me - I will say, since that's part of the issue, if the reviewer …
> Add FAQ cert link and prerequisites to product_page.html

- courses/views/v1/__init__.py
Fixes https://github.com/mitodl/hq/issues/2411
Because the filter for enrollable courses is built on course run, if there are more than one enrollable course run, the course would show multiple times on the catalog page.  To fix this, I added distinct to the course queryset to make sure we're only choosing each course once.
Prior to pulling branch:
1. Create a course or courses with multiple course runs that are enrollable (enroll dates overlap today's date)
2. Go to /catalog and you should see this course more than once - more precisely, you should see it as many times as it has course runs that are open to enroll today
3. You can ALSO see this at /api/courses/?page=1&live=true&page__live=true&courserun_is_enrollable=true if you prefer data over gui
Pull the branch
Once the branch is …
> Fix Duplicate Courses on Catalog Page

- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
Fix https://github.com/mitodl/mitxonline/issues/1919
Don't switch departments when courses or programs tab is selected.
Go to catalog page. Select a department, switch to the programs tab. The same department should be selected.
> Course Calatog: Stay on selected department

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- main/templates/base.html
Fixes https://github.com/mitodl/hq/issues/2472
This PR conditionally displays "Course content available anytime", the callout, and "No certificate available" on courses which fall under "isArchived" which is:
- end date is earlier than now AND
- enrollment_end is empty or later than now
To test this properly, before pulling, set up 2 courses (amongst others) with course runs that match the following:
For both: start_date and _end date are both in the past, enrollment start is in the past.
1. enrollment_end is in the future
2. enrollment_end is empty
Open these prior and should see the old behavior (look like other pages)
pull the PR
reload page
Should see the new callout & words.
> Update course info bar to respond to archived courses

- cms/models.py
- cms/templates/product_page.html
- courses/api.py
- frontend/public/src/components/CourseProductDetailEnroll.js
_Removed the Needs Review from this since Program Page will require this to be refactored to work._
Fixes mitodl/hq#2396
Fixes #1793 
This incorporates a few changes:
- In the CoursePage model, the relevant runs should now filter out runs with enrollment end dates in the past, so past course runs should not display
- In the More Dates selector, items that were listed as inactive were actually selectable - this fixes that, only `button` elements are handled now
- The ProductDetailEnrollApp component should now favor the first apparent unenrolled courserun rather than just grabbing the first if one isn't explicitly selected. 
- The relevant course runs queryset function now only includes live courses
Note that the course runs API considers whether or not the enrollment was successful in edX …
> Assorted fixes for More Dates selector in existing design

- frontend/public/src/components/CourseInfoBox.js
Fixes https://github.com/mitodl/hq/issues/2472
Updates the course about page to have certificate not shown when archived course.
Using an archived course, ensure that the certificate option is no longer shown. This should read "No certificate available" for courses that match `isArchived()`
This should align with the figma linked in Additional Context
Ensure that other courses still display certificate information as before.
[Figma](https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?type=design&node-id=1592-6996&mode=dev)
> Update the Certificate field for archived courses

- cms/templates/home_page.html
- frontend/public/package.json
- frontend/public/scss/home-page/featured-product-cards.scss
- frontend/public/scss/layout.scss
- frontend/public/src/entry/django.js
- main/templates/partials/featured_product_card.html
- yarn.lock
Fixes https://github.com/mitodl/hq/issues/2456
Fixes https://github.com/mitodl/hq/issues/2445
Fixes https://github.com/mitodl/hq/issues/2290
I swapped over to use [Slick Carousel](https://github.com/kenwheeler/slick/). This carousel has some built in responsiveness, allows for teh advancement of however many slides we choose, and has accessibility bits available.
This PR:
- Makes the carousel accessible (Slick Carousel has this built in, I also swapped the arrows to buttons instead of links). Hidden items are hidden, things are swipable as well as clickable. Items are now read correctly.
- Animation responsiveness is no longer a mess - Slick Carousel has this as well.
- Font descenders are no longer cut off on the bottom row.
Load up the carousel with things set on it (make sure you set …
> Carousel Fixes

- cms/models.py
- cms/templates/product_page.html
- courses/api.py
- frontend/public/src/components/CourseProductDetailEnroll.js
Reverts mitodl/mitxonline#1903
mitodl/hq#2573
Reverts most of #1903. Specficially:
* In the CoursePage model, the relevant runs should now filter out runs with enrollment end dates in the past, so past course runs should not display
* The ProductDetailEnrollApp component should now favor the first apparent unenrolled courserun rather than just grabbing the first if one isn't explicitly selected.
* The relevant course runs queryset function now only includes live courses
(I kept the code to stop you from being able to choose a date that wasn't enrollable.) 
Testing should be pretty close to the scenario described in mitodl/hq#2573
> Revert "Assorted fixes for More Dates selector in existing design"

- courses/serializers.py
- courses/serializers_test.py
https://github.com/mitodl/hq/issues/2303
Updates `LearnerRecordSerializer` to only return grades if one of these conditions are met:
- A certificate is generated (this has already covered in existing code)
- The course's certificate available date has passed
- If there is no course certificate available date, then the course has ended
- Setup a program and related courses
- Setup a run 
- start date is in the pass and end date is in the future
- certificate available date in the future
- Enroll in program
- Create passing grade for run created above
- Go to your program record, make sure grade is not displayed for that run
- Test any condition mentioned in the description, grade should be displayed for that run
> don't leak grades in program record before course completed

- frontend/public/src/components/CourseLoader.js
- frontend/public/src/components/SkeletonLoader.js
- frontend/public/src/containers/pages/CatalogPage.js
- package.json
- yarn.lock
Fix https://github.com/mitodl/hq/issues/2328
Installs [react-content-loader](https://github.com/danilowoz/react-content-loader)
adds content loader for courses and programs in the catalog page
Go to catalog page while the courses are loading it should show the loader.
> Catalog Page: Add content loader 

- cms/templates/product_page.html
https://github.com/mitodl/hq/issues/2601
Address accessibility issues on instructor section of course about page (new design)
- make instructor name keyboard focusable
- return focus on instructor name when modal closes
- Setup course/program about page for new design
- Add Faulty Members on course/program about page from CMS
- Go to course/program page
- Use screen reader to tab through the above page, you should now be able to tab to each instructor and open modal. 
- When instructor modal closes, the screen reader should now focus on instructor name.
> Course About Redesign - Accessibility issues on instructor bio

- frontend/public/src/components/ProgramInfoBox.js
Fixes https://github.com/mitodl/hq/issues/2552
Removes the start date from the ProgramInfoBox
Have a program setup in your mitxonline instance. Go to the about page for that program. You should NOT see a start date.
> Remove start date from ProgramInfoBox.js

- frontend/public/scss/product-faculty-members.scss
Fix https://github.com/mitodl/hq/issues/2551
Fix overflow on faculty info boxes for different browser width.
> Product Page: Fix overflow on faculty info boxes

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll.js
Fix https://github.com/mitodl/hq/issues/2621
Updates the More Dates section of the course box.
1. Show enrollable runs that are already enrolled
2. Don't show "first unexpired run" that is already listed after the start-date-icon. This run can be enrolled through the big "Enroll Now" button.
3. Fix the regression with the "enroll now" button not switching to enrolled once the user enrolled in the "first unexpired run"
> Course Page: More enrollment dates updates

- cms/templatetags/expand.py
- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/containers/ProductDetailEnrollApp.js
Fix https://github.com/mitodl/hq/issues/2595
Update the Show more link to toggle text and appear at the bottom of the about text when expended.
> Product Page: about section Show More toggle updates

- courses/api.py
Fix https://github.com/mitodl/mitxonline/issues/1934
When enrolling user in a course, enroll them also in associated LIVE programs only.
Enroll you user in a course run that is a requirement in a program. If the program is not "live" the should be no program enrollment.
If you set  `program.live = True` then when you enroll in a course a program enrollment should be created.
> Filter out not live programs

- frontend/public/scss/catalog.scss
- frontend/public/scss/top-app-bar.scss
- frontend/public/src/components/UserMenu.js
- frontend/public/src/containers/pages/CatalogPage.js
Fix https://github.com/mitodl/hq/issues/2532
Fix https://github.com/mitodl/hq/issues/2508
Changes in this PR should only effect mobile view.
1. the overlay department menu should close on selection
2. the selected department is displayed un the blue header
3. minor centering and padding adjustments
> Catalog Page: Mobile view changes

- frontend/public/scss/product-page/product-details.scss
- frontend/public/scss/top-app-bar.scss
- frontend/public/src/components/CourseInfoBox.js
- main/templates/base.html
Fix https://github.com/mitodl/hq/issues/2618
Fix https://github.com/mitodl/hq/issues/2647
Following the designs here https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?type=design&node-id=0%3A1&mode=dev.
Updated the font family for new-design styles.
Before:
After:
> Course About Page: update font and styles

- courses/conftest.py
- courses/views/v1/__init__.py
- courses/views_test.py
- fixtures/common.py
- main/test_utils.py
- poetry.lock
- pyproject.toml
Closes https://github.com/mitodl/hq/issues/2795
Adds in:
- upper limit query counting, based on current, bad state
- nplus one fixture (auto use)
- utility to look for duplicate queries
- more robust/true to "life" fixture for API data 
Pull the branch and run tests via pytest. You can run with --v to see more output (including information about duplicated queries.
One helpful bit might be my math on the number of queries is a little fuzzy as there's a weird edge case. I'm hoping this is solved once we go in and fix these, but calling this out.
checklist, per issue:
- make sure we're looking for nplusone situations
- make sure there are test assertions around query count with baselines based on current state
- Ensure tests are run against sufficiently sized datasets
> Course API test updates

- cms/templates/product_page.html
- frontend/public/scss/product-page/product-details.scss
Fix https://github.com/mitodl/hq/issues/2566
Add mobile design for instructor bio modal on the course about page.
For testing take a look at the design: https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?type=design&node-id=1926%3A2877&mode=dev
> Instructor popup modal mobile view

- cms/serializers.py
- cms/serializers_test.py
- courses/models.py
Closes mitodl/hq#2391
Updates the course page serializer to include related programs in its search for a financial assistance form URL. 
Create two programs. One should have a full financial assistance buildout (published form, tiers, etc.); one should not. The two programs should have a RelatedProgram record and should have independent courses with products.
Attempt to view a course in the program that does not have financial assistance. You should see links to the other program's financial assistance forms, and you should be able to apply for and be approved for financial assistance as per usual. 
Attempt to purchase the verified track for a non-FA program's course after approving your financial aid request. You should get the personalized pricing for the course. (This has not changed - …
> Updated get_financial_assistance_form_url to also consider related programs

- frontend/public/scss/product-faculty-members.scss
- frontend/public/scss/product-page/product-details.scss
Fix https://github.com/mitodl/hq/issues/2654
Implement a new design for the instructor bio cards on the course about page.
Make sure you have created few instructors for a course in the cms. Go to the course about page and make sure that they follow the design in the issue.
> New design for the instructor bio cards on the course about page

- cms/templates/product_page.html
- frontend/public/scss/product-page/product-details.scss
Fix https://github.com/mitodl/hq/issues/2570
Adds padding for before the Course Info Box.
Aligns the course info box to be in the middle for tablet and mobile view.
> Course About Page: tablet and mobile view adjustments

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseProductDetailEnroll.js
mitodl/hq#2616
In the mobile version of the upsell modal:
- The certificate upsell list should fall into a single column
- The certificate pricing and Enroll and Pay buttons should also become a single column
- The Need Financial Assistance and free options should appear stacked and centered
Regular kind:
Mobile:
Grab a course with multiple course runs and a verified track and open the upsell modal, then switch your browser into responsive mode. The styling should work as expected. (There are no functional changes here but all the functionality should work as expected.)
> Fixing the mobile styling on the enrollment modal

- frontend/public/scss/top-app-bar.scss
- frontend/public/src/components/AnonymousMenu.js
- frontend/public/src/components/TopBar.js
- frontend/public/src/components/UserMenu.js
- frontend/public/src/components/UserMenu_test.js
Partially completes https://github.com/mitodl/hq/issues/2559
1. Change the anonymous header to use hamburger menu
2. Add Catalog link to the anonymous desktop header
3. Adds Catalog link to the dropdown navigation
Checkout the header in desktop, mobile, anonymous, authenticated views. Make sure the navigation works.
Mobile View:
Desktop:
> Update header design and navigation

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/factories/course.js
https://github.com/mitodl/hq/issues/2902
If you were logged in but not enrolled in a course, the More Dates link would work but not show anything. This fixes that - we were looking for you to be an anonymous user to display the link. 
Log in and view a course with multiple course runs that you're not enrolled in. Clicking More Dates should show you the additional dates.
> Fixing date to display if you're logged in

- courses/urls/__init__.py
fixes https://github.com/mitodl/hq/issues/2933
Changes the URLs from re_path to path
be enrolled in a local program, go to dashboard and click to go into the record. Record should load and you should be able to enable sharing (if everything else is correctly set up)
I broke this during the API refactor.  Here is urls.py prior to that refactor: https://github.com/mitodl/mitxonline/blob/709b0e3a8d7c5dedb674009314ee4cad800154e9/courses/urls.py
> Fix Program Share URLs

- cms/serializers.py
- courses/serializers/v2/courses.py
- courses/urls/v2/urls.py
- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
- flexiblepricing/api.py
mitodl/hq#2798
Adds a refactored courses API to the app. This API:
* Allows for filtering on specific course IDs (numeric IDs)
* By default excludes the approved financial assistance check
* Uses a cut down version of the CoursePageSerializer (named aptly `BaseCoursePageSerializer`)
With these changes, the `/api/v2/courses` page runs ~600 queries (using the normal test case) versus v1's ~2000 queries. It also contains less data. 
The v2 API is intended to be used by the catalog; the course product pages should continue to use the v1 API so that financial assistance, instructors, and pricing data is available.
Compare loading a course (or courses) in the v1 api versus the v2 one: `/api/courses` vs `/api/v2/courses` optionally with a PK at the end. They should be largely the same but the v2 …
> Adds v2 of the courses API for the program page

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
mitodl/hq#2912
After some investigation into the ticket noted, the archived message was in fact working properly - this just adds an automated test for that case. 
This also adds a few classes to the parts of the course infobox so it's easier to write tests for them.
Run the automated test, which should pass.
You should additionally see new class names in the course infobox for the various sections of the box:
```
course-archived-message (if visible)
course-timing-message
course-effort-message
course-pricing-message
course-certificate-message
```
The rules for this are:
A course is archived (and displays the yellow archived callout) if:
- The `enrollment_end` date is unset, or set in the future
- The `end_date` is set
> Adding a test for archived courses

- cms/serializers.py
- courses/views/v2/__init__.py
- frontend/public/src/containers/pages/CatalogPage_test.js
- frontend/public/src/lib/queries/programs.js
closes https://github.com/mitodl/hq/issues/2907
updates programs to have a  page__live query
Have a live program with no live associated page, should not see it on catalog page.
> Add page__live filter to programs API and update url in catalog page query

- courses/serializers/v1/courses.py
- courses/views/v1/views_test.py
Closes mitodl/hq#2916
Updates the courses API to filter programs by Live - if the program isn't live, then the course's programs list shouldn't have it. 
Also added a test for the course API by readable id - there didn't seem to be one, and the new tests also checks for program data to be included (or not) appropriately. 
Load a course page for a course that's in a program. You should see the program in the list in the course infobox. 
Turn off the program by going to Django Admin and unchecking the Live box, then reload the course page. You should no longer see the program in the list.
> Updated v1 course API to only pull live programs; added tests

- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
- frontend/public/src/lib/queries/catalogCourses.js
closes https://github.com/mitodl/hq/issues/2798
Since we don't want to change other pages, I've added this to a new query under catalogCourses (open to changing this name, but it made the most sense to me).
Load up and load /catalog... careful, you might experience whiplash it's so fast now (kidding... but it's a major improvement.)
> Change Catalog to use v2 API endpoint for courses

- frontend/public/src/components/AnonymousMenu.js
- frontend/public/src/components/UserMenu.js
Related to https://github.com/mitodl/mitxonline/pull/1969
Fixes the links in the header in Desktop view not to disappear after a click.
Use the navigation in the header in anonymous and authenticated view. Nothing should jump or disappear in the header when you click any of the buttons.
> Header nav links fixes

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
- frontend/public/src/lib/util.js
- frontend/public/src/lib/util_test.js
Closes mitodl/hq#2984
Ferdi noticed that the start date on a course in the future displayed as "Started: <future date>" in the course info box. This fixes that display - it should display "Start Date" now - and refactors out the date display code from the CatalogPage so that it is reusable elsewhere (but still takes into account the cases that the CourseInfoBox has, like archived courses and the More Dates display). 
In the Course Info Box for a course with a valid future start date that isn't self-paced, it should display "Start Date:" and then the start date of the course.
In the Course Info Box for a course with a valid past start date that isn't self-paced, it should display "Start Anytime" and then the start date of the course.
In the Course Info Box for …
> Fixes start date formatting in CourseInfoBox, refactors date display for reuse

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/containers/ProductDetailEnrollApp.js
Fix https://github.com/mitodl/hq/issues/2596
Sets display none for hidden text on the page
Use voiceover to make sure the it doesn't read text that is not visible on the page.
> Product Page: Display none for hidden text

- cms/templates/course_list_card.html
- frontend/public/scss/product-page/program-courses.scss
Fix https://github.com/mitodl/hq/issues/2644
Change the start time label to div instead of h4.
Make sure that the design looks the same as before and nothing is broken.
> Headings for required courses start date

- cms/serializers.py
- cms/serializers_test.py
Closes mitodl/hq#2994
If a program does not have its own financial assistance form, but is related to a program that does have one, the serializer looks for the appropriate financial assistance form URL for the related program. This works, but it was also putting the program it was asked for (that doesn't have a FA form)'s URL slug in the URL, which caused a broken link. This instead gets the program page that the financial assistance form belongs to and constructs the URL with that instead. 
Create two programs in the system, including CMS pages. Create a financial assistance form for just one of those programs. Then, add a RelatedProgram record that ties the two programs together.
View the CMS page for the program with the FA form. The link to financial assistance should be visible and …
> Fixes financial assistance form URL for programs that don't have their own

- cms/serializers.py
- cms/serializers_test.py
- cms/templates/product_page.html
Closes mitodl/hq#2752
This does two things:
1. There was no way to open the instructor cards by keyboard. You could tab down to an instructor name but you could not hit Enter to open the modal. Further, when the modal was open, you could not close it via the Escape key. 
2. In testing, I found an issue where if the program doesn't have a financial assistance form, and it has a related program that _also_ doesn't have a FA form, the serializer will fail. 
Instructor cards: Open a product page and use the tab key to select the instructor name. Hit Enter, and the modal should open. Hit Escape and the modal should close. 
Program FA: Create two programs that are related to each other but do not create financial assistance forms for either. The program API should continue to work.
> Updates the onclick for the instructor name to activate on keyup, fixes an issue with financial assistance page serialization

- cms/templates/product_page.html
- frontend/public/scss/product-page/product-details.scss
Fix https://github.com/mitodl/hq/issues/2567
Reoder product info for mobile view
Go to product page make sure that Desktop and tablet view look the same as before. Go to mobile view and make sure that the Product Info Box goes right after product description.
> Reoder product info for mobile view

- courses/factories.py
- courses/serializers/v2/departments.py
- courses/serializers/v2/departments_test.py
- courses/urls/v2/urls.py
- courses/views/test_utils.py
- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
Updates
https://github.com/mitodl/hq/issues/2992
https://github.com/mitodl/hq/issues/2911
https://github.com/mitodl/hq/issues/2910
https://github.com/mitodl/hq/issues/2823
This update to teh Departments endpoint:
- Makes the course and department counts accurate
- Moves the logic to the serializer rather than the view
- adds serializer tests
- adds view tests
Run tests
Add departments to your local. The count in the catalog page should match the API output.
Also, double check my "math" on that logic.
> Departments v2 endpoint - now with more course and program counts

- frontend/public/scss/product-page/program-courses.scss
- frontend/public/scss/variables.scss
Closes mitodl/hq#2986
The program course cards should default to a "dimmed" mode, and then undim on hover. This adds the CSS to support that. See the [relevant Figma link](https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?page-id=0%3A1&type=design&node-id=1373-5892&viewport=-17610%2C515%2C0.97&t=8L3q92hSlGEYTV7H-1&scaling=min-zoom&mode=design). 
https://github.com/mitodl/mitxonline/assets/945611/96cf69ae-6bb1-49ed-957f-25481cb3b098
Load the program page for a program with courses. The course cards should be dimmed, and hovering over them should bring the opacity of the image and the text to 1.
We were using the red button background (ala the Enroll Now button) for the course title text - in Figma it isn't like this.
> Updates CSS to add hover states on the program course cards

- frontend/public/src/containers/pages/CatalogPage.js
Fix https://github.com/mitodl/hq/issues/2494
Adds `role="status" aria-atomic="true"` to the course count div.
Use voiceover to navigate the page click the department filters, when the course count updates it should announce the update.
> Announce course count change

- frontend/public/scss/catalog.scss
- frontend/public/src/containers/pages/CatalogPage.js
Fix https://github.com/mitodl/hq/issues/2491
1. Update main header to h1
2. The items count should be h2
3. departments list should be wrapped in nav element
4. the courses grid should be a list
Everything should look the same as before. Use voice over to navigate the page by heading, navigate the page by landmark.
> Catalog Page: updating header and list elements

- frontend/public/scss/home-page/home-page-contact-row.scss
Fix https://github.com/mitodl/hq/issues/2486
Make Email input label visible to screen reader
Use voiceover to to read the Signup section at the bottom of the home page. It should read the "Email*" label.
> Accessibility: Make label visible to screen reader

- frontend/public/scss/home-page/featured-product-cards.scss
- frontend/public/src/entry/django.js
- main/templates/partials/featured_product_card.html
Fix https://github.com/mitodl/hq/issues/2453
Removes the duplicate selection of the featured products in the carousel.
Groups the title and the start time into a header for better readability.
Use screen reader to read the featured products in the carousel. 
Tab through the products in the carousel each tab will move the selection to the next product.
> Accessibility: tabbing through featured products improvement

- cms/templates/product_page.html
- frontend/public/src/containers/ProductDetailEnrollApp.js
Closes mitodl/hq#3077
- Moves the instructor modal code into the ProductDetailEnrollApp (eliminating inline JS calls)
- Adds taborder to the instructor image so it can be focused upon
- When the modal is popped, set focus to the close button
- When the modal closes, set focus to the instructor's featured image
This sets the focus to the featured image because otherwise there ends up being a stray keyup that re-toggles the modal to open again if focus is set to the h3.
Navigate to a course page that has instructors on it. You should be able to tab down to the instructor name, hit Enter, and pop the modal. The focus should be on the Close button so hitting Enter again should close, or you can tab around. The modal should close but not reopen.
Similarly, navigation should work as expected …
> Fixes the keyboard trap issue with instructor modals

- frontend/public/scss/layout.scss
- frontend/public/src/containers/pages/CatalogPage.js
Fix https://github.com/mitodl/hq/issues/2531
Make department sidebar stay on the page when scrolling down on mobile
Go to Catalog on mobile, scroll down to the bottom of the page, click the department filter button, a nav menu will open up. You should be able to see the list of the departments.
> Make department sidebar sticky on mobile

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
Partial fix for mitodl/hq#3109
If there are two active course runs, both with products but one of which is ineligible for upgrade, the upsell dialog will allow you to upgrade that particular course run where you shouldn't be able to. This adds some filtering to keep that from happening. 
Set up two course runs that overlap. Both should have products and allow for upgrading, but the one that starts the latest should have an upgrade deadline in the past. (So, if you have ones that has both start dates as 2023-11-01 and one that has both start dates as 2023-11-15, the 2023-11-15 one should be the one with the upgrade deadline set in the past.) 
- On main, you should be able to upgrade, and you should be able to select the second course run and upgrade it.
- In this branch, you should be able …
> Filter out courseruns that can't be upgraded when displaying the upsell dialog

- frontend/public/src/components/ProgramProductDetailEnroll.js
Fix https://github.com/mitodl/hq/issues/2651
Go to program page and open the enrollment dialog.
The button area is not added here because it is dependent on the course run selected, whether the course run has price info, finaid info etc...
> Updating the program enrollment  dialog text

- cms/models.py
- cms/templates/certificate_page.html
Fix https://github.com/mitodl/hq/issues/2696
Fix https://github.com/mitodl/mitxonline/issues/2003
Updates the program and course certificate to use the title of the product.
Create a course certificate, create a course certificate page in wagtail. 
View the certificate. Make sure it looks as expected.
Repeat the same with a program certificate.
> Certificates use product title

- cms/templates/product_page.html
- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/entry/django.js
- main/templates/base.html
Fix https://github.com/mitodl/hq/issues/2973
Fix https://github.com/mitodl/hq/issues/2769
Fix https://github.com/mitodl/hq/issues/2838
Updates the style for  the navbar on product page:
1. The links hover over the whole tab rather than just the words.
2. Adjusted some of styles to match the figma design
3. Active tab is changes color
4. Navbar is fixed at top of page
Look at the design in the issue. Go to product page and hover over the navbar. It should be visible that the menu is clickable.
When you select a tab it should scroll to the location on the page. The active tab changes based on the position of the scroll.
> add styles to the navbar on product page

- cms/templates/product_page.html
- frontend/public/src/components/ProgramProductDetailEnroll.js
Fix https://github.com/mitodl/hq/issues/2623
This PR fixes two unrelated things:
1. Switch the name and the course info in the program enrollment dialog
2. Fix a styling bug for the "required program courses" section (this small bug doesn't have an issue)
1.
2.
> Program enrollment: choose courses

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
Closes mitodl/hq#3295
If you have an existing enrollment in a course that is upgradeable, the enroll now button component will try to funnel you into upgrading that enrollment. However, it did this funneling even if the run's deadline had passed. This fixes that by adding some checks to make sure the course run is actually eligible for upgrade. 
Set up two course runs (and related course, if necessary). One should be fully in the past and one should be eligible for enrollment and upgrade now. The course runs must have products and the course must have a CMS page. Create an audit enrollment in the past course run, then load the course page. You should see the normal messaging - current upgrade deadline and price, Enroll Now button - and clicking Enroll Now should prompt you to upgrade into …
> Check to make sure the end date and upgrade deadline haven't passed before grabbing your audit enrollment

- frontend/public/src/components/CourseProductDetailEnroll.js
mitodl/hq#3295
If the app has to resolve which course run it should be working with, sometimes it will fail back to just the first one in the list that comes back from the API. This can result in a course run that's not enrollable being chosen. This PR adds a check to favor the first enrollable course run over just the first one in the list, and then fall back to the first one in the list if there's not one that's eligible. 
I tested by copying the courserun info for `course-v1:MITxT+14.100x+3T2023` and `1T2024` from production, making sure both had products, and then forcing an audit enrollment in 3T2023. Once done, you should be able to load the course page for 14.100x, and clicking Enroll Now should offer to upgrade you to 1T2024. Clicking upgrade _or_ hitting Enroll for Free should …
> When resolving the current run, make sure it's also enrollable

- frontend/public/src/components/ProgramProductDetailEnroll.js
https://github.com/mitodl/hq/issues/2623#issuecomment-1875972496
display the course number instead of course ID on program enroll modal
Go to program enrollment page (It requires setting up courses, programs locally)
Click on "Enroll now"
A upgrade enrollment dialog should popup, it should list all the courses in that program.
Note that the display name should be course title + course number
The screen reader should read the course title and course number as well
> display course number on program enroll modal

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/ProgramProductDetailEnroll.js
https://github.com/mitodl/hq/issues/714
Adding `?next=` to course and program enrollment pages to remember where user was going after login 
As anonymous users, go to course and program page
Click on enroll now
You are redirected to login page with `?next=` on url
Log in with your credential
You should be taken to the course or program page where you were before login
> add next parameter to course and program enrollment pages for unauthenticated users

- frontend/public/src/components/UserMenu.js
Fix https://github.com/mitodl/hq/issues/2988
Removes role="menu" from user menu.
using a screen reader navigate to the user menu dropdown, you should be able to toggle the user dropdown and have the reader announce it to you.
> Remove role menu

- frontend/public/scss/product-page/product-details.scss
Closes https://github.com/mitodl/hq/issues/2750
Adds visual focus to two elements mentioned above - the enroll now button and enroll free "button" (that looks like a link)
Make sure your course has pricing set so it launches the modal. You should be able to tab through and it should highlight the various elements. These should be:
- The X (previously worked and should still)
- The Enroll Now button (did not have a border prior)
- The Financial aid link (previously worked and should still - you will have to add a form to make this work OR - as I did - make a small change to the logic in the component to display it regardless)
- The No thanks, I'll take it free "button"/link at the end (did not have a border prior)
> Add css in for visual focus on modal buttons

- frontend/public/.eslintrc
- frontend/public/src/containers/pages/login/LoginEmailPage.js
- frontend/public/src/containers/pages/login/LoginPasswordPage.js
- frontend/public/src/containers/pages/profile/EditProfilePage.js
- frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
- frontend/public/src/containers/pages/register/RegisterConfirmPage.js
- frontend/public/src/containers/pages/register/RegisterDetailsPage.js
- frontend/public/src/containers/pages/register/RegisterEmailPage.js
- frontend/public/src/containers/pages/settings/EmailConfirmPage.js
- frontend/public/src/lib/queries/auth.js
> Fix flow errors in redux-query updates

- courses/management/commands/create_courseware.py
NA
When running the quickstart management command (main/management/commands/configure_instance.py) an error occurs when the quickstart command executes the create_courseware command (courses/management/commands/create_courseware.py).  The create_courseware command is executed without specifying a department argument.  The create_courseware throws an error when it checks the value of the local variable `add_depts` which, when no department argument is provided, is undefined.
This PR resolves the issue by checking whether `add_depts` is defined as a local variable.  `add_depts` is defined when the department argument is defined, otherwise the local variable is not defined.
The `add_depts` variable is checked when creating a program or course.
Run the configure_instance management command …
> create_courseware command no department defined error

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/ProgramInfoBox.js
Closes https://github.com/mitodl/hq/issues/2836
Adds in a link to the FAQ for self paced and instructor paced courses as well as a badge for instructor paced.
Have courses of the various formats, ensure the link shows as appropriate
Figma: https://www.figma.com/file/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?type=design&node-id=4092-3869&mode=design&t=ONalqUFtLjNoci7G-0
> Explain Course Formats

- cms/templatetags/expand.py
Fix https://github.com/mitodl/hq/issues/2596
Fixes two things:
- the hide class should be on the hidden element from the very begining
- the Show More link is now in between the visible text and the hidden text.
Use a screen reader to tab through a product page that has hidden "about" section text. Make sure the the links in the hidden text are not read by the reader.
Play with the Show More button and make sure that the hidden text appears after the button.
> Show More link on product about page accessibility

- frontend/public/src/components/NotificationContainer.js
- frontend/public/src/components/TopBar.js
https://github.com/mitodl/hq/issues/715
After paying for a course, a user is redirected to the user's Dashboard in MITx Online where they are presented with an alert indicating whether the payment process was successful or not.  For screen readers, the alert is rendered when the page is loaded which does not trigger the use of `role="alert` on the alert.  This PR adds a 3 second delay, after the page has loaded, before displaying the alert.  This delay means that the alert is rendered 3 seconds after the page has loaded and results in the alert being read by the screen reader in a fashion expected of `role="alert`.  
The functionality that`role="alert` provides to screen readers can also be observed when unenrolling from a course from the user dashboard.
1. Enroll and pay for a course …
> Delay alert when rendering the page in order to engage screen reader alert

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/lib/util.js
- frontend/public/src/lib/util_test.js
https://github.com/mitodl/hq/issues/3382
Updates the logic that controls which date is displayed first to users on the course about page.  The updated logic is described in the code and here: https://mitodl.slack.com/archives/C02649X2P1V/p1705690944470659?thread_ts=1705689453.418639&cid=C02649X2P1V 
Run through different course run start date configurations in order to trigger the following to be shown in the course about page start date field:
1. 'Starts: earliest course run start date'
2. 'Start Anytime'
3. 'Started: earliest course run start date'
> 3382: self paced courses with future start dates show start anytime

- frontend/public/src/containers/pages/records/LearnerRecordsPage.js
Fix https://github.com/mitodl/mitxonline/issues/2056
Fixes a bug when getting the program id.
Go to view your program record, click enable sharing, check that sharing request was called with the correct program id.
> Fix program id retrieval when sharing

- .github/workflows/docs.yml
- pants-plugins/mitol/docs/register.py
- pants.toml
n/a
For version 0.85.0, the production deploy got stuck because the Publish Documentation action failed. It looks like this was mostly due  to Pants being too old, so this bumps that to 2.17.1 and makes some minor changes to the `docs` plugin to make it work. 
Running `./pants docs ::` should work as expected.
The latest Pants is 2.18.2 but that didn't seem to work; [there's a warning here](https://github.com/mitodl/mitxonline/actions/runs/7641957862/job/20820461026#step:5:100) that is likely the issue. (We're not using SCIE pants here yet so moving to that is probably the right move but there's also [specifically an init-pants action](https://github.com/pantsbuild/actions/tree/main/init-pants) that we could also look at. Or, both, though bumping to 2.18.2 locally worked OK without also …
> Update Publish Documentation to newer versions of stuff so it runs

- courses/views/v2/views_test.py
- ecommerce/management/commands/create_product.py
Closes mitodl/hq#3463
`create_product` wasn't creating the initial version of the product it created - it just made the row in the `ecommerce_product` table, so trying to buy the resulting product would fail. This fixes that.
Run `create_product` - the new product it creates should have a version. (Easy way to check is just to grab the last row of the `reversion_version` table, or doing a `like` on `object_repr` in that table with the product name you created.) 
Checkout should work with the newly created product.
> Wrapping product creation in a create_version block so versions happen like they should

- courses/views/v2/views_test.py
- ecommerce/api.py
- ecommerce/views_test.py
n/a
I noticed when processing a bulk code creation form in the staff dashboard that codes that I'd requested be created as one-time discounts were being created as unlimited ones instead. As it turns out, the API call for this was not looking at the `POST`ed redemption type - it expected flags instead. This fixes the API to use _either_ the flags or the `redemption_type` kwarg (which is how it's sent via POST), so the redemption type is saved correctly. 
This also fixes the `test_get_courses` test - this had similar problems to `test_get_programs`, which was fixed in https://github.com/mitodl/mitxonline/pull/2073 , which was also rolled into that PR because the tests were failing. 
Create a set of discount codes from the staff dashboard that are of a redemption type that's not unlimited. …
> Fixes use of "redemption_type" when generating discount codes in bulk

- frontend/public/src/components/EnrolledItemCard.js
https://github.com/mitodl/mitxonline/issues/2075
Resolves in issue with using the keyboard to navigate and control the browser when the either the unenroll modal or email settings modal is open for a course enrollment.
You should have a course created and be enrolled.
1. Visit http://mitxonline.odl.local:8013/dashboard/.
2. Using only your keyboard, open the unenroll modal or email settings modal from the course enrollment card.
3. Verify that you can move focus to one of the buttons on the modal.  When you press enter, the focused button should perform it's expected action (close the modal, or submit).
> 2075: some dialogs email settings unenroll not keyboard navigable

- cms/models.py
- cms/templates/certificate_page.html
Fix https://github.com/mitodl/hq/issues/3370
Uses program type to specify the type of program for which a certificate is issued.
Something to think about: omitting the Series might be a better solution.
> Program certificate for different program types

- cms/templates/product_page.html
- frontend/public/scss/product-faculty-members.scss
- frontend/public/src/containers/ProductDetailEnrollApp.js
Fix https://github.com/mitodl/hq/issues/2989
Updates the instructor info section for accessibility. Everything should look as before.
You should be able to tab through the instructors names.
Navigate though the instructors with voiceOver and hear their names and titles.
> Accessibility: updating intructors info

- courses/admin.py
Related to https://github.com/mitodl/hq/issues/3580
adds search fields to CourseRunEnrollmentsAuditAdmin model and inlines to `CourseRunEnrollmentAdmin`
Make sure you have an enrollment instance. View it in the admin.
Then modify the course enrollment. A new audit model should get created. Try searching for the audit by username or email.
View the enrollment in the admin and see the audit instances related to the enrollment.
> Admin improvements to CourseRunEnrollmentAudit model

- cms/templates/course_list_card.html
- frontend/public/scss/product-page/program-courses.scss
https://github.com/mitodl/hq/issues/3361
Fixing the keyboard accessible issue for the course card on program page. 
Course card is now focusable
- You will need to setup courses and programs to test it
- Turn on voiceover and go to program page
- you should be able to tab to the course card and then use keyboard to open it
> fix course card not keyboard accessible issue

- courses/signals.py
- courses/signals_test.py
None
Updates the signal to check whether the program is live before generating the cert.
Take a look at the tests. 
Create a program with a required course. When you create a cert for that course, a program cert should get generated. 
If you set the program `live=False` and then create a course cert then no program cert should get generated.
> Create certs only for live programs

- courses/models.py
- courses/models_test.py
Fix https://github.com/mitodl/hq/issues/3622
On course certificate page show the end date equivalent to certificate creation date. The actual end date of the course run can be changed by the course team.
Create a course certificate. Go to view the certificate, the end date that is displayed should be the certificate creation date.
> Certificate Page: End date should be certificate creation date

- frontend/public/src/containers/pages/CatalogPage.js
fixes https://github.com/mitodl/hq/issues/3141
fixes https://github.com/mitodl/hq/issues/2992
fixes https://github.com/mitodl/hq/issues/2910
fixes https://github.com/mitodl/hq/issues/2909
Rather than just call the callback on the courses page, also calls it on the programs page as well.
Ensure that your database has at least 24+ relevant courses and programs for a department or two. I can provide a seed script if need be.
Load the catalog page. you should see number of courses and programs match the count at the top right.
This pulls back from the previous iteration of how I'd like to see this work - in the future we should rework the page to asynchronously seed the data to redux, but in the meantime, we're adding the callback to the bottom of programs which was not there previously.
> Change the callback to respond on programs page as well

- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
Fixes https://github.com/mitodl/hq/issues/3664
blocks https://github.com/mitodl/hq/issues/3663
Splits the render number of items function into two - one for courses and one for programs, and uses those in the desktop and mobile versions alike. This will also be used to determine how many loading divs are needed in a follow-on PR
Make sure the counts match on desktop and mobile and are correct for each item type and filter
> Fix mobile counts on catalog

- courses/serializers/v2/departments.py
- courses/serializers/v2/departments_test.py
- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
- main/test_utils.py
https://github.com/mitodl/hq/issues/3689
This PR modifies the `/api/v2/departments/` endpoint.  The endpoint previously provided the number of courses and programs associated with each department.  This PR removes the number of courses and programs, and instead provides a list of course and program IDs associated with each department.
**Example response**
```
{
"count": 2,
"next": null,
"previous": null,
"results": [
{
"id": 1,
"name": "dept1",
"course_ids": [
1,
2
],
"program_ids": []
},
{
"id": 2,
"name": "dept2",
"course_ids": [
1
],
"program_ids": [
1
]
}
]
}
```
The intention of this change is to better support filtering by department on the catalog page.  When a user filters by department on the catalog page, future development will utilize the course and program IDs provided by the …
> 3689: add department filter to the api endpoints for courses and programs

- courses/models.py
- courses/models_test.py
Fix https://github.com/mitodl/hq/issues/3622
The end date for the program on the certificate is the date the certificate was created.
To test this:
Create a program certificate, go to view the certificate, make sure the the end date on the certificate is showing the date it was created.
> Change program end date to certificate creation date

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/ProgramInfoBox.js
https://github.com/mitodl/hq/issues/2846
Changes course about page text to "Free to Learn" from "Free".
1. Using one of the courses created from the quickstart command (https://github.com/mitodl/mitxonline/blob/main/docs/source/configuration/quickstart.rst), view the associated course about page.
2. Verify that the course about page displays "Free to Learn".
> 2846 Course About: Replace Free with Free to Learn

- frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
- frontend/public/src/containers/pages/register/RegisterDetailsPage.js
- frontend/public/src/lib/queries/auth.js
https://github.com/mitodl/hq/issues/3360
This PR adds functionality to redirect users, who begin the registration process after attempting to enroll into a course, back to the course page after completing the registration process and additional-details page.
1. Load a course page while signed out of MITx Online.
2. Attempt to enroll into the course.  When you are redirected to the login page, click create an account.
3. Complete the registration process.  Verify that you are redirected back to the course page from step 1 after you submit the additional-details page.
4. Repeat steps 1-3 using a program and program page.
5. Ensure that you are redirected to the MITx Online homepage when you initiate the registration process from the main or catalog page.
> 3360: on account registration redirect new users to the page they started on

- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
- frontend/public/src/lib/queries/catalogCourses.js
- frontend/public/src/lib/queries/courses.js
- frontend/public/src/lib/queries/programs.js
Closes https://github.com/mitodl/hq/issues/3748
This PR adds in a `queryIDListString` to the `getNextCoursePage` function which takes in a string of course IDs and appends that as a parameter for` id=` to the end of the API url.  This is set when a department other than `ALL_DEPARTMENTS` is selected and `getNextCoursePage` is called.
This should make it so that on a page with less than the expected numebr of courses already loaded, the missing courses are loaded.
Load up with more than 12 courses. You should have a few in a couple of departments. This will allow you to see if, when you swap to one, it loads after swapping.
> Fetch by department when selected

- frontend/public/scss/product-details.scss
- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
Fix https://github.com/mitodl/hq/issues/3671 and partially https://github.com/mitodl/hq/issues/3109
Changes the enroll now button to open the dialog whenever there is more then one course run available for enrollment.
In the dialog the dropdown select course run shows all enrollable course runs. The runs that can't be upgraded have a label  `(no certificate available)`
There are few scenarios to test:
**1. All course runs for a given course don't have products but are enrollable**
**2. One course run has product and other not, but both are enrollable**
**3. two course runs both have products both are enrollable, but only one is upgradable** (meaning payment_deadline is in the future) - in this scenario the dialog looks the same as case 2.
**4. Has one enrollable course run with no …
> Upgrade dialog choose any course run

- frontend/public/src/components/forms/ChangeEmailForm.js
- frontend/public/src/components/forms/ChangePasswordForm.js
Fix https://github.com/mitodl/hq/issues/3830
add aria-label to the change password and email forms for voiceover to read.
Go account-settings and use voiceover to read the forms. Make use it is clear when one form ends and where the other starts.
> Distinguish change forms in account settings

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
none
This PR corrects some behaviors when `is_upgrade` and `products` could be true or false independent of each other.
fixes couple of things:
1. When the dialog is closed and opened again the current run is reset to null
2. if a run has a product but the upgrade deadline has passed it should say "certificate not available", and disable upgrade buttons accordingly
3. removes unnecessary code
to test this :
1. create a product for your run and set the upgrade deadline to the future.
2. create another run with a product and set upgrade deadline to the past
3. open the upgrade dialog as you select course the messaging should be consistent.
For example:
Here it says in the select element (no certificate available), but underneath shows the cost
> Upgrade enrollment dialog fixes

- courses/api.py
- courses/api_test.py
- courses/models.py
- courses/models_test.py
- sheets/deferrals_plugin.py
Fix https://github.com/mitodl/hq/issues/3781
Update the deferral procedure to downgrade enrollment to audit instead of unenrolling.
Testing:
Have a user with existing enrollment and fullfilled order for that run.
Create another run that is open for enrollment
Then run the management command:
`./manage.py defer_enrollment --user <username> --from-run <readable_id> --to-run <readable_id> -k`
Then check in the admin that the `from_run` enrollment is now set to audit, and the `to_run` is set to verified.
> Deferrals: set to audit instead of unenrolling

- courses/views/v1/__init__.py
Fix https://github.com/mitodl/hq/issues/3013
If you are already enrolled in this course run, and you go to product page and try to enroll again, it will not call `create_run_enrollments`
Enroll in a course run in certificate track. Make sure that PaidCourseRun is deleted.
Go to course product page try to enroll in the same run again. The enrollment post request should return duplicate error.
Repeat the same with the program product page. The program page enrolls you in the run it find convenient so make sure you are already enrolled for that run.
I am not sure if we should should restrict re-enrollment only if the user is enrolled in verified track, or any type.
> Enrollment request make sure not enrolled

- frontend/public/src/containers/pages/CatalogPage.js
Fixes https://github.com/mitodl/hq/issues/3950
Makes sure filteredPrograms is set earlier on the page to avoid the state where the programs don't show on load of /catalog/programs.
Added routing to update history on change to tab or department
load /catalog/programs and programs should show
load /catalog/programs/department-name and department name should show
When you navigate by clicking a tab or department, the URL should update
> Ensure filteredPrograms is set earlier and change the route when navigation changes.

- frontend/public/src/components/EnrolledCourseList.js
Fixes https://github.com/mitodl/hq/issues/3831
Changed the route from root to catalog
Log in as a user with no enrolled courses. The link in the middle of the page to "browse our courses" should link to the catalog, not the home page.
> Update Browse link on Dashboard

- frontend/public/package.json
- frontend/public/scss/cards.scss
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/forms/AddlProfileFieldsForm.js
- frontend/public/src/components/forms/ApplyCouponForm.js
- frontend/public/src/components/forms/ChangeEmailForm.js
- frontend/public/src/components/forms/ChangePasswordForm.js
- frontend/public/src/components/forms/EditProfileForm.js
- frontend/public/src/components/forms/EmailForm.js
- frontend/public/src/components/forms/LoginPasswordForm.js
- frontend/public/src/components/forms/ProfileFormFields.js
- frontend/public/src/components/forms/RegisterDetailsForm.js
- frontend/public/src/components/forms/RegisterEmailForm.js
- frontend/public/src/components/forms/ResetPasswordForm.js
- frontend/public/src/containers/pages/profile/EditProfilePage.js
- frontend/public/src/containers/pages/records/LearnerRecordsPage.js
- frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
- frontend/public/src/lib/test_utils.js
- frontend/public/src/lib/validation.js
- yarn.lock
Fix https://github.com/mitodl/hq/issues/3827
Update formik
adds aria-invalid and  aria-describedby when validation errors.
Go to profile page, try to submit the form without a required field filled out. When you click sbmit it should scroll you to the errored field, and show the error message in red.
Do the same with all forms:
- Change email,
- change password
- profile fields
- learner records page
- reset password form
- Register email
- register password
- AddlProfileFiledsForm
Then test the accessibility of the form.
Use voiceover to move through the form, try to submit the form with empty required field. The screen reader should read the error message, and focus on the field with the error message.
> Form error messages should appear consistently and be accessible 

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/lib/test_utils.js
Fix https://github.com/mitodl/hq/issues/3944
When selecting "Please select" again it should reset `currentCourseRun` and disable both upgrade and enroll buttons.
> Fix enrollment dialog default option

- courses/management/commands/create_courseware.py
- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
- frontend/public/src/util/integration_test_helper.js
NA
1. Removes a bunch of unused or duplicate code.
2. Refines logic and methods to be more single-purpose/functional.
3. Allows for Program + department URLs such as http://mitxonline.odl.local:8013/catalog/programs/science
4. Resolves and issue where https://rc.mitxonline.mit.edu/catalog/programs loads an empty catalog page.
1. Verify that you can navigate the catalog page for both courses and programs, switching between departments, switching between tabs, and loading more courses and programs as you scroll.
2. Verify that you can navigate to the course and program tab using a URL such as http://mitxonline.odl.local:8013/catalog/programs/
3. Verify that you can navigate to the course and program tab, and filter by department, using a URL such as …
> Fix catalog page for empty app

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll.js
Fix https://github.com/mitodl/hq/issues/3430
Updates the Course info box to still show info when no active run is available.
To test this make sure you have a course that has no runs that are open for enrollment. The go to that course page, for exapmle: http://mitxonline.odl.local:8013/courses/w-course-29/
Make sure nothing else breaks.
> Course Product Page with no Runs

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/util.js
Related to https://github.com/mitodl/hq/issues/2833 
Related to https://github.com/mitodl/hq/issues/2834
Updates the course info box to show:
- end dates for all active course runs
- The More Dates button is now dark blue and when you hover becomes red
- updates the styles and text of the icons and the text for information about start and ends dates for all the runs.
**This PR only addresses the Course Start and End dates section not the whole info box.**
Have a course with multiple active course runs (enrollment open). Go to the the course product page and verify that the functionality is still there and the design is as [described here.](https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?node-id=4792-207)
> Adding end date info to the CourseInfoBox

- frontend/public/src/lib/notificationsApi.js
Fix https://github.com/mitodl/hq/issues/3982
updates a notification message when a user tries to enroll second time.
enroll in an existing course run, then try to enroll again you should get a red notification with the updated message.
> Update duplicate enrollment meassage

- frontend/public/scss/product-page/product-details.scss
None
Fixing a spacing issue for the warning message for archived and no run courses:
Before:
After:
> Update styles for warning message on course product page

- frontend/public/src/containers/pages/CatalogPage.js
- frontend/public/src/containers/pages/CatalogPage_test.js
https://github.com/mitodl/hq/issues/4137
Fixes an issue when displaying the course and program counts on the catalog page when viewing with a mobile display.
1. Use this branch with a instance of MITx Online which has a few courses and programs.  There should be a different number of course and programs - ex. 3 courses and 2 programs.
2. Visit the MITx Online catalog page (http://mitxonline.odl.local:8013/catalog/) using a mobile display.
3. Verify that the issue is resolved.
> 4137: mitx online course and program count on catalog page is incorrect in mobile view

- frontend/public/package.json
- yarn.lock
https://github.com/mitodl/mitxonline/pull/2167
Removes the react-swipeable dependency which is not used.
> Remove react-swipeable dependency

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
Fix https://github.com/mitodl/hq/issues/4122
Adds a popup with explanation of the course format.
Go to course product page and click the "Learn More" link in front of course format.
> Course format pacing info popup

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
related to https://github.com/mitodl/mitxonline/pull/2187
Adds a "Learn More" link
This link opens a popup dialog with info and a link to explanation page.
Go to an archived course, you should see a yellow warning message. It should have a "Learn More" link that opens a dialog with more info.
Make sure that the Course Format link still works correctly, showing Self-Paced or Instructor-Paced popup info.
> Adding a Learn More link to Archived message

- courses/views/v1/__init__.py
Fix https://github.com/mitodl/hq/issues/4210
We had a problem where a user was downgrading their enrollment by enrolling again.
So we restricted duplicate enrollments.
However, this caused the issue above.
This PR restricts duplicate enrollment only if user is verified in that course.
Enroll for free in a course run.
Then try to pay for it.
The payment should be successful, and you should see your enrollment in the dashboard.
> restrict duplicate enrollment only if user is verified

- .secrets.baseline
- app.json
- cms/tasks.py
- main/settings.py
Updates https://github.com/mitodl/hq/issues/4029
Adds an offset, single run  cron task that runs every minute to check if the items exist and update if not. This is offset by 30 seconds so it gives some space for the similar google sheets task.
Run the app and see that the cron is running in the celery logs. There should be adequate logging to view this manually.
> Add task for creating featured items in cache

- courses/api.py
- courses/models.py
- courses/models_test.py
- courses/serializers/v1/base.py
- courses/serializers/v1/courses_test.py
- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/courseTypes.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/courseApi_test.js
Fix https://github.com/mitodl/hq/issues/4146, https://github.com/mitodl/hq/issues/4197, https://github.com/mitodl/hq/issues/4199
When only archived run is enrollable it has priority of coming up future runs.
This PR changes the logic for firstRelevantRun:
1. If there are enrollble runs - choose the one that is closest to now, giving preference to runs that start in the future.
2. If there are no currently enrollable runs, then return a run that will be enrollable in future
3. If there are no enrollable now and enrollable in future runs than return null. When this happens the "Enroll Now" button will be grey and disabled with the text "Access Course Materials".
Create a run the has an enrollable archived course and a run in the future like this course in production: …
> Give priority to enrollable runs

- courses/admin.py
None
Adding the ability to filter certificates which make it easy to track if certificates for a particular course or a program.
Also removing `certificate_page_revision` from the list view since it too long and not that important. If you need to check the certificate version then just view the individual certificate.
> Admin: filtering certificates by course and program

- cms/api_test.py
Fixes https://github.com/mitodl/hq/issues/4308
test_create_featured_courses performs fine when the dates align, but when the factory produces a random date sometimes that date doesn't align as one would expect. To combat this, I set the dates based on one on another and based on "now" to keep the results consistent.  This was already in place for the future courses since their dates determined their order, but I have also now done this for the in_progress course.  I also made the check that they're all in place into one statement instead of 4 using sets.
Check my logic and run the test... a lot.
> Fix flaky test: test_create_featured_courses

- courses/signals.py
- courses/signals_test.py
https://github.com/mitodl/hq/issues/3783
https://github.com/mitodl/mitxonline/pull/2193
Fixes an issue when syncing the hubspot user.
- Setup Hubspot with MITx Online
- Create a user and create a CourseRunCertificate for that user.
- Verify that the user's Hubspot contact is updated with the CourseRunCertificate.
> Fix syncing hubspot user

- cms/api_test.py
NA
Repairs a flaky test (test_create_featured_items) that is dependent upon Course and CourseRun dates when filtering.
Unit tests should always pass.
> Repair test based on dates (test_create_featured_items) 

- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/lib/courseApi.js
Related to https://github.mit.edu/mitxonline/mitxonline-issues/issues/671
Renaming enroll now button for archived courses
> Renaming enroll now button for archived courses

- courses/admin.py
- courses/serializers/v1/courses_test.py
- courses/serializers/v2/courses.py
- courses/serializers/v2/programs.py
- courses/serializers/v2/programs_test.py
- courses/views/test_utils.py
Checks off second box https://github.com/mitodl/hq/issues/4110
Adding course topics to course and program api
Go to http://mitxonline.odl.local:8013/api/v2/courses/
http://mitxonline.odl.local:8013/api/v2/programs/
> Adding topics to course and program api

- courses/models.py
- courses/serializers/v2/courses.py
- courses/serializers/v2/programs.py
In response to https://github.com/mitodl/mitxonline/pull/2235 which is a fix for issues with the deploy of https://github.com/mitodl/mitxonline/pull/2228
Since the deploy of the above pull request in RC, you'll see a 500 on the API and the catalog page will not load due to a `RelatedObjectDoesNotExist`  error.  There was a PR put up to fix this, but I found a couple of issues so I put up this PR as a response. This PR is meant to address the 500 errors without disrupting other parts of the application and to fully address the issue as the other PR only covered the courses API and the programs API is seeing the same issue.
I reverted the change to the property on the Course model and instead I changed the `get_topics` function in the serializers to use `if hasattr(instance, "page") and …
> Use hasattr() rather than directly referencing the property when checking for course.page

- courses/models.py
- courses/serializers/v2/courses.py
- courses/serializers/v2/programs.py
Related to https://github.com/mitodl/mitxonline/pull/2228
Fixing naming overlap between `Course.page` as property and as a related name to `CoursePage`
Create a course without a course page.
Go to `http://mitxonline.odl.local:8013/api/v2/courses/`. Make sure it works.
> Fixing CoursePage related name overlap

- cms/models.py
- cms/models_test.py
- courses/api.py
- courses/api_test.py
- courses/views/v1/__init__.py
- courses/views/v1/views_test.py
Fix https://github.com/mitodl/hq/issues/4493
Filter relevant course runs to be live
Test course about page,for courses that might have a no runs open for enrollments, and runs that are open but no longer live. Both cases should show the same view. They should not appear in the catalog.
Nothing else should break.
> Filter relevant course runs to be live

- frontend/public/src/components/forms/EditProfileForm.js
NA
This PR fixes an issue on the edit profile and additional details forms where the "Are you a" checkboxes were not being populated with the user's saved profile information.  The form would still save the form correctly.
Visit the edit profile page or additional details form, documented here: https://docs.google.com/document/d/1W7jYty8HjkaYxSFXoUMF9ZYTOp8eJ4ssmINfgLhQ61Q/edit?pli=1#heading=h.hi2minfkuu1y
Check or uncheck one of the checkboxes on the form.  Submit the form.  After the page reloads, verify that the changed checkbox represents the change made prior to submitting the form.
> Populate profile form occupation checkbox with saved data from user profile

- ecommerce/admin.py
https://github.com/mitodl/mitxonline/issues/2201
https://github.com/mitodl/mitxonline/issues/1895
Fixes the Django Admin search for Products
1. Have an instance of MITx Online with a Product created. 
2. Visit mitxonline.odl.local:8013/admin/ecommerce/product/
3. Use the search bar to search for your Product.  Verify that your Product is displayed if the search matches.
4. Use the search bar to search for a non-existing Product (random string that doesn't match any Product string).  Verify that your Product is not displayed.
> Fix Django Admin search for Products

- docs/source/configuration/open_edx.rst
- docs/source/configuration/tutor.rst
https://github.com/mitodl/hq/issues/4416
This PR replaces `mitxpro-openedx-extensions `with `openedx-companion-auth` in the readme file. More details in the ticket
- Validate the changes in [open_edx.rst](https://github.com/mitodl/mitxonline/blob/anas/update-readme/docs/source/configuration/open_edx.rst) and [tutor.rst](https://github.com/mitodl/mitxonline/blob/anas/update-readme/docs/source/configuration/tutor.rst)
> docs: replaced mitxpro-openedx-extensions with openedx-companion-auth in readme

- courses/serializers/v2/courses.py
https://github.com/mitodl/hq/issues/4575
Adds the Instructor name and description to the Courses API v2 for all Instructors associated with a Course Page.
1. Run the configure_instance command.
2. Create an Instructor page in the CMS.  Add the instructor to the Course page.
3. Visit http://mitxonline.odl.local:8013/api/v2/courses/<COURSE_NUMBER> and verify that the instructor added to the Course Page is included in the API response.
> Include course instructors in V2 API results

- cms/api.py
- cms/constants.py
- cms/models.py
- cms/tasks.py
Fixes https://github.com/mitodl/hq/issues/4615
modifies the function that checks for a key in the cache to also check the TTL to reset the cached list a little prior to expiration so we don't see it break
Manually set a key to be cached for under 10 minutes instead of 24 hours, next time the task runs (every minute)), you should see it replace the key even though TTL is not 0. 
Also, if there's nothing in the cache, the homepage shouldn't be disrupted, just empty in that area.
> Adding TTL check and coursepage

- main/settings.py
- sheets/tasks.py
Related to https://github.com/mitodl/hq/issues/4550
I looked at the logs for June 6th and this task was taking up to 4 minutes, and the schedule was set to run every minute.
sets a time limit on the task and sets the schedule to every 5 min.
I am not sure what would be the best way to abort the task if it has exceeded the time limit.
Add this to the task and watch the logs:
```
import time
time.sleep(130) 
```
> Set time limit for task process_google_sheet_requests

- cms/tasks.py
Fixes https://github.com/mitodl/hq/issues/4651
Fixes the task to use the correct cache when checking ttl for the featured courses
Delete your local featured items :
```
from django.core.cache import caches
redis_cache.get("CMS_homepage_featured_courses") // should return a list if you have any set
redis_cache = caches["redis"]
redis_cache.delete("CMS_homepage_featured_courses")
redis_cache.get("CMS_homepage_featured_courses") // should return nothing 
```
Wait for the task to run on celery, every minute, at :30.  You should see successful output in terminal and running `.get` again should return a new list
A good next test would be to set ttl for the line to under 10 minutes (so less than 600 seconds) manually, after it has run successfully:
```
from django.core.cache import caches …
```
> Change the cache from memcache to redis in the task as well as it is in util func

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/ProgramProductDetailEnroll.js
https://github.com/mitodl/hq/issues/4662
Fixes a styling issue where the text of the "Enrolled" button on the Program about page was white on a white background, when the learner is enrolled in the Program.
1. Enroll into a Program.
2. Visit the Program's about page.
3. Verify that the "Enrolled" button has white text on a red background and does not change when hovered.
> Program enroll button text does not appear on about page

- docker-compose.yml
Related to https://github.com/mitodl/mitxonline/pull/2240/commits/948d9559d2814074d5d4b1c07393bd395d83ebc0#r1633562871
Throws error
```
service "db" refers to undefined volume db-data: invalid compose project
```
Should run docker compose build and up with no error.
> Fix invalid compose project

- frontend/public/src/components/CourseProductDetailEnroll.js
Fix https://github.com/mitodl/hq/issues/4424
This updated the "enroll now" login button to say "access course materials" if the course is archived.
You should have a course that is archived.
Take a look the the course about page when logged in and logged out.
The button should say "Access Course Meterials"
> Login button should indicate when course is archived

- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
https://github.com/mitodl/hq/issues/4548
Removes the "Course details" link on the course cards shown on a learner's dashboard if the course does not have a published CMS page.
1. CReate course with a drafted CMS page.
2. Enroll user in course
3. Visit user's dashboard.
4. Verify that the "Course details" link is not displayed on the course card.
> 4548 dashboard dont display course detail link when the course about page is not published

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/CourseInfoBox.js
https://github.com/mitodl/hq/issues/4152
Fixes the spacing and contrast of the icon element on course about pages which have no course runs that are enrollable in the future.
1. Create or update a course run that is not enrollable based on the defintion here https://docs.google.com/document/d/1F0e-laruWOgCAe_NOA-MENcjh4_SECdGUJ_q-yTJS50/edit#heading=h.1hrid43inzkv
2. visit the Course's about page and verify that spacing and color of the icon.
> Preliminary Test-More-Dates "No Sessions" design: Exclamation point icon - low contrast and spacing

- frontend/public/src/components/EnrolledItemCard.js
https://github.com/mitodl/hq/issues/4913
Fixes an issue caused when loading the dashboard while also enrolled in a course with no page.
1. Enroll into a course run associated with a course that has no page.
2. Visit your dashboard.
3. Verify the dashboard loads and that the course is shown on the dashboard.
> Enrollment in a course run without a course page crashes the dashboard

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/lib/courseApi.js
Fix https://github.com/mitodl/hq/issues/4877
Filters course runs for enrollment in the enrollment dialog.
Create at least two or three course runs. Make one of them with future enrollment. Go to the product page and open the enrollment dialog. The future course run should not show up in the options.
> Show only enrollable runs in the enrollment dialog

- ecommerce/views/v0/__init__.py
n/a but a relevant Sentry error is here: https://mit-office-of-digital-learning.sentry.io/issues/5647502284/?project=5864687&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D&referrer=issue-stream&statsPeriod=14d&stream_index=0
There's code in the checkout interstitial that generates a context for Google Analytics, and includes discount info if there is any. This fixes a minor issue with it that was causing 500 errors.
Create an order with a discount code, and then checkout. _Don't use a zero-value code._ If the discount brings your order to $0, you won't get routed through CyberSource. But, checkout should work fine.
> Fixing discount code payload generation for Google Analytics

- openedx/api.py
- openedx/api_test.py
Fix https://github.com/mitodl/mitxonline/issues/2225 and https://github.com/mitodl/mitxonline/issues/1797
If use enrolls, unenrolls, and enrolls again, the course run enrollment in edx should be active, otherwise the user can't access the course on edx, just like it happened for this user https://github.com/mitodl/hq/issues/4367.
On open edx `is_active = False` is equivalent to being unenrolled.
Locally you can test if by enrolling in a course for an audit track, then unenrolling, then paying again. You can pay with a coupon too.
The api would get called again. This double call of create enrollment api is going to set is_active to true on repeated call.
> When creating enrollment set is_active explicitly in the enrollment api call

- ecommerce/serializers.py
- frontend/public/src/containers/pages/checkout/OrderHistory.js
https://github.com/mitodl/hq/issues/5106
Changes the order page to display the datetime for orders using the update_on value instead of the created_on value for the associated order.
1. Begin to purchase a Course.
2. Take a minute or two to complete the payment steps.
3. Verify the order page displays the update_on value which should be equal to the time when you completed the payment steps and were redirected back to MITx Online.
> MITx Online receipt displays wrong date

- frontend/public/src/components/NotificationContainer.js
Fix https://github.com/mitodl/hq/issues/715
Makes the alert/notification at the top of the page get read by the screen reader when it appears on the screen.
Turn on the screen reader then try to enroll or/and unenroll from a course. the screen reader should read the alert message when it comes up.
> Make the enrollment alert read by screen reader

- courses/models.py
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
Fix https://github.com/mitodl/hq/issues/5098
In terms of logic there are three places where this is important:
1) I n deciding which "Enroll Now" button to show, (open a dialog or just submit a form)
2) in rendering the enrollment dialog drop down for selecting a run
3) Displaying "more dates" section
Everything should function as usual except for:
1. If there is only one run that is open for enrollment and is upgradable the Enroll Now button open a dialog where the user still has a select dropdown (instead of no dropdown). This makes the choice deliberate and makes the course dates visible.
2. An archived course is not chosen as `next_run_id` if there are other enrollable runs
3. Only enrollable runs show up in the "More Dates" section.
Make sure the "Enroll now" button, the enrollment …
> Filtering only enrollable runs on the product page

- courses/serializers/v2/courses.py
- courses/serializers/v2/courses_test.py
Fix https://github.com/mitodl/hq/issues/5176 and https://github.com/mitodl/hq/issues/5177
time_commitment and durations to the courses api
Go to http://mitxonline.odl.local:8013/api/v2/courses/ and make sure  that time_commitment and durations show the values you entered in the cms.
> Add time_commitment and durations to the courses api

- main/settings.py
Fix https://github.com/mitodl/hq/issues/4956
Adjust the schedule of `courses.tasks.generate_course_certificates` to run twice a day.
> Generate certificates twice a day

- courses/serializers/v2/courses.py
- courses/serializers/v2/courses_test.py
- courses/utils.py
Closes https://github.com/mitodl/hq/issues/4994
Adds availability to the courses API endpoint. If a course has any dated run open for enrollment, API will show `dated` for that course. If there are only self paced courses, it will show `anytime`
Hit the endpoint with courses with multiple courseruns. Some good date variability would be to have some runs open for enrollment and some not. Having variability in whether or not they are self-paced will show if the changes meet the need as well.
> Add availability to Courses API endpoint

- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/ProgramInfoBox.js
Fix https://github.com/mitodl/hq/issues/4491
Updates the section for duration and required effort to allow longer text.
> Updating styles for program info box

- courses/serializers/v2/courses.py
- courses/serializers/v2/courses_test.py
- courses/utils.py
- courses/utils_test.py
Fixes https://github.com/mitodl/hq/issues/5260
Rather than relying on the adverse, this PR adds a gunction, get_dated_courseruns, to get any dated, enrollable courseruns for the course being serialized.  I've also added a test to this effect. This will generate the correct availability as we defined dated as having 1 or more dated courseruns, regardless of whether they also had archived or self-paced courses.
Create courseruns that are both enrollable and not, self-paced and not and you should still see dated as long as one is both enrollable and not self-paced.
> Add get_dated_courseruns function for availability to check for dated courses

- courses/serializers/v1/base.py
- courses/serializers/v1/courses_test.py
- courses/utils.py
- frontend/public/src/components/CourseInfoBox.js
- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/CourseProductDetailEnroll_test.js
- frontend/public/src/factories/course.js
- frontend/public/src/flow/courseTypes.js
- frontend/public/src/lib/courseApi.js
- frontend/public/src/lib/util.js
Fix https://github.com/mitodl/mitxonline/issues/2357
This PR changes the front end to use a single source of is_archived and makes the catalog display "Start Anytime" even when the course is not `is_self_paced=True'
Is archived is used in many places in the frontend, but it's value is not dynamic, so it's better to compute it in the backend.
> Catalog card should show Start Anytime if the course is archived

- courses/templates/mail/course_run_unenrollment/body.html
- courses/templates/mail/course_run_unenrollment/subject.txt
https://github.com/mitodl/hq/issues/3832
Fixes typo in the unerollment email
unenroll from a course and ensure that the typos are corrected in the email subject line and body.
> Fix typo in unenrollment email

- courses/serializers/v2/programs.py
- courses/serializers/v2/programs_test.py
https://github.com/mitodl/hq/issues/4970
Uses the Department serializer to serialize the program's departments on the program API.
Visit http://mitxonline.odl.local:8013/api/v2/programs/ and ensure that the departments are formatted the same as http://mitxonline.odl.local:8013/api/v2/courses/
> Department serializer for programs API

- courses/api_test.py
- courses/apps.py
- courses/models_test.py
- courses/signals.py
Fix https://github.com/mitodl/mitxonline/issues/2365
Imports signals courses config.
create all required course run certificates for your program. A program certificate should get created automatically .
> Make post_save CourseRunCertificate signal work

- frontend/public/scss/cards.scss
- frontend/public/scss/common.scss
- frontend/public/scss/dashboard.scss
- frontend/public/scss/layout.scss
- frontend/public/scss/product-page/product-details.scss
- frontend/public/src/components/EnrolledItemCard.js
Fix https://github.com/mitodl/hq/issues/5406
Updates the dashboard dialogs for unenrolling from a course, program, email preferences.
Try to check all dialogs and see that the styles are consistent.
> updating styles for dashboard dialogs

- courses/api.py
Fix #https://github.com/mitodl/hq/issues/5643
If the user has a revoked program certificate, it's a special case, just skip them for now.
Create a user with a revoked program certificate that has met all program requirements. The call `generate_program_certificate(user, program)`. It should not error.
> Ignore revoked program certificates for now

- .secrets.baseline
- main/settings.py
- main/urls.py
https://github.com/orgs/mitodl/projects/21/views/6?pane=issue&itemId=81655244
Viewflow was overriding the 404 error page which then overrided our custom 404 error page.  This PR move the viewflow library lower in on the list of installed apps in the settings.py file, which will allow for our custom 404 error page to take precedence over the 404 error page provided by viewflow. 
Set `DEBUG` equal to `False` in your .env file as well as the docker-compose.yml file.
Restart your application and visit a page like http://mitxonline.odl.local:8013/fake.
Verify that the MITx Online custom 404 page is displayed and not the 404 page from viewflow (you can currently see the 404 page from viewflow if you visit https://rc.mitxonline.mit.edu/fake.
> fix custom 404 template

- courses/serializers/v2/programs.py
- courses/serializers/v2/programs_test.py
https://github.com/mitodl/hq/issues/5698
Adding `duration` and `time_commitment` to the program API 
Create a program and populate the length/duration and effort/time_commitment in the program CMS page. These fields should be populated via the endpoint /api/v2/programs/
> add duration and time_commitment to program API

- flexiblepricing/mail_api.py
https://github.com/mitodl/hq/issues/5762
Updates the flexible price email attribute that is used in the template for sending flexible price emails to learners.
This will need to be tested on RC.  There is an issue when loading the staff-dashboard locally using the main branch: https://github.com/mitodl/hq/issues/5837.
> Don't show course and program ids in financial assistance emails

- .github/workflows/ci.yml
- docker-compose.yml
Reverts https://github.com/mitodl/mitxonline/pull/2329/files
I initially thought the postgres upgrade worked fine but my local was caching things or something weird.  Anyway, upgrading to Postgres v16 without any modifications to our data does not work, so this PR reverts that upgrade.
> revert postgres upgrade

- frontend/public/src/components/NotificationContainer.js
Related to https://github.com/mitodl/hq/issues/715
Set tab index to -1
Trigger a notification through enrollments or failiure of enrollment and make sure that the notifications dic is set to tab-index: -1.
> Notifications set tab-index to -1

- frontend/staff-dashboard/src/styles/antd.less
refine-antd upgrades to v4 in https://github.com/mitodl/mitxonline/pull/2399 (I didn't notice the button color changed when testing the PR)
Apply custom CSS to the staff dashboard after the package `refine-antd` is upgraded to v4, the primary button's color has changed to blue in v4, which doesn't match with https://rc.mitxonline.mit.edu/staff-dashboard/. 
Since https://github.com/ant-design/ant-design/blob/master/components/style/themes/default.less no longer exists in `refine-antd v4`, this PR is to add some CSS to match the button color with the existing staff dashboard.
docker-compose build
docker-compose up
Go to staff dashboard http://mitxonline.odl.local:8013/staff-dashboard/flexible_pricing and compare to RC
> add css to refine dashboard after refine-antd upgrades to v4

- .secrets.baseline
- authentication/pipeline/user_test.py
- authentication/views_test.py
- openedx/api.py
- openedx/api_test.py
- users/serializers.py
- users/serializers_test.py
Fix https://github.com/mitodl/hq/issues/5642, https://github.com/mitodl/hq/issues/5931
Adds email as one of the fields to validate.
Retire an existing user, then try to create an account with the same email address but different username.
> Validate user email on account creation

- courses/management/commands/manage_program_certificates.py
Related to https://github.com/mitodl/hq/issues/6131
add option to generate certificates for a program
1. Have a user that has passed all required courses in your program. 
2. Make sure the program certificate is not there. If your program does not have a certificate child page created then the program certificates don't get generated.
3. Then created the certificate page and Signatories for the program
4. Then run the management command:
` ./manage.py manage_program_certificates --create -—program=<my_program_id>`
> add option to generate certificates for a program

- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
- frontend/public/src/lib/queries/departments.js
Fix https://github.com/mitodl/hq/issues/6308
Remove pagination for departments api
Create over 12 departments with courses. Go to http://mitxonline.odl.local:8013/api/v2/departments/
You should see all departments on one page.
> Remove pagination for departments

- frontend/public/scss/catalog.scss
- frontend/public/src/containers/pages/CatalogPage.js
Fix Partially https://github.com/mitodl/hq/issues/3478
Re-orders the title and start time of the course to be read in the proper order by the reader.
Everything should look the same.
Using voiceOver.
> Re-orders the title and start time of the course to be read in the proper order by the reader

- frontend/public/scss/dashboard.scss
- frontend/public/src/components/EnrolledItemCard.js
- frontend/public/src/components/EnrolledItemCard_test.js
Fix https://github.com/mitodl/hq/issues/6344
Make dropdown menu same as in the header.
for course items and program items.
Go to the student dashboard and make sure the dropdown menu looks good and works.
> Enrolled Course Item dropdown menu accessibility 

- .secrets.baseline
- app.json
- frontend/public/src/flow/declarations.js
- frontend/public/src/lib/auth.js
- frontend/public/src/lib/auth_test.js
- main/settings.py
- main/utils.py
- main/utils_test.py
mitodl/hq#6520
After login, this throws the user to the Unified Ecommerce session start endpoint, which will start up a session for the user there and then send them back to MITx Online. This ensures the user can interact with the cart while in MITx Online (to get cart status, add items, etc.). 
The code for this is feature flagged out. Ensure `enable_unified_ecommerce` is configured in PostHog to test this. It needs to be Enabled. (Additionally, you should have your MITx Online setup configured to use PostHog, and ideally a project that you control rather than one of the regular OL ones.) 
You'll need a Unified Ecommerce instance set up. Specifically, it will need to be set up and tracking jkachel/6520-add-updates-to-establish-session so you have the other side of the equation (unless …
> Add support for round-tripping the user through Unified Ecommerce on login

- cms/models.py
fix https://github.com/mitodl/hq/issues/6415
Removing the ordering of instructor link page. It doesn't do anything useful.
When the admin re-chooses instructors the order is unpredictable, or at least was unpredictable.
1. Go to cms page. Start editing a course page by adding a bunch of instructors to the page. Check the order on the page.
2. Then go ahead and change some of the selection to another instructor. Check the order of instructors on the page again. (this used to mess up the order)
3. Then try deleting and adding them in the desired order.
Check that the order is as expected.
> removing order from InstructorPageLink

- .github/workflows/docs.yml
Fix this error 
`The version '3.1' with architecture 'x64' was not found for Ubuntu 22.04`
puts 3.10 in quotes.
> docs yml correct python version

- courses/api.py
- courses/management/commands/defer_enrollment.py
N/A
Awhile ago we added the possibility to defer enrollments without providing a course run to defer to. Now I the management command can do that too.
Try to run the management command:
`./manage.py defer_enrollment --user example@mit.edu --from-run  course-v1:MITxT+18.01.1x+1T2025
`
you should get 
```
Deferred enrollment for user: User username=username email=example@mit.edu
Enrollment deactivated: <CourseRunEnrollment: id=2, run=course-v1:MITxT+18.01.1x+1T2025, mode=audit>
Enrollment created/updated: N/A
```
> Allow to defer enrollment without to_run

- courses/api.py
None
Currently, if a user gets downgrades from verified to audit they get dent an email about enrolling in the course run.
We should not send email about enrollment in a course if the user got downgraded from "Verified" to "Audit".
You can use a management command to defer your enrollment. The enrollment should be set to "audit" and "deferred" And you should not receive and email about enrolling in an audit mode for the course run.
`./manage.py defer_enrollment --user example@mit.edu --from-run course-v1:MITxT+14.73x+1T2026`
> No emails for downgrading enrollment

- courses/api.py
None
Don't send email when downgrading enrollment.
You can use a management command to defer your enrollment. The enrollment should be set to "audit" and "deferred" And you should not receive and email about enrolling in an audit mode for the course run.
./manage.py defer_enrollment --user example@mit.edu --from-run course-v1:MITxT+14.73x+1T2026
> making downgrade not send email

- courses/serializers/v2/courses.py
- courses/wagtail_hooks.py
- courses/wagtail_views.py
Related to https://github.com/mitodl/hq/issues/5432
Removes the Course topics menu items in the admin view in the cms.
The topics are still available at http://mitxonline.odl.local:8013/cms/topics/.
Adds parent topic for each child topic in the api.
Take a look at the cms admin side bar.
Take a look at https://mitxonline.mit.edu/api/v2/courses/ and make sure that the parent topic appears.
> Remove duplicated course topics

- courses/api.py
Fix https://github.com/mitodl/hq/issues/6927
This effects not just deferrals, but all requests that are modifying an enrollment through this method:
The change status will be set to the provided value or to the default value. Rather then setting it only when the mode was anything else than None.
This allows to reset an active enrollment to a clean state.
This allows for a previously deferred run to get "un-deferred".
You can test it with the management command.
`./manage.py defer_enrollment --user example@mit.edu --from-run  course-v1:MITxT+18.01.1x+1T2025 --to-run course-v1:MITxT+18.01.1x+2T2025`
And then reverse it back
`./manage.py defer_enrollment --user annagav@mit.edu --from-run  course-v1:MITxT+18.01.1x+2T2025 --to-run course-v1:MITxT+18.01.1x+1T2025`
> Reset change_status on all requests to create_run_enrollment

- config/default.vcl
- docker-compose.yml
N/A
This simplifies and fixes the varnish configuration so that it doesn't do the extra steps of setting a hardcoded host name.
Instead, the `docker-compse.yml` has been updated to use the forwarded host/port, which accomplishes the same result but will work for arbitrary url bases.
I also made a bit of a breaking change to the way that `PUBLIC_PATH` is set because I need to be able to override the entire string (e.g. `https://mitxonline.odl.local', different protocol and no port). This shouldn't be an issue for most people unless they doing something super custom.
You should be able to `docker compose up` and the app should function like normal.
> Fix varnish config for arbitrary hostnames

- scripts/run-django-dev.sh
None
This PR runs `./manage.py createcachetable` as part of setup.
If you want to test this, you probably need a fairly clean install of mitxonline. After running migrations, you'll get a 500 error `relation "durable_cache" does not exist`. This fixes it. 
In lieu of starting with a fresh db, you could just check that `docker compose up` still works.
> automatically create cache table

- courses/views/v1/__init__.py
- openapi/specs/v0.yaml
- openapi/utils.py
- scripts/test/openapi_spec_check.sh
Related to https://github.com/mitodl/hq/issues/7004
Fixes some issues with the `api/v1/enrollments/` OpenAPI schema
1. Tests should pass
2. http://mitxonline.odl.local:8013/dashboard/ should still show your enrollments
3. http://mitxonline.odl.local:8013/api/v1/enrollments/ should still show your enrollments
> Improve openapi schema for enrollments API

- cms/serializers.py
- courses/serializers/v1/courses.py
- courses/serializers/v2/courses.py
- openapi/specs/v0.yaml
For dashboard work, noticed during https://github.com/mitodl/hq/issues/7004
Marks the a few nullable properties as optional.
This should have absolutely no runtime effects.
> A few small schema fixes (optional fields)

- .pre-commit-config.yaml
- .secrets.baseline
- conftest.py
- ecommerce/api_test.py
- ecommerce/serializers_test.py
- ecommerce/views_test.py
- poetry.lock
- pyproject.toml
- scripts/test/python_tests.sh
N/A
Python tests have been taking an increasing amount of time to run, definitely locally and I suspect github actions are suffering as well. This adds the plugin `pytest-xdist` which allows the tests to run in parallel. Each test worker gets its own db so they don't stomp on each other.
It also fixes the ecommerce tests which starting failing when run in parallel because some the settings fixture (moved to `conftest.py`) was setting the settings on the global django settings instead of the pytest `settings` fixture so it was leaking across test boundaries, but in such a way that it allowed other tests to pass that otherwise wouldn't have the correct configuration if they ran earlier.
You can run this a few ways (you don't need to test them all, but test at least one `-n` option):
- …
> Add xdist so tests can be run faster

- courses/api.py
- courses/management/commands/populate_course_data.py
- courses/models.py
Related to https://github.com/mitodl/hq/issues/5336
Allows to enroll in test course runs without enrollment in edX.
In django shell run `./manage.py populate_course_data`
Enroll in one of the test courses named starting with "Case 1:"
Enroll in other courses make sure enrollment works.
> Successfully enroll in test course runs without clalling edX

- courses/management/commands/populate_course_data.py
- courses/management/courses.json
Related to https://github.com/mitodl/hq/issues/5335
Add more courses with different runs based on the issue https://github.com/mitodl/hq/issues/5335.
Run `./manage.py populate_course_data`
got to `http://mitxonline.odl.local:8013/catalog/courses/test-scenarios-department` to view them.
or http://mitxonline.odl.local:8013/courses/course-v1:MITxT+0.010x/
> add more scenarios

- courses/models.py
related to https://github.com/mitodl/mitxonline/pull/2584
I add a typo after resolving a circular import in the previous PR.
Fixing a little typo
Enrollment in test courses should succeed.
> Small fix for the fake test course runs

- cms/models.py
Fix https://github.com/mitodl/hq/issues/7052#issuecomment-2787490264
Make Preview certificate work in the CMS
Created a certificate page for a program or a course.
Create Signatories.
Preview the pages.
> Make Preview certificate work in the CMS

- docker-compose.yml
N/A
The APISIX service is missing a `profile`, this adds it.
By default the service should not start, add `apisix` to `COMPOSE_PROFILES` to have it start:
```COMPOSE_PROFILES=apisix docker compose up```
> Add a compose profile for apisix

- Dockerfile
- poetry.lock
- pyproject.toml
- users/models.py
N/A
This updates the apigateway dependency to use https://github.com/mitodl/ol-django/pull/237
Also cleaned up some lint errors in Dockerfile
You should be able to create new accounts and the `createsuperuser` command should work again.
> Remove override of User.USERNAME

- Dockerfile
- docker-compose.yml
Fixes some issues with pathnames in the Docker Compose environment. For the Kubernetes deployment, the Dockerfile changed to put the app at `/src` in the image, not `/app` - but the mounts in the Compose file got missed, so it didn't seem like changes were being propagated into your running container. This fixes that. (The path change is to keep things in line with other EKS deployments.) 
Also fixes some smaller things:
- Commands now use json format - this is the preferred method - and scripts get run via `/bin/bash` instead of directly
- In some places, the case for Dockerfile commands wasn't correct, so fixed that
- `ENV` should use the `variable=value` syntax now. (Also, `LABEL`.)
App should work normally. If you make changes, you should see them in the running container too.
I …
> Fix some issues with Docker infra config

- .github/workflows/ci.yml
- docker-compose.yml
- package.json
- yarn.lock
n/a
https://github.com/mitodl/mitxonline/pull/2618 fixed some stuff in the Django side of the app that was causing renovate to fail, but it also included a `yarn.lock` update that wasn't needed. Reverting that wasn't enough, though; there were some other issues with tests and node versions and specifically `cheerio` and `enzyme`, so this fixes that stuff too.
In short, this:
- [Pins `cheerio` to `1.0.0-rc12` to resolve an import error with cheerio](https://github.com/mitodl/mitxpro/pull/3113#issuecomment-2316890699)
- Updates CI to use Node 20.18
- Updates docker-compose to also use Node 20.18 (these two things didn't match)
Everything should run and work as expected. The CI action should run successfully.
I found the comment linked to above for xpro actually in the cheerio issue it links …
> Fix JS test failures in CI

- main/settings.py
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Closes https://github.com/mitodl/hq/issues/7250
This adds the `v1` and `v2` endpoints to the OpenAPI spec so they are published with the client when it is generated.
I'm not exactly certain how to test this here. This code needs to be committed so that the OpenAPI client can be regenerated in https://github.com/mitodl/mitxonline-api-clients.
This is being done to support the enrollments / UAI dashboard work in Learn which needs the additional endpoints.
> add v1 and v2 to the openapi spec

- docker-compose.yml
n/a
Just adds local.openedx.io to the `x-extra-hosts` section in the Compose file. Tutor defaults to this hostname now. You can certainly set up Tutor to use a different one, but we might as well have the default in there too.
Ideally, you have a Tutor instance or can get one set up that uses the default `local.openedx.io` domain name. You should be able to use the MITx Online integration stuff with Tutor successfully.
Practically, the `web` and `celery` containers just need to be able to talk to a container that's outside the MITx Online network using the `local.openedx.io` hostname. Since we're aliasing this to `host-gateway`, this means the container can be anything that can respond on a port. You can just use the `nginx` container for this: `docker run --rm -p 80:80 nginx` Then, in a …
> Update the extra hosts section to include local.openedx.io

- users/views.py
Fix https://github.com/mitodl/hq/issues/7308
Update edx user profile asynchronously
Try to save profile while missing OpenEdxApiAuth
> Update edx user profile asynchronously

- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
- users/serializers.py
- users/urls.py
Closes mitodl/hq#7326
Adds the users API to the OpenAPI spec by mounting it at `/api/v0` in the urlconf (in addition to `/api`, where it is now).
Also added a couple of small changes to the UserSerializer so that Spectactular knows what the types are for a handful of fields.
The Users API should appear in the spec.
> Update Users API to be versioned (at v0), so it shows up in the OpenAPI spec

- b2b/management/commands/b2b_list.py
- b2b/models.py
- b2b/views/v0/__init__.py
- main/settings.py
- poetry.lock
- pyproject.toml
- users/models.py
Closes mitodl/hq#7244
Other systems will likely need to access the B2B data (orgs and contracts) stored in the system. This adds API key authentication for those endpoints, so you can be either an admin user or supply an API key to access the data.
This also updates the `b2b_list` command to add an option to list out the users that are associated with an org or contract.
You should be able to create an API key in the Django Admin. Then, you should be able to access the b2b endpoints using the key: `curl -H "Authorization: Api-Key <key>" http://mitxonline.odl.local:9080/api/v0/b2b/organizations/` (and `contracts`). 
You should be able to run `b2b_list learners` and specify either `--contract` or `--org` to list users in a specific org. You may need to go in and …
> Add API key for B2B data

- app.json
- main/settings.py
N/A
Removes syslog handler from Django logging and relies solely on console logging.
Verify that logs still show up in docker-compose
The syslog handler won't work under Docker/Kubernetes. Removing it now that this app is no longer running on Heroku.
> refactor: Remove syslog logging handler

- courses/api.py
- courses/api_test.py
Fix https://github.com/mitodl/mitxonline/issues/2570
Deactivate audit enrollment before deferral
Try to defer an enrollment, where the to_run is already enrolled in audit.
you can do this by running a management command.
> Deactivate audit enrollment before deferral

- main/urls.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
- users/serializers.py
n/a
The `extend_schema_field` for `b2b_organizations` in the User serializer was just `list[str]`; this changes it so that it should return the proper organization type instead, and fixes the nested contract serializer so that it's typed correctly too.
This also adds the frontends for the schema - we didn't expose the schema download or Swagger UI endpoints before, and this adds that too.
Check the type of the `b2b_organizations` member in the users API (specifically, the `/api/v0/users/me` one).
You should also be able to get to Swagger at `/api/schema/swagger-ui/` and download the spec yaml at `/api/schema/` .
> Update urlconf to add accessible schema/Swagger URLs, add better typing for B2B data, update OpenAPI spec

- frontend/public/src/containers/App.js
- frontend/public/src/containers/pages/login/LoginSso.js
- main/settings.py
- main/settings_test.py
- main/views.py
n/a
- `/signin` will now redirect to `/login` if the middleware is enabled.
- Add `SESSION_COOKIE_DOMAIN` and `SESSION_COOKIE_NAME`, and default the latter to `mitxonline_sessionid`
- Update the Login button to do a full redirect when clicked - it was otherwise getting routed via React Router, which wasn't effective
- Remove the test to make sure `app.json` is up to date (but just that) since we're in k8s land now
- Reload the page. The session cookie name should have changed. You should be able to control what the cookie's name is and domain. 
- Ensure the middleware is enabled:
- Click Login. You should be taken to the APISIX login flow.
- Go to /signin - you should be redirected to /login (and then prompted to log in if you're unauthed).
> Changes to shore up a few minor issues around login

- ecommerce/serializers.py
Fix https://github.com/mitodl/hq/issues/7395
Remove content_type form LineSerializer
Make sure your user has an existing order
Go to order history 
the existing order should show up in the table.
> Remove content_type form LineSerializer

- frontend/public/src/components/OrderSummaryCard.js
N/A
If coupon code gets too long it pushes the text outside the box.
After:
> Coupon code style for very long codes

- frontend/public/src/lib/util.js
- frontend/public/src/lib/util_test.js
Closes mitodl/hq#7473
As noted in the issue, when the frontend hit a course that had no course runs in it, it called `getStartDateText`, which then dutifully sorted nothing and moment was left to operate on an undefined. Now, if there's no course runs, this should just return an empty string.
Create a course with a live page and everything, but no course runs. The catalog Courses tab should work as you would expect. The course should show up but it should not say anything for start date.
Not sure if we want something else here besides empty string. I think generally we were expecting there to always be at least one course run in the list. (The course that tripped this up had a B2B run, and we don't want users getting into those, so we filter those out..)
> If getStartDateText gets a course with no runs, output empty string

- courses/serializers/v2/courses.py
- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
n/a
https://github.com/mitodl/mitxonline/pull/2701 included a change that strips out B2B-related course runs and courses from the result set. The AI stuff needs this data, though, and for now we have a limited set of these, so this adds them back in.
The course pages for B2B courses should remain in Draft mode or they will be displayed in the MITx Online catalog.
Make sure you have some courses that have B2B runs in them. Hit the `/api/v2/courses` endpoint - you should see them. You should not see them in the frontend unless the course has a published CMS page.
We will at least need to add some filtering to the enrollment modal to ensure people can't enroll in B2B courseruns. (Or, maybe we have an API key sort of thing for the associated Learn bits that need this data? These are public …
> Don't strip out B2B courses from the API

- authentication/new_serializers.py
- authentication/new_serializers_test.py
Fix missing edx_username when saving profile.
When creating a user profile we need to save edx_username, instead of username field.
> When creating user profile save edx_username

- frontend/public/src/components/UserMenu.js
- frontend/public/src/components/UserMenu_test.js
- frontend/public/src/lib/urls.js
Part of the continuing saga to ~~destroy the One Ring~~ fix https://github.com/mitodl/hq/issues/7273
This updates the frontend to send the user to /logout/oidc instead of /logout when the api gateway is enabled.
You should be able to logout with `MITOL_APIGATEWAY_DISABLE_MIDDLEWARE` enabled or disabled.
> Added logic to send user to the gateway logout url

- b2b/factories.py
- courses/models.py
- courses/serializers/v2/courses.py
- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
- fixtures/b2b.py
Closes mitodl/hq#7563
If you're pulling data for a course that has runs that meet the time requirements for enrollability (start date before now, enrollment start date before now, end dates after now or not set) but are a mix of B2B course runs and regular ones, the `next_run_id` field in the course may return an invalid course run:
- If you're not filtering for a particular B2B organization, you might still get a B2B course run as the next ID if it's the next available run
- If you are filtering on organization, you might get a course run that's not the B2B run
To fix this, this PR updates `first_unexpired_run` to filter out B2B course runs entirely. It also adds a second method, `get_first_unexpired_org_run`, that filters specifically on the user's contracts (as we want to see things …
> Update next_run_id to add B2B course run awareness

- app.json
- main/settings.py
- main/settings_test.py
Closes https://github.com/mitodl/hq/issues/7625
This PR adds `CSRF_COOKIE_DOMAIN` as a configurable setting in `settings.py`. It is not required and defaults to `None`. This is being done to make CSRF to MITx Online possible from our other websites, namely MIT Learn.
- In your `.env` file, set `CSRF_COOKIE_DOMAIN=.odl.local`
- Spin up `mitxonline` on this branch
- Open a Django shell and run the following, after which you should see the cookie domain set to `.odl.local`:
```
from django.conf import settings
settings.CSRF_COOKIE_DOMAIN
```
> Make CSRF_COOKIE_DOMAIN configurable by env variable

- authentication/api_gateway/serializers.py
- authentication/api_gateway/serializers_test.py
- authentication/api_gateway/views_test.py
- openedx/api.py
- openedx/api_test.py
edx username not saved properly
and Fix https://github.com/mitodl/hq/issues/7609
Add create_edx_user to profile creation
Onboarding API should call create_edx_user when the user submits the profile information.
Now it passes the provided username to create_user .
create a new account , fillout  the profile 
You edx user should have a edx_username saved correctly.
The edx api call to create user should succeed.
> save edx_username when creating profile

- users/models.py
- users/models_test.py
Fix https://github.com/mitodl/hq/issues/7610
Update the FaultyOpenEdxUserManager manager to also include users who have edx_username set but have not been synced.
You can test this by updating your OpenEdxUser `has_been_synced` to false and then making sure that the task has picked it up and tried to sync with edx.
> Repair faulty users when OpenEdxUser exists already

- frontend/public/src/components/CourseProductDetailEnroll.js
- frontend/public/src/components/ProgramProductDetailEnroll.js
- frontend/public/src/lib/api.js
- frontend/public/src/lib/api_test.js
- frontend/public/src/lib/queries/util.js
- frontend/staff-dashboard/src/hooks/useDrfDataProvider.ts
- locustfile.py.example
- main/settings.py
N/A
Switches usages of the csrf cookie name to `csrf_mitxonline` to match `settings.py`. It also changes `CSRF_COOKIE_NAME` to be a hardcoded value to ensure this is never set without understanding that support needs to be added for it.
The site should still be functional.
> Switch usages of 'csrftoken' to 'csrf_mitxonline'

- openedx/api.py
- openedx/api_test.py
- poetry.lock
Closes mitodl/hq#7679
This makes sure the user has a valid `OpenEdxUser` record before we try to enroll them in the course. They likely _should_ have one, but there are some instances where they won't, and in those cases this will generate the username.
This uses the generation code that was moved from xPRO into ol-django in this PR: https://github.com/mitodl/ol-django/pull/266 and it will use the user's name to generate the username, with the email as the fallback if they don't have a name for whatever reason. If the user has a username in their profile _and_ it's not an email address, then this will just use the user's username (truncated to the max length for edX usernames, which is usually 30). 
Test with a working edX integration. Create a user that does …
> Auto-generate edX username on enroll

- courses/serializers/v2/programs.py
- courses/serializers/v2/programs_test.py
- courses/views/test_utils.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Fix https://github.com/mitodl/hq/issues/7698
Get start date for a program based on the next avaialble course run
tests should pass
> Get start date for a program based on the next avaialble course run

- courses/views/test_utils.py
- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Fixes https://github.com/mitodl/mitxonline/issues/2774
This fixes a regression introduced in my [previous PR]() that fixed the tests being flaky. At the time the API filtering wasn't being tested in `views_test.py` so this didn't get caught until RC. It's caused by the fact that the filter specifies its own prefetch for `courseruns` when `?courserun_is_enrollable=` is passed. I opted for putting the logic in the `Filterset` itself. It feels like there should be a better way to do this, but it's good enough for now.
- Tests should pass
> Fix prefetches on courses API

- openedx/api.py
- openedx/api_test.py
N/A
This solves a deadlock situation where we were updating the `edx_username` inside of the transaction but that causes openedx's registration API to not be able to see that value when it makes a call to `/user/me` because we haven't committed it to the DB. This moves that code into an equivalent `update()` query outside of the transaction. It also adds a check inside that transaction to bail if `edx_username` is `None` and a similar check to `create_edx_auth_token` that we now need too because it's not guaranteed that method gets called and the user exists in openedx anymore because the username isn't set nor has the user been synced.
You should be able to register for a user locally, the user should be created in openedx, and their social auth uid should match their `edx_username` and …
> Handle edx_username outside transaction

- main/middleware.py
- main/middleware_test.py
Follow-up to https://github.com/mitodl/mitxonline/pull/2786
This PR follows up the above PR based on some testing in RC. The functionality that sets a wildcard domain on the response CSRF cookie is not necessary, since the domain being used is from `HTTP_REFERER` (validated against `CSRF_TRUSTED_ORIGINS`.
You should be able to follow the same steps as in https://github.com/mitodl/mitxonline/pull/2786 and everything should still work. This fix is mostly for RC / Production.
> remove wildcarding functionality in middleware

- b2b/management/commands/b2b_list.py
- config/apisix/apisix.yaml
- docker-compose.yml
n/a
Listing out enrollment codes includes whether or not they've been redeemed, and there was a typo in redeemed, so this fixes it.
This also updates a couple of small things:
- Added a couple more edX hostnames to the extra hosts list: `apps.openedx.odl.local` and `studio.openedx.odl.local`
- Updated the login-required routes for APISIX - instead of wildcarding `/login`, it now uses specific routes so that the OAuth routes continue to work
This only is a problem if you try to list out enrollment codes (`b2b_list contracts --codes <id>`) that have been redeemed, so you'll need to generate a contract that uses enrollment codes - just create one with a price and a learner cap - and then redeem one. You should be able to list out the codes, and it should show you which have been redeemed. …
> Fix typo in the b2b_list command; some minor changes for local deployments

- courses/serializers/v2/courses.py
- courses/serializers/v2/courses_test.py
- ecommerce/serializers.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Related to https://github.com/mitodl/hq/issues/7698
Adding min_price and max_price to the Course and Product Serializer
Go to http://mitxonline.odl.local:8013/api/v2/courses/
and http://mitxonline.odl.local:8013/api/v2/programs/
> Add price range from the cms page to api

- b2b/api.py
- b2b/api_test.py
Closes mitodl/hq#7860
Updates the courseware_url property generation as noted in the original issue.
Automated tests should pass. There's a test to make sure the base URL is in the generated URL now.
Otherwise, create a B2B course run by using the `b2b_contract courseware` command. This will trigger `create_contract_run` and thus will hit the changed code. Once done, the created run should have the proper URL in it. (The readable ID will be urlencoded.)
The original issue notes removing the `OPENEDX_COURSE_BASE_URL` setting and using the API base URL instead - these are completely different, at least on local deployments, so I haven't done this. (Ex: `http://apps.openedx.odl.local:2000/learning/course/course-v1:xPRO+Test1+5T2025/home` is the URL for a course in Tutor locally; if we used …
> Fix the URL generation for B2B course runs

- uwsgi.ini
N/A
Gets rid of this warning:
```
web-1      | *** Operational MODE: preforking+threaded ***
web-1      | /opt/venv/lib/python3.10/site-packages/sentry_sdk/_compat.py:86: Warning: IMPORTANT: We detected the use of uWSGI in preforking mode without thread support. This might lead to crashing workers. Please run uWSGI with both "--enable-threads" and "--py-call-uwsgi-fork-hooks" for full support.
web-1      |   warn(
```
We already have it configured this way in deployed environments.
Run `docker compose up` and you should not see the warning in the output
> Fix sentry + uwsgi warning for localdev

- cms/api.py
- cms/models.py
- cms/wagtail_api/filters.py
- cms/wagtail_api/schema/serializers.py
- cms/wagtail_api/schema/views.py
- cms/wagtail_api/serializers.py
- cms/wagtail_api/urls.py
- cms/wagtail_api/views.py
- courses/serializers/v2/courses.py
- main/settings.py
- main/urls.py
- openapi/hooks.py
- openapi/settings_spectacular.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
https://github.com/mitodl/hq/issues/7865
Enables Wagtail APIs
- Checkout this branch
- Create some data like Courses, Course Runs, Programs, Program Runs, Course Pages in CMS with certificates, instructors, program pages etc
- Now the pages API is available at `/api/v2/pages/`
- You can follow [Wagtail API Usage Guide ](https://docs.wagtail.org/en/stable/advanced_topics/api/v2/usage.html)
- This base URL will return all pages.
- To get a list of CoursePage objects with all fields
- `/api/v2/pages/?fields=*&type=cms.CoursePage`
- To get a list of ProgramPage objects with all fields
- `/api/v2/pages/?fields=*&type=cms.ProgramPage`
- To get a list of CertificatePage objects with all fields
- `/api/v2/pages/?fields=*&type=cms.CertificatePage`
- To get certificate data of specific revision
- …
> feat: enable wagtail API

- courses/factories.py
- courses/models.py
- courses/serializers/v2/programs.py
- courses/serializers/v2/programs_test.py
- courses/views/test_utils.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Closes https://github.com/mitodl/hq/issues/7916
Closes https://github.com/mitodl/hq/issues/7915
This PR:
- Adds `collections` to the API response for `Program` objects, which contains an array of integer ids matching `ProgramCollection` objects that list the `Program` in its `programs` field
- Restructures the `requirements` field in the API response to include keys for both `courses` and `programs`, including `required` and `elective` under that for each type
- Make sure you have some test `Program` objects in your database, at least one of which has another `Program` listed as a requirement
- Create a program collection in Wagtail at Root -> Home Page -> Program Collections
- Add some programs to the collection and click Publish
- Make sure your user is enrolled in the programs
- Visit …
> add collections to program, show program type requirements

- poetry.lock
Fixes https://github.com/mitodl/mitxonline/issues/2840
This updates the scim package to pick up a fix for the scim sync.
Set `MITOL_SCIM_KEYCLOAK_SEARCH_BATCH_SIZE=5` and run `./manage.py scim_sync` and you should see it make a request to search for every 5 users rather than every 100 (the default) and rather than the default of the task size (1000)
> Update scim package to pick up sync search fixes

- ecommerce/management/commands/extend_coupons.py
N/A
We have seen several requests to extend the expiration date for B2B coupons.
Related example issue https://github.mit.edu/mitxonline/mitxonline-issues/issues/970
Try to run the command for previously created coupons and check that the expiration date got updated.
> Add a management command to extend dates on unused courpons

- courses/serializers/v2/certificates.py
- courses/serializers/v2/certificates_test.py
- courses/urls/v2/urls.py
- courses/views/v2/__init__.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
- scripts/test/openapi_spec_check.sh
Closes mitodl/hq#7867
Add certificate retrieval APIs to MITx Online.
There are two, because there are two kinds of certificate:
- `/api/v2/course_certificate/` retrieves a course certificate
- `/api/v2/program_certificate/` retrieves a program certificate
These take the UUID that is returned from the enrollment API and return the certificate data. They should not require authentication. Both the user's specific certificate information is returned and the Wagtail page information for the page.
Manual tests will require you to have a certificate page created, and a certificate issued for a user (for both a course and a program). Once you have that, you should be able to hit the API in the Swagger UI and get the certificate data back as expected. You should not …
> Add certificate retrieval APIs

- main/management/commands/configure_instance.py
Closes https://github.com/mitodl/hq/issues/7985
This PR fixes a bug in the `configure_instance` script in the part that creates the Edx Demonstration Course and E2E Test Course. Currently, these commands pass a single string to the `depts` argument on `create_courseware`. On the other end, in `create_courseware`, this is treated as an array. This causes the string to be split into its individual characters, and a `Department` object is created for each letter. Once it gets to the second course, it hits a letter that has already been used and a collision occurs. This PR simply passes arrays instead.
This is what Django admin for `Department` looks like currently after running `configure_instance`:
After this fix:
- Spin up a fresh instance of `mitxonline`
- Set up OpenEdx and run …
> fix course creation in configure_instance

- courses/views/v1/__init__.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Closes https://github.com/mitodl/hq/issues/8012
This PR adds an explicit `retrieve` view to `UserProgramEnrollmentsViewSet`, setting the required `id` parameter on that and the `destroy` view. The `list` endpoint had the parameter removed, so you can query it without arguments and get all of the program enrollments for the current user.
- Spin up `mitxonline` on this branch
- Create some program enrollments for your user
- Visit `/api/schema/swagger-ui/#/program_enrollments/program_enrollments_list`
- Verify that the listing view requires no parameters and returns all your program enrollments
- Verify that the retrieval and destroy endpoints still require ID and function
> remove id requirement from program enrollment listing view

- courses/serializers/v2/certificates.py
- courses/serializers/v2/certificates_test.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Related to https://github.com/mitodl/hq/issues/8009
This PR replaces the integer ID's on the `course_certificates` and `program_certificates` endpoints for `course_run` and `program` respectively with the serialized representation of the object they represent. For `course_run`, `CourseRunWithCourseSerializer` was used and for `program` I used `ProgramSerializer`.
- Spin up MITx Online on this branch
- Make sure you have sufficient data to test certificates:
- Some test courses (Django admin)
- Some test programs (Django admin)
- A B2B organization with associated programs (Using B2B management commands, see docs for more detail)
- Your user should be enrolled in at least one of these courses and have a grade (Enrollments done in the dashboard UI, grades in Django admin)
- Course run and …
> add extra data to certificate endpoint

- main/settings.py
- openedx/tasks.py
- openedx/tasks_test.py
Fixes https://github.com/mitodl/hq/issues/8207
This adds an environment variable that disables the repair task because it's being problematic right now and unable to complete the bulk of its work until https://github.com/mitodl/mitxonline/pull/2881 lands and we can catch up.
Set `REPAIR_OPENEDX_USERS_FREQUENCY` to something low like `60` (seconds) and when `DISABLE_USER_REPAIR_TASK` is set to true you should see the message "Skipping repair_faulty_openedx_users task as it is disabled" in the logs, if it's false then you should see the task run successfully
> Add flag to disable user repair task

- authentication/backends/apisix_remote_user_org.py
- b2b/api.py
- b2b/tasks.py
- users/models.py
Partially closes mitodl/hq#8222
The `ApisixRemoteOrgUserBackend` calls the API to reconcile the user's organization memberships every time it runs, which is a lot (every request that involves the backend). So, this updates the backend and the API to only perform the reconciliation if it's actually necessary. It caches the org membership for the user in Redis so we can check there rather than hitting the database.
To facilitate this, there is a new cached property in the User model that returns just the user's organization SSO IDs.
The default timeout for cached data is 5 minutes, so ideally try to perform the steps within MITx Online within those 5 minutes. (Or, [adjust your settings](https://docs.djangoproject.com/en/5.2/ref/settings/#std-setting-CACHES-TIMEOUT) so that the timeout is …
> Only reconcile B2B organizations if we need to

- b2b/views/v0/__init__.py
- main/permissions.py
N/A
https://github.com/mitodl/mit-learn/pull/2453 in Learn updates the org dashboard to hit the contracts page API, which requires an admin user; didn't catch this in testing but it breaks the org dashboard if you're not an admin. So, adding a permissions class to allow read-only if authed, read/write if staff permissions.
Should be able to hit `/api/b2b/v0/contracts` and `organizations` as a non-admin, but won't be able to write to them.
Should be able to write to the above if an admin.
> Add an IsAdminOrReadOnly permission set for contracts/orgs

- b2b/admin.py
- b2b/models.py
Closes mitodl/hq#8309
The `ModelAdmin`s for the B2B contract and org models were added in for convenience but were done in a pretty quick, bare-bones fashion. So, these aren't the most usable things in general, and the Contracts page display here throws a 503 in an environment that has a bunch of data in it. 
So, this PR fixes a few issues:
- Limit the display for organization page and course page models so that it's not pulling in a ton of extra data that we don't need, and to limit to the actually relevant fields for these models (stripping out all the Wagtail internal model fields that we don't care about so much)
- Update the list and filtering for these pages so they have some reasonable options
- Makes the contract and org page displays read-only - if you want to edit things, you …
> Fixes for contract/org page displays in Django Admin

- authentication/views_test.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
- users/urls.py
None
A followup for https://github.com/mitodl/mitxonline/pull/2897, It adds the slash at the end of the URL for the userinfo endpoint. Open edX is calling it with slash and MITx Online throws 404.
- Checkout this branch
- Visit `/.well-known/openid-configuration`
- It should return userinfo_endpoint ending with a slash
> fix: append slash to userinfo endpoint

- openedx/api.py
- openedx/api_test.py
Fixes https://github.com/mitodl/mitxonline/issues/2857
Do not make profile updates if openedx user is not synced.
- Checkout master branch and create a user. Do not start Tutor/Open edx so that user is not synced.
- Make changes to the user profile at `/profile/`
- Notice that you get `OpenEdxApiAuth.DoesNotExist` in logs
- Checkout this branch and repeat above. Notice that now you get an info log like `"Skipping user profile update for %s, user has no Open edX account"`
> fix: do not update open edx profile if user is not synced

- cms/wagtail_api/schema/views.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
For. https://github.com/mitodl/hq/issues/8414
Adds readable ID to the params for API requests like https://api.learn.mit.edu/mitxonline/api/v2/pages/?fields=*&type=cms.CoursePage&readable_id=course-v1%3AMITxT%2B7.28.1x
Try hitting `api/v2/pages/?fields=*&type=cms.CoursePage&readable_id={some-readable-id}` Locally; it should work I guess. 
I have also tested it by double checking that the param is included in code generated by https://github.com/mitodl/mitxonline-api-clients
Weird that v0.yaml, v1.yaml, and v2.yaml include all the APIs. We should look into that sometime.
> Improve Wagtail OpenApi Schema

- cms/api.py
- cms/api_test.py
- For https://github.com/mitodl/hq/issues/8414
Makes `feature_image_src` a fully qualified URL so we can use it on other sites (like Learn)
Check that:
- images still work as expected within MITxOnline
- images in the wagtail API responses, e.g., http://api.learn.odl.local:8065/mitxonline/api/v2/pages/?fields=*&type=cms.CoursePage&readable_id=course-v1%3AMITxT%2B7.28.1x-fake, include fully qualified URLs.
> Use absolute URLs for feature_image_source

- openedx/admin.py
- users/admin.py
N/A
This fixes an issue with trying to set the username for users who haven't had their openedx user created yet. It always overrides `desired_edx_username` to be the value of `edx_username`.
- Create a user but don't input an edx username, check their record in django-admin and enter an edx_username.
- Check the database directly and confirm that the `desired_edx_username` field also updated to the same value.
> Fix django admin

- openedx/api_test.py
- users/factories.py
- users/models.py
Part of https://github.com/mitodl/hq/issues/8417
Adds an additional filter to the existing query to filter our users that have never logged in.
- Create a user that has a null `last_login` and has no OpenEdxUser
- Create anotherthat has a non-null `last_login` and has no OpenEdxUser
- When the repair celery task runs, it should only repair the second user
> Only repair users who have logged in at least once

- openedx/api.py
- openedx/api_test.py
[#8527](https://github.com/mitodl/hq/issues/8527)
When OpenEdX returns empty username suggestions for usernames containing non-ASCII characters (like "Nguyễn"), the system was raising an `OpenEdxUserCreateError` instead of falling back to local username generation. This fix implements a fallback mechanism that generates unique usernames locally using random number suffixes when OpenEdX suggestions are unavailable.
- Added `_generate_unique_username()` helper function to modularize username generation logic
- Updated `_create_edx_user_request()` to fall back to local username generation when OpenEdX returns empty suggestions
- Refactored `reconcile_edx_username()` to use the same modular username generation function
1. Create a user with non-ASCII username: `Nguyễn`. Verify the user gets …
> fix: handle non-ascii username collisions

- b2b/api.py
- docs/source/configuration/b2b.rst
https://github.com/mitodl/hq/issues/8631
While working through 8631, I noticed that the re-run code was grabbing the wrong course runs for creating a contract run. We have specific runs that are marked with a run tag of `SOURCE` that should be used for new contract runs, but the API was grabbing the most recent course run. (When this was written, the naming for these wasn't set up yet.) This fixes the lookup to look specifically for a course with a run tag of `SOURCE`, and then fall back to the _first_ course run.
This PR also updates the B2B contract management documentation to include info about the automated course run creation process.
You will need MITx Online and edX running and configured properly to talk to each other. MITx Online also needs to be set up with a service account to …
> Update the B2B course run creation code to explicitly look for a source course

- courses/views/v2/__init__.py
- courses/views/v2/views_test.py
Fixes https://github.com/mitodl/hq/issues/8750
While it's not expected, sometimes the courses API is called with `?org_id=` for an anonymous user, probably due to a session timeout coinciding with a dashboard load. This prevents a 500 error. Will address how to handle the anonymous use case more resiliently in a separate PR since it'll require a new API.
This is a bit complicated to test, so I think I'd say the test I wrote is enough to cover it.
> Courses API w/ org= handle anonymous

- cms/wagtail_api/views.py
- openapi/hooks.py
- openapi/specs/v0.yaml
- openapi/specs/v1.yaml
- openapi/specs/v2.yaml
Small followup to https://github.com/mitodl/mitxonline/pull/2952
Makes url casing more consistent. See code comment.
1. Check that `/api/v2/pages/?type=cms.courspage&fields=*` and `/api/v2/pages/?type=cms.CoursPage&fields=*` are both accessible to anonymous users, and that `/api/v2/pages/?type=cms.courspage&fields=*` shows up int he OpenAPI spec.
2. Similar for programs/certifies.
> Wagtail permissions and url fix

- main/settings.py
N/A
This sets zeal not to raise exceptions normally as we only want that during tests.
You should be able to run the app and hit the home page and no exceptions be raised but warnings should be logged.
> Don't raise zeal exceptions normally

- users/serializers.py
- users/serializers_test.py
Related to https://github.com/mitodl/hq/issues/8492
Allows for a PATCH request to succeed when last name and first name are missing.
Set up your user to have blank first and last name in the LegalAddress part of the profile.
Enroll your user in some course.
Go to dashboard and try to "go to course", you should be able to submit the missing year or country successfully.
Check in the admin or the profile page that the field was successfully updated.
> Removing first and last name requirement for a PATCH request
