mitodl/mitxonline

Dockerfile
runtime.txt

N/A
Upgrades python 3.8 -> 3.9
App should build and run without error

Upgrade python to 3.9.6

---

static/js/components/TopAppBar.js
static/js/components/TopAppBar_test.js
static/js/components/UserMenu.js
static/scss/top-app-bar.scss
static/scss/user-menu.scss

fixes #22
(Required)
Implement logged-ui in the site header

Implement logged-ui in the site header

---

cms/models.py

The course page was not loading so it's just a quick fix of it
Fix course page access (direct link or through home page feature section)
Add courses and choose the course as a featured product on the home page

fix home page feature products section

---

docs/configure_open_edx.md

Closes #31 
This updates the documentation with a setting that was missing. The MM configuration itself already exists over in the MM repo.
N/A, documentation only

Update openedx configuration docs

---

cms/templates/product_page.html
main/templates/footer.html
static/scss/common.scss
static/scss/dashboard.scss
static/scss/footer.scss
static/scss/layout.scss
static/scss/product-details.scss

#91 
- Fixes the styling/layout issues in the footer
- Fixes the layout issues on the dashboard
- Fixes the layout issues on the Product Detail Page
- Removed extra <p> tags from rich text in product detail page
- Removed xPRO's unused style from the footer which was copied over xPRO
Putting simply, these are the things from PDF:
1. All footer text to be `font-weight:400` & spacing Mentioned in PDF
2. For the dashboard page, adjusted the spacing mentioned in the PDF
3. For product page background is set to `white` and spacing adjusted as per PDF
**Note:** There is a pdf file attached to the associated issue which will help out identifying the required styling changes
- Verify it against the changes mentioned in the PDF attached to the ticket.
- Verify the nothing else has been affected by …

fix: styling and layout changes for dashboard, footer and product page

---

main/templates/footer.html
static/scss/footer.scss

#49 
**Invision Designs:**
[Mobile Design](https://projects.invisionapp.com/d/main/#/console/21535972/455488637/preview)
[Desktop Design](https://projects.invisionapp.com/d/main/#/console/21535972/455477372/preview)
- Matches the footer design with the provided invasion screens
- Major changes are in mobile design
- Some changes in desktop/mobile logo spacing
Load any page in the website and look at the footer, it should match with invision design (See Out of scope components in the associated ticket)
**Desktop**
**Mobile**

Added footer design enhancements

---

static/js/containers/pages/DashboardPage.js
static/js/containers/pages/DashboardPage_test.js
static/scss/dashboard.scss

fixes #141 
update empty dashboard message
Visit the dashboard page
**NOW**
**BEFORE**

update empty dashboard message

---

main/context_processors.py
main/settings.py
partials/gtm_body.html
partials/gtm_head.html

#73 
- Adds the missing pieces from the support of GTM
- Removed the duplicate HTML for partials
- Generally, Ports the context processor from the xPRO to pass the GTM/GA config values to the Django templates
**Note:**
I didn't port `GTM` related configuration/code for the checkout/payment part since it's not yet part of MITxOnline.
- This is basically just that addition of the boilerplate code, but to test it you'll have to create accounts on https://tagmanager.google.com and https://analytics.google.com/analytics/web/?authuser=5#/a206499573w284900088p250338982/admin/property/settings.
- Once the accounts are created you will need to set two configuration values `GTM_TRACKING_ID` and `GA_TRACKING_ID` which you will find after creating a project on the GTM console mentioned above and the …

add/enable GTM support

---

static/scss/layout.scss

ticket #142 
Changes the background color to #f5f5f5
Visit SignIn page and verify background colour is #f5f5f5
Visit course page and verify background colour is #f5f5f5

changed background color

---

authentication/views.py
authentication/views_test.py
courses/views/v1/__init__.py
courses/views_test.py
main/constants.py
main/utils.py
static/js/constants.js
static/js/lib/notificationsApi.js
static/js/lib/notificationsApi_test.js

Closes #69 
Adds a welcome message for users that complete authentication for the first time
- Register a new user and complete authentication. You should see a welcome banner that will not show up w/ page reloads after ~20s
- Log into the app with an existing user. You should not be shown the welcome banner

Added welcome message for users that complete first authentication

---

static/js/components/AnonymousMenu.js
static/js/components/AnonymousMenu_test.js
static/js/components/TopAppBar.js
static/js/components/TopAppBar_test.js
static/js/components/UserMenu.js
static/js/components/UserMenu_test.js
static/scss/layout.scss
static/scss/top-app-bar.scss

fixes #118 
improve top-bar menu by removing the duplication of the menu's

improve top-bar menu

---

authentication/serializers.py
authentication/serializers_test.py
main/settings.py

Relevant Ticket #147 
This PR makes Forgot Password case insensitive
- Create new User,
- Follow Sign in process until Password Page.
- Click Forgot password and enter email with some characters in Capital form.
- Verify email is sent.

Make Forgot Password case insensitive

---

main/settings.py

N/A
Enables an existing middleware we have to make sure API responses aren't cached.
Go to the dashboard and verify api responses include the `Cache-Control: private, no-store` header.

Enable no cache for API

---

static/js/components/AnonymousMenu.js
static/js/components/TopAppBar.js
static/js/components/UserMenu.js

#154 
- Fixes accessibility issues with header
- Fixes dropdown button unique id issue highlighted by LightHouse
- Fixes area-label texts
- Fixes `alt` for MIT logo in the header
- Check the accessibility on any page and there should be no complaints regarding the header part.
**After**
**Before**

fix: resolve the accessibility issues pointed out for header component

---

static/js/components/UserMenu.js
static/scss/user-menu.scss

Closes #225 
This accomplishes the following
- Replaces the div element in header component with a button
- Adds relevant styling to the button
This PR can be tested in the following manner
- Login to MITxOnline
- Verify User pull down in included in tab order by pressing tab.
Desktop Pictures

Added feature `Tab to user pulldown menu`

---

static/scss/product-details.scss
static/scss/product-faculty-members.scss

fixes #214 
fix product detail spacing issues on all devices (desktop, tablet and mobile)
Just visit any product detail page with full content
**Desktop**
**Tablet**
**Mobile**

fix product detail spacing issues

---

users/serializers.py
users/serializers_test.py

Closes #289
Removes @ symbol as valid username character, so new users cannot include it in their usernames
- Test that new user creation fails validation if an @ symbol is included in the username
- Test that you can still log in as a user that already has an @ symbol in their username
A data migration will follow this PR

Removed @ symbol as valid username character

---

authentication/serializers.py
authentication/serializers_test.py
authentication/urls.py
authentication/views.py
authentication/views_test.py
main/settings.py
requirements.in
requirements.txt
static/js/containers/pages/settings/AccountSettingsPage.js

Closes #273 
This PR accomplishes the following tasks
- Adds ol-django-authentication app to MITxOnline.
- Removes unused djoser code
This PR can be tested using the following steps
- Create a MITxOnline online account
- Try to change password via `Forgot Password` and verify it works
- Try to change password via `Forgot Password`, Change case of email and verify it works
- Try to change password via Account page and verify `Valid notification is sent`, `Password is changed`, `User remains signed in`

added ol-django-authentication app to MITxOnline

---

static/js/containers/pages/register/RegisterConfirmSentPage.js

@briangrossman can you verify it, Is it good enough as shown in image below.
fixes: #276 
When a screen reader user submits the first account creation form (where they enter their email), they do not get an alert to know that a message "We've sent you email" appears. They do not know that the text on the screen has been updated.
The focus should shift when the page changes to the new content such that the screen reader is redirected to the correct element to read it. In this case, one could shift focus to the h1 "thank you etc" followed by instructions to check eMail, etc. That should be enough.
Test the above criteria while creating an account.

asadiqbal08/ Fix accessibility issue by tabindex to header

---

courses/tasks.py

Closes #313 
Updates sync_courseruns_data name to match the name is settings.
- make a course / course run with same courseware_id both on MIT xOnline and edx-platform  e.g `course-v1:edX+DemoX+Demo_Course`
- then run management command / celery tasks to run the syncs of data
- `docker-compose exec web python manage.py sync_courserun --run=course-v1:edX+DemoX+Demo_Course`
- `courses.tasks.sync_course_runs_data`

updated task name

---

README.md

None.
Fixes a broken Open edX configuration doc link in the README.md
- Check the broken link in the main branch, and then verify in this branch. should be good to go if the links works

docs: fix broken open edx config link

---

.github/workflows/ci.yml
.gitignore
cms/models.py
cms/wagtail_hooks.py
docs/source/conf.py
main/settings.py
pants-plugins/mitol/docs/register.py

N/A
Adds black formatter check to the github actions.

Add black formatting check to CI

---

ecommerce/discounts.py
ecommerce/discounts_test.py
ecommerce/factories.py

added discount abstraction API and tests for those
Fixes #310 
Adds the discount calculation code as an abstract base class, and implementations for four discount types. 
pytest should pass

Added discount abstractions and tests

---

main/templates/footer.html
static/scss/footer.scss
static/scss/variables.scss

#188 
- Adds support footer
- Check that you can see the support footer as mentioned in ticket #188 
- Check that it's visible on all the pages
- Home Page
**Desktop**
**Mobile**
**Tablet**

style: add support footer

---

courses/serializers.py
courses/serializers_test.py
static/js/containers/pages/DashboardPage.js
static/js/containers/pages/DashboardPage_test.js
static/js/factories/course.js
static/scss/dashboard.scss

fixes #369 
Change unsubscrib UI to email settings
(Required)
(Optional)
(Optional)

Change unsubscribe UI to email settings

---

courses/serializers.py
courses/serializers_test.py
static/js/containers/pages/DashboardPage.js
static/js/containers/pages/DashboardPage_test.js
static/js/factories/course.js
static/scss/dashboard.scss

Revert "Change unsubscribe UI to email settings"

---

static/js/containers/pages/DashboardPage.js
static/scss/layout.scss
static/scss/product-details.scss

fixes #379 
fix email settings pop-up references wrong course
Please see the ticket description

fix email settings pop-up references wrong course

---

users/serializers.py

N/A
Ran `black . ` w/ latest version of `black`.
Tests should pass.

Format code since `black` changed regex flag order 🙄

---

ecommerce/urls.py
ecommerce/views/v0/__init__.py
ecommerce/views_test.py
static/js/containers/ProductDetailEnrollApp.js
static/js/containers/ProductDetailEnrollApp_test.js

Fixes #422
This PR ensures there's only ever one product in the cart when a user tries to pay to avoid situations with multiple products.
- Got to a product page and click to purchase the paid version.
- You should be directed to the checkout page.
- Go to a different product and do the same.
- You should end up on the checkout page with only the second product in your cart.

View to add products to the cart and proceed directly to checkout

---

courses/api.py
courses/api_test.py
courses/management/utils.py
courses/views_test.py
openedx/api.py
openedx/api_test.py
openedx/management/commands/retry_edx_enrollment.py

fixes #400 
unsubscribe from course emails after unenroll
Try to enroll / unenroll in a course and see the admin record of it
**Unenroll**
**Enroll**

unsubscribe from course emails after unenroll

---

static/js/containers/pages/checkout/CartPage.js

Fixes the Privacy Policy link in the Order Summary card on the checkout page.
Look at the Privacy Policy link - it should go to /privacy-policy/.

fixing privacy policy link

---

courses/models.py
courses/views/v1/__init__.py
ecommerce/api.py
ecommerce/models.py
ecommerce/views/v0/__init__.py

Fix #447
Check for blocked countries during checkout
in the admin add a BlockedCountry instance for your user's country, and link it to the course you are going to checkout with. 
Try to enroll your user in a course.

Check for blocked countries during checkout

---

ecommerce/discounts.py
ecommerce/discounts_test.py
ecommerce/models.py
ecommerce/views_test.py

These two tests were reworked a bit to make them more reliable - they seemed to work OK locally but would trip up the CI runner:
- test_checkout_result - would fail basket check after processing in the Review state. For testing orders in the Review state, the test creates an order, sets it to Review, and then attempts to create a new basket and processes the order to make sure the basket isn't touched. The new basket sometimes gets created with the same product in it as the old basket, though, which causes it to fail. It doesn't do that now.
- test_discounted_price - needed simplification and a small change to the Discount API to make all the types return a consistent type (they all return Decimal now; the fixed price one would return a bare number).

Adjusts tests to make them more reliable

---

.github/workflows/ci.yml
frontend/staff-dashboard/package.json

N/A
Ensures JS tests run in github actions.
Look at the log output of the github actions and verify the frontend tests are running.

Fix tests on CI

---

frontend/public/package.json
yarn.lock

fixes 
fixes #512
fix video on the course page is not screen-reader accessible

fix video on course page is not screen reader accessible

---

frontend/public/src/components/OrderSummaryCard.js
frontend/public/src/components/forms/ApplyCouponForm.js
frontend/public/src/components/forms/ApplyCouponForm_test.js
frontend/public/src/containers/pages/checkout/CartPage.js
frontend/public/src/containers/pages/checkout/OrderReceiptPage.js

fixes #517 
fixes Ecommerce: Accessibility: Discount code error message is invisible to screen reader

fixes Ecommerce: Accessibility: Discount code error message is invisible to screen reader

---

frontend/public/src/containers/pages/DashboardPage.js

#523 
fixes courses display incorrect date on the dashboard

fixes courses display incorrect date on the dashboard

---

frontend/public/src/containers/pages/DashboardPage.js

fix course ordering on the dashboard 
#523 
Just check with all the course runs in the past or in future

fix course ordering on the dashboard

---

README.md
docs/source/configuration/index.rst
docs/source/configuration/refine_admin.rst

Updates the documentation to add configuration information for Refine.

Adds Refine Admin documentation

---

ecommerce/views/v0/__init__.py
ecommerce/views_test.py

#610 
- Adds logic to handle course links from external checkout e.g. `?course_id=<>`
- Converts the course_id into product and adds that to the cart
- Adds the associated course_id product to the cart and redirects the user to checkout
- With edX:
- Setup edx
- Install the latest external-checkout plugin from https://github.com/mitodl/open-edx-plugins/tree/main/src/ol_openedx_checkout_external (Follow the setup process mentioned in README)
- Setup Course modes in edx (Verified & Audit) & enroll
- Make sure your MITxOnline course run's `courseware_id` matches the edx's course Id and a product against the course run is present
- In edX, You'll see `Upgrade button` click that and you should be redirected to `/cart/add?course_id=?` which should redirect you to checkout page with the product …

feat: update cart to handle products from external checkout

---

ecommerce/views/v0/__init__.py
ecommerce/views_test.py

fixes #612 
If a coupon is entered it should replace the financial aid discount only if it's a higher discount.
- Make sure you have flexible price details for the user and it's applied on the cart
- apply the coupon on the cart.

If a coupon is entered it should replace the financial aid discount only if it's a higher discount.

---

frontend/public/src/lib/urls.js

#620 
Fixes issue found by @pdpinch here: https://github.com/mitodl/mitxonline/pull/633#issuecomment-1161722499
Navigate to any interior page in the app. The Order History link in the top nav menu should work. 
The Order History link should also work on the homepage (it did before, so there shouldn't be a regression here). 
The route for orderHistory was constructed like one of the "hidden" routes (like confirm email, etc.) so the link wasn't rendering properly on internal pages.

Moved orderHistory route and reworked it so it renders properly

---

frontend/staff-dashboard/src/pages/flexible_pricing/list.tsx

fixes: #631 
Fixes the issue for Dropdown `Justification` was not maintaining the state after refresh.

asadiqbal08/Dropdown Justification is not maintaining the state after refresh

---

ecommerce/views_test.py

#643 
Reworks `test_redeem_discount_with_higher_discount` so that it doesn't randomly fail.
Run pytest tests. The affected test should be successful.

Reworks flexible pricing discount test to reduce flakiness

---

README.md

Removes a reference for an 'optional steps' section which is no longer in the README.

Remove missing section link for optional steps

---

docs/source/configuration/open_edx.rst

Add a reference to the default django admin login credentials for `devstack`.  Add steps to define `backend` and `enable` oauth configuration in devstack.  Add instructions on where to update the lms.yml file and inform the reader to first search for existing settings before updating/adding to the file.

Update steps for accessing and configuring devstack

---

docs/source/configuration/open_edx.rst

Revert "Update steps for accessing and configuring devstack"

---

flexiblepricing/api.py
flexiblepricing/api_test.py

#678
Partially implements #678 - updates the flexible pricing application code to consider programs along with courses. If the course belongs to a program, or the request is tied to a program, the application code will look for tiers that apply to the program. 
Flexible Pricing requests for an individual, standalone course should work. If the course is manually added to a program (e.g. via Django Admin), the tiers that are set up for the program should take precedence over the tiers for the course and you should see those discounts when you check out. (You can't buy enrollment in a program at this point so testing tier application through the frontend for a program won't work just yet.)

Flexible Pricing: approved requests should apply to programs

---

cms/models.py
cms/templates/flexiblepricing/flexible_pricing_request_form.html
cms/templates/flexiblepricing/flexible_pricing_request_form_landing.html
frontend/public/scss/common.scss

fixes #709 
Flexible pricing: updates income form

Flexible pricing: updates income form

---

flexiblepricing/views/v0/__init__.py

Fixes https://github.com/mitodl/mitxonline/issues/778
Orders financial assistance requests by most recent first.
- Setup financial assistance for a course following this guide https://github.com/mitodl/hq/discussions/133
- Request financial assistance for the course multiple times.
- Most recent requests will appear first.
(Optional)

online-778 Order flexible prices by most recent first

---

docs/source/configuration/ecommerce.rst

Updates the ecommerce documentation with some specifics which are needed or else errors can occur.

Updated ecommerce docs to include max product price and unique CVN

---

cms/models.py
cms/models_test.py
cms/templates/product_page.html
frontend/public/scss/product-details.scss
frontend/public/src/containers/ProductDetailEnrollApp.js
frontend/public/src/factories/course.js

- #767 
- Follow-up PR of #786 
- Tooltip Title background color fix
- Selected date wrong displayed due to timezone fix
- Selected date will now be persistent on page reload
- Irrelevant course runs in `More Dates` fixed
- In `More Dates` check the tooltip title has now white background
- In `More Dates` Select a date and check the date displayed is correct and not wrong due to timezone difference
- In `More Dates` Select date and reload page check if the date is same as selected
- Edge case After changing the date course run is selected for enrollment. Verify that the course run is not remained same if you change the URL to another course in same browser Tab

More Dates: Tooltip title text, style, irrelevant dates bug fixes #767

---

frontend/staff-dashboard/src/App.tsx

N/A
Hiding the learners tab because it's empty and might be confused as being broken.
Verify the tab has been removed from the staff dashboard navigation.

Remove learners tab from staff dashboard

---

frontend/public/src/components/EnrolledItemCard.js
frontend/public/src/lib/courseApi.js

Fixes #834
Updates the code that finds the flexible pricing request form for a course to return false if there's no marketing page for the course at all. Also updates the code that displays the featured image to skip over it if there's no marketing page. 
*Standalone Course*
1. Create a new course and course run. Do not associate the course with a program. 
2. Enroll a test user in the course run manually (just create the record here in Course Run Enrollments). 
3. View the dashboard. A card for the course should appear as per usual. It will not have a featured image.
*In a Program*
1. Create a new course and course run within a program. The program can be new or extant. You can also reassign an existing course to a program if it also doesn't have a CMS page.
2. Enroll a test user in the …

Fixes empty dashboard issue if there's no CMS page for a course

---

cms/templates/flexiblepricing/flexible_pricing_request_form.html
courses/models.py
ecommerce/views/v0/__init__.py
ecommerce/views_test.py

Fix https://github.com/mitodl/mitxonline/issues/793
Get certificate at reduced price takes the user to basket for checkout.
Fill out the flexible pricing form, receive a discount and test the Get Certificate button. It should take you to chackout page with the product in the cart.

Get certificate at reduced price

---

cms/api.py
cms/commands_test.py
cms/factories.py
cms/management/commands/configure_wagtail.py
cms/models.py
cms/serializers_test.py
courses/factories.py
courses/serializers.py
courses/serializers_test.py
courses/views_test.py
frontend/public/scss/dashboard.scss
frontend/public/src/components/EnrolledItemCard.js
frontend/public/src/flow/courseTypes.js
main/templates/base.html
main/templatetags/startswith.py

Issue #692 #693 
- Enroll in course and create certificate (can be manually created by DB entry)
- Open Learner Dashboard
- Open course look if View Certificate button is there
- Click the View Certificate button, it should open a new certificate window with share options

Learner and anonymous certificate view- issue #692 #693

---

ecommerce/api_test.py

None
There was another commit in the release that made tests in another commit fail.
Fix tests.
All tests should pass.

Fix failing test_order_refund_success_with_ref_num

---

cms/templates/home_page.html
cms/templates/product_page.html
frontend/public/scss/auth.scss
frontend/public/scss/cart.scss
frontend/public/scss/common.scss
frontend/public/scss/course-cards.scss
frontend/public/scss/dashboard.scss
frontend/public/scss/product-details.scss
frontend/public/scss/product-faculty-members.scss
frontend/public/scss/top-app-bar.scss
frontend/public/scss/user-menu.scss
frontend/public/scss/variables.scss
frontend/public/src/components/OrderSummaryCard.js
frontend/public/src/components/forms/ApplyCouponForm.js

https://github.com/mitodl/mitxonline/issues/944
design tweaks requested in https://github.com/mitodl/mitxonline/issues/944
Go to frontend to see the style changes (Reference to css file attached to ticket)
PRICE box, hero-block font size, and margin changes
course card border style change
course card hover
Removed hover on Instruction card (not actionable)
dashboard font size, badge, and button changes
Checkout 
dropdown menu
button hover 
hover on the course title

944 about page design tweaks

---

renovate.json5

Fixes #976 
Fixes the renovate config
Can't test this until it merges to main.

Fix renovate config

---

cms/templates/product_page.html

None. Not worth a ticket for a two word text change
> equest from OGC [Office of General Counsel]: please change first two words from "Due to" to "Because of".
Take a look at an about page.

fix: text change to OFAC disclaimer

---

app.json
requirements.in
requirements.txt

Closes #968 
This bumps the version on the two google sheets libraries to address a code/config issue when using service accounts.
We only have a service account configured in production, so I think it's fine to just verify that the application runs without error.

Bump google sheets versions

---

ecommerce/api.py
ecommerce/views/v0/__init__.py

Fixes #1019 
Wraps the two calls to `fulfill_completed_order` in a transaction and adds a call to `select_for_update` to the order retrieval for fulfillment, so the steps described in #1019 won't result in a 500 error due to a duplicate key violation.
1. Add an item to the cart and start the checkout process.
2. Before paying for the item, use the Back button to navigate back to the cart.
3. Attempt to start the checkout process again.
4. Complete payment.
5. You should be successfully redirected back to your dashboard.

Fixes duplicate key error when returning to cart using back button

---

ecommerce/api.py

https://github.com/mitodl/mitxonline/issues/1021
Per slack conversation, we don't want to log reason code 2xx from payment response as errors, 1xx code should be errors.
reason code is explained in [documentation](https://developer.cybersource.com/library/documentation/dev_guides/Secure_Acceptance_Hosted_Checkout/Secure_Acceptance_Hosted_Checkout.pdf)
make a payment if you want to trigger a specific error?
```
mitxonline-web-1  | [2022-09-22 12:48:11] ERROR 119 [ecommerce.api] api.py:290 - [9a54ad837932] - Transaction was not successful. Transaction ID: 664204087413648xxxxxx  Reason Code:  1xx  Message: xxx 
```

update payment response reason code to log error for 1xx

---

ecommerce/management/commands/find_paid_unenrolled_learners.py
ecommerce/management/commands/generate_legacy_enrollment_codes.py

Fixes #961 
Adds a management command, `generate_legacy_enrollment_codes`, that will generate a 100% off discount code for learners that have paid for a courserun but aren't enrolled for it. (See #960.) The discount codes are:
* 100% off
* One-time use
* Associated with the specified course run
* Set as a user discount (so, barring other discounts, they will autoapply when the learner attempts to purchase the course)
* Formatted `MM-legacy-<username>-<readable_id>`
The generated codes and the email addresses for the learners they apply to are written to a CSV file.
This also adds a management command, `find_paid_unenrolled_learners`, which will look in the _MITxOnline_ database for users that have purchased a courserun but aren't enrolled in it at all. This outputs in a format that can be …

Adds management command to generate enrollment codes for legacy learners

---

ecommerce/templates/mail/product_order_receipt/subject.txt

Fixes #945
Changes the email subject on the receipt emails to "MITx Online Receipt". 
Restart your environment (so the change gets picked up) and check out. The receipt email should be "MITx Online Receipt".

Changes the receipt email subject

---

courses/models.py
ecommerce/mail_api.py
flexiblepricing/mail_api.py

Reverts mitodl/mitxonline#1060

Revert "1044: when referring to a course in email don't include the full course"

---

courses/management/commands/upgrade_eligible_users.py

Related to #1059
Fix a small bug related to the final print out message counting the number of upgraded users.
The same as in #1059

Fix a small bug in upgrade_eligible_users

---

ecommerce/management/commands/generate_legacy_enrollment_codes.py

none but was mentioned in https://github.com/mitodl/hq/discussions/281
Adds two features to the `generate_legacy_enrollment_codes` management command:
- It will now check to see if a code exists for the given user (matching on discount type, redemption type, and amount; product; and user) - if it does, it will skip code creation and emit a message saying as much
- You can now specify the expiration date by passing `--expires <date>` to the command. Dates should be in ISO format (YYYY-MM-DD) though this uses the `dateutil` package so there is some flexibility here. Passed dates are converted to the default timezone (UTC usually). 
1. Generate some codes in the normal fashion. 
2. Re-run the same input file. No new codes should be generated.
3. Delete the generated codes (either directly …

Adding duplicate checking and expiration date on generated enrollment codes

---

ecommerce/management/commands/generate_legacy_enrollment_codes.py

none
Updates the `generate_legacy_enrollment_codes` to make it match learners based on username or email address. This should allow for creating enrollment codes based on a user's social auth record rather than relying on email address (which may be different). 
Generate an input file in the expected format: `<username or email>,<course readable id or MicroMasters import id>`
Then run `generate_legacy_enrollment_codes <input file> <output file>` (and optionally add `--expires` if you want to test expiration dates). The output should contain valid codes for users that are found within MITxOnline.

Updates the generate_legacy_enrollment_codes command to match on username or email

---

ecommerce/admin.py

https://github.com/mitodl/mitxonline/issues/1126
Adds the order reference number to show in the list of orders within the Django Admin interface.
Create an order.  View the order list page within the Django admin interface.

Added reference number to list display

---

courses/admin.py

https://github.com/mitodl/mitxonline/issues/1133
Update 'course run' to use the raw field on CourseRunGrade admin
Go to http://mitxonline.odl.local:8013/admin/courses/courserungrade/

update course run as raw field on CourseRunGrade admin

---

README.md

None
- Adds some information about certificates in the readme
Just check the readme, any typos or grammatical mistakes

docs: add information about certificates management

---

requirements.in
requirements.txt

Fixes #1162
Updates the version for `payment-gateway` to 1.7.1 to incorporate a fix for the username hashing functionality.
1. Create an account with a username that contains a non-ASCII character. (The issue was for a username that had an é in it.) 
2. Attempt to purchase a course.
Your transaction should complete successfully.

Updating version of mitol-django-payment-gateway to 1.7.1

---

courses/management/commands/create_verified_enrollment.py
courses/models.py
ecommerce/api.py
ecommerce/constants.py
ecommerce/models.py

#1109 
This creates a verified enrollment for courses on edx and mitxonline
- Fetch and check out to this branch and make sure edx is configured
- Create a course on Edx and the same on mitxonline
- Add verified course mode in `course modes` on Edx
- Add a `discount code` on mitxonline and run the following command
- `./manage.py create_verified_enrollment --user user_email --run course_run --code enrollment_code`
- make sure to replace `user_email`, `course_run` and `enrollment_code` with appropriate values
- Validate the error messages
- After enrollment validate entries in `Order`, `FulfilledOrder`, `Transaction`, `PaidCourseRun`, `DiscountRedemption` and `CourseRunEnrollment` tables in Django admin

feat: User verified course enrollment

---

frontend/public/package.json
frontend/public/src/components/CartItemCard.js
frontend/public/src/components/EnrolledCourseList.js
frontend/public/src/components/EnrolledCourseList_test.js
frontend/public/src/components/EnrolledItemCard.js
frontend/public/src/components/EnrolledItemCard_test.js
frontend/public/src/components/EnrolledProgramList.js
frontend/public/src/components/EnrolledProgramList_test.js
frontend/public/src/components/GetCertificateButton.js
frontend/public/src/components/NotificationContainer.js
frontend/public/src/components/ProgramCourseInfoCard.js
frontend/public/src/components/ProgramEnrollmentDrawer.js
frontend/public/src/containers/ProductDetailEnrollApp.js
frontend/public/src/containers/ProductDetailEnrollApp_test.js
frontend/public/src/containers/UpsellCardApp.js
frontend/public/src/containers/pages/DashboardPage.js
frontend/public/src/containers/pages/DashboardPage_test.js
frontend/public/src/containers/pages/checkout/CartPage.js
frontend/public/src/containers/pages/profile/EditProfilePage_test.js
frontend/public/src/containers/pages/register/RegisterConfirmPage.js
frontend/public/src/containers/pages/register/RegisterConfirmSentPage.js
frontend/public/src/entry/django.js
frontend/public/src/factories/course.js
frontend/public/src/lib/courseApi.js
frontend/public/src/lib/courseApi_test.js
frontend/public/src/lib/queries/enrollment.js
frontend/public/src/lib/util.js
frontend/public/src/tests_init.js

N/A
This fixes the `fmt` and `fmt:check` commands which were no-ops when run via `yarn workspaces foreach run COMMAND`  because of the `$PWD` prefix, which ended up being the project root in that case.
This PR includes the fix to those commands and the resulting format fixes.

Fix fmt and fmt:check commands

---

courses/forms.py

N/A
This adds back an import I overzealously removed on my original PR which is causing an exception.
- On `main`, go to the django-admin page for a program and click "save", confirm you get an exception
- On this branch, do the same, it should save successfully

Add missing import

---

micromasters_import/README.md
micromasters_import/management/commands/queries/011_import_program_enrollments.sql

https://github.com/mitodl/mitxonline/issues/703
This PR is to create an import script to migrate the program enrollment from MicroMaster
- Add program ID mapping for DEDP to  /admin/micromasters_import/programid/
- follow the README instruction to setup foreign data wrapper locally if haven't already
- then run 
` ./manage.py import_micromasters_data --num 011`
- verify the import records via admin/courses/programenrollment/ 
(Optional)
(Optional)
(Optional)

add migration to import program enrollments from MicroMaster

---

courses/serializers.py
courses/serializers_test.py

Fixes #1203
Fixes an accidental deletion of other program requirements
Verify that you can update the requirements for multiple programs without having the others deleted.

Fix accidental deletion of requirements

---

courses/management/commands/create_courseware.py
courses/models.py
courses/models_test.py
courses/serializers.py
courses/serializers_test.py
docs/source/commands/create_courseware.rst
frontend/public/scss/dashboard.scss
frontend/public/src/components/EnrolledItemCard.js
frontend/public/src/components/EnrolledItemCard_test.js
frontend/public/src/components/ProgramCourseInfoCard.js
frontend/public/src/components/ProgramEnrollmentDrawer.js
frontend/public/src/flow/courseTypes.js
frontend/public/src/lib/courseApi.js
static/images/done.svg

This is a re-do of [the prior PR for this ](https://github.com/mitodl/mitxonline/pull/1198) - see that for details; forgoing the normal template because of that. (I'm reopening this with no code changes because the prior merge went away somehow.)

Re-groups enrollments in the program drawer and adds tags back to enrollments

---

courses/serializers.py

Fixes #1214
Filters initial requirements gathering in `ProgramSerializer` to just courses to prevent an error that was being hit when the node type wasn't a course. Also adds a bit of code to walk the requirements tree if there are nested operators, so courses that are nested in a node are also brought up. 
1. Generate a program with multiple courses and a requirements tree that involves a branch. (For local testing, I cloned the DEDP program from RC.) 
2. Enroll a test user in at least one of the courses in the program.
3. View the dashboard with the programs UI enabled. You should see all the courses that are in the requirements tree in the program drawer.
4. Alternatively, view the API output at `/api/programs/<program id>` or `/api/program_enrollments/` - this should also work.

Adds some code to walk the requirements tree if there are nested operators

---

courses/serializers.py

Fixes #1222 
Adds a check to see if there is a requirements tree for the program before generating the course ID list. (If the program record predated the requirements tree, there wouldn't be a root node and you'd get a 500 error.) 
1. Create a program.
2. Manually delete the requirements tree nodes associated with that program. (For local testing, I did `delete from courses_programrequirement where program_id = ?` where `?` is the program ID in a database shell.) 
3. Try to load the program via the API: `/api/programs/<program id>/` - it should work properly, with an empty set for the requirements list.

Added some checks to ensure there is a requirements tree before walking it

---

.github/workflows/ci.yml
.github/workflows/docs.yml
.github/workflows/production.yml
.github/workflows/release-candiate.yml

Closes #1240 
Changes `ubuntu-latest` to `ubuntu-20.04` in github action files

Change ubuntu-latest to ubuntu-20.04 on all github actions yml files

---

frontend/public/src/components/EnrolledItemCard.js

Closes #1250 
Removes the program ID from the card.
Load the program dashboard. None of the cards should list the program ID.

Removes program readable ID from the card

---

main/management/commands/configure_instance.py

None
Updates the `configure_instance` management command to run `createinitialrevisions` to create initial revisions for the created products. If revisions are not created then we get an error while creating an order.
1. Configure data using `configure_instance`.
2. Add the created product to the cart. 
3. Placing an order raises 500.

Run command to create initial revisions in `configure_instance`

---

cms/templates/certificate_page.html
main/templates/copyright.html
main/templates/footer.html

fix: certificate template improvements

---

frontend/public/src/components/EnrolledItemCard.js

fix: program certificate link text

---

ecommerce/views/v0/__init__.py
ecommerce/views_test.py

Closes #1362
Updates the code that processes discount codes to strip whitespace when looking for the discount code.
Attempt to apply a discount code with spaces at the front and/or back of the code. It should be applied successfully. 
Tests should additionally pass.

Updates discount application code to strip whitespace

---

ecommerce/admin.py
ecommerce/models.py
ecommerce/templates/admin/ecommerce/refund_control_row.html
ecommerce/templates/review_cancel_order_confirm.html
ecommerce/urls.py

We've gotten a few orders that have hit the Review state due to payment processor issues. In these cases, we have to clear the discount redemptions that may exist for the order and change the order status to `canceled`; there wasn't a way to do this via the Django Admin, so you had to drop into a database shell. This adds in a Cancel Order button to the Django admin for these orders, which will do that process for you. 
n/a (but there are 3-4 Zendesk tickets that spurned me on to do this)
* Adds a new Review Order page under Ecommerce in the Django Admin, which will just show orders in Review state
* For orders in Review, adds a button to the button bar titled "Cancel Order" that delivers you to an interstitial page to confirm cancelling the order.
* Model support for this functionality. …

Makes it easier to cancel an order in the Review state

---

ecommerce/admin.py

#1380 
- Adds search filter for discount code in Discount admin model
- Adds list filter for `discount_type` and `redemption_type`, `for_flexible_pricing` in Discount Django Admin model
- Setup this branch
- Verify that you can search discounts based on `discount_code`
- Verify that filters (`discount_type`, `redemption_type`) work fine

feat: add search and filters on Discount admin model

---

.github/workflows/new-issues.yml

N/A
N/A
This adds a github action workflow to add new issues to a [global project on the hq repo](https://github.com/orgs/mitodl/projects/21/views/1) so we can triage them properly before starting on them.
Can't test until it's on `master`, but you can see the same workflow setup on this test repo:
https://github.com/mitodl/workflow-testing/blob/main/.github/workflows/new-issues.yml
And a successful run of that here:
https://github.com/mitodl/workflow-testing/actions/runs/4048796451
Note: the issue this ran for has since been removed from the project.

Add a workflow for new issues

---

README.md

None
Fixes the broken handbook link in the readme.
Visit the update link, It should work fine.

Update handbook link in readme

---

openedx/api.py

#1445 
- Fixes an issue if a user is already enrolled on `edx` but `edx_enrolled` is `false` on `MITxOnline`
- and a `course mode` is expired on `edx` in which a user is enrolled it raises `EdxApiEnrollErrorException`
1. Add the mitxonline user's course enrollment record in edx and mitxonline, but the mitxonline record has to be `Edx enrolled` equal to `false`.  
2. Add edx course mode expiry before any call to `retry_failed_edx_enrollments()`.
3. Validate that no more `EdxApiEnrollErrorException` exception is raised for this case after this PR
4. And `Edx enrolled` will be changed to `true`

fix: retry_failed_edx_enrollments should check for existing enrollments

---

README.md
app.base.json
app.json
authentication/utils.py
frontend/public/src/containers/pages/register/RegisterConfirmPage.js
frontend/public/src/containers/pages/register/RegisterConfirmPage_test.js
main/settings.py
openedx/api.py
users/management/commands/block_users.py
users/management/commands/retire_users.py
users/management/commands/unblock_users.py
users/views_test.py

https://github.com/mitodl/mitxonline/issues/1529
Updates any instances of "mitX Online" to "MITx Online".
I don't think any formatting issues should occur within the UI since any additional space used by "MITx Online" is negligible compared to "mitX Online".

Update references to MITx Online

---

frontend/public/src/lib/api_test.js
yarn.lock

Same as https://github.com/mitodl/mitxonline/pull/1255 but with a unit test included.
Tests should run successfully, application should work as expected.

Update decode uri component from 0.2.0 to 0.2.2

---

app.json
main/settings.py
requirements.in
requirements.txt
sheets/plugins.py
sheets/tasks.py
sheets/tasks_test.py

Fix https://github.com/mitodl/mitxonline/issues/1553
Adds Google Sheet Deferrals library for managing deferrals
Follow the instructions in this [PR](https://github.com/mitodl/ol-django/pull/113)
Or follow the README instructions :https://github.com/mitodl/ol-django/blob/main/src/mitol/google_sheets_deferrals/README.md
Old instructions:
(To install the google-sheets-deferrals before it has been released:
Checkout the branch `ag/install_google_sheets_deferrals`. 
Run `./pants package ::`
Copy `/app/mitol-django-google-sheets-deferrals-2023.1.17.tar.gz` into your mitxonline folder
In requirements.txt add `/app/mitol-django-google-sheets-deferrals-2023.1.17.tar.gz`
In Dockerfile, move `COPY . /app` above `RUN pip install -r requirements.txt -r test_requirements.txt`
Run `docker-compose …

Adding google sheets deferrals library

---

ecommerce/models_test.py

There was a merge and commit that was not formatted correctly in PR 1670.  That PR was merged into the main branch.  This PR does the formatting.

Format the merge of ecommerce model test PR 1670

---

courses/api.py
courses/api_test.py

https://github.com/mitodl/mitxonline/issues/1740
This ensures that a learner is always enrolled into all programs for which the course that the user is enrolling is defined as an elective or requirement.
1. you must have: User, Course, current Course run, Course page, Program with the course defined as a requirement or elective, Program page.
2. Enroll your user into the Course.
3. Un-enroll your user from the Program.
4. Un-enroll your user from the Course.
5. Re-enroll your user into the Course.
6. Verify that your user is enrolled into the Program and that Program displays under the Program tab of the dashboard.

1740: Re-enroll learner into program

---

sheets/README.md

Related to https://github.com/mitodl/mitxonline/pull/1717
Adds documentation on how google sheets work and how to use it
Read [README](https://github.com/mitodl/mitxonline/blob/250943005d86d1545a597d1b06d3a10efdb26279/sheets/README.md)

Sheets functionality and usage description

---

README.md

Closes #1799 
Adds instructions in the README for updating python dependencies with poetry
Read the instructions and evaluate if they are understandable, accurate, and thorough enough

Instructions for updating python dependencies with poetry

---

app.json
frontend/public/package.json
main/settings.py
poetry.lock
pyproject.toml
yarn.lock

updates https://github.com/mitodl/hq/issues/1981
This PR adds posthog to both the js and python dependencies for the project. I am working on a discussion post with instructions on usage.
Make sure the inclusion of these new packages does not break functionality.
Discussion post with more information on usage: https://github.com/mitodl/hq/discussions/2116

Add posthog to repo

---

cms/templates/home_page.html
cms/templates/product_page.html
frontend/public/scss/home-page/home-page-hero.scss
frontend/public/scss/meta-product-page.scss

Updates https://github.com/mitodl/hq/issues/1677 and other related tickets
I've used the bodyclass block to add a class to body so teh body class can be added as needed. This way we can add it to the scss files and change it as needed wtih flags.
Load home page or a product page. Background should be white. Presently it's a sad grey color. Compare vs. RC.

Fix background css on feature flagged areas

---

cms/templates/home_page.html
frontend/public/scss/home-page/featured-product-cards.scss
frontend/public/scss/home-page/home-page-contact-row.scss
frontend/public/scss/home-page/home-page-hero.scss
frontend/public/scss/home-page/home-page-video-component.scss
main/templates/base.html

Closes https://github.com/mitodl/hq/issues/2315
Changes fonts from roboto and montserrat to inter and poppins
Load and make sure the paragraphs are inter and headings are Poppins

Change fonts to new correct fonts for home page

---

frontend/public/scss/footer.scss

https://github.com/mitodl/hq/issues/2251
Fixes new footer mostly for medium view (IPad portrait oriantation) per Bilal's suggestion. 
iPad portrait e.g. 820 x 1180
Compare this branch with https://rc.mitxonline.mit.edu/ for medium view
The layout for other views (large screen, XS screens, desktop and mobile) should look the same as on RC

New design footer css updates

---

courses/management/commands/create_courseware.py

n/a
This adds support for assigning a courseware object created via `create_courseware` to a department or a series of departments. Optionally, you can also specify that the departments should be created if they don't already exist.
Departments are specified with the `-d/--dept/--department` flag. Creating can be toggled on by specifying `--create-depts`. 
With just assignment: run `create_courseware <necessary bits> -d <department name>`. If the department exists, the new object will be assigned to it. If the department does not exist, it won't.
With creation toggled: run `create_courseware <necessary bits> -d <dept name> --create-depts`. The courseware will be created with the department, which will also be created if necessary.
You can specify any number of departments by specifying …

Updates create_courseware to allow you to specify departments (optionally creating them)

---

frontend/public/scss/catalog.scss
frontend/public/src/containers/pages/CatalogPage.js

https://github.com/mitodl/hq/issues/1676
This PR cleans up some of the extraneous CSS on the catalog page.  
The only visible changes this PR makes are:
1. Setting the font family.
2. Slightly decreasing the width of the department filter sidebar and catalog items.
1. Visit http://mitxonline.odl.local:8013/catalog/.
2. Ensure that the page renders correctly for all screen sizes.
3. Ensure that the page is accessible via screen readers and can be navigated with a keyboard.

Catalog page css updates - v1

---

frontend/public/src/components/CourseInfoBox.js

Closes https://github.com/mitodl/hq/issues/2902
There were parts of the More Dates selector that were dependent on enrollments being there, which doesn't happen sometimes (either you're not logged in or you haven't got any), which caused the info box to not display. In addition, if you weren't  enrolled in the course, the additional course dates were still clickable, which we have gone away from. 
Load a course while logged out of the app. The info box should display successfully. 
If the course has multiple course runs, you should be able to expand the list and the additional start dates should not be clickable. This should be the case if you're logged out or if you're logged in and viewing a course you're not enrolled in.

Removing final vestiges of clickable more dates selectors

---

cms/templates/course_list_card.html
frontend/public/scss/product-page/program-courses.scss

https://github.com/mitodl/hq/issues/3362
Changes apply to the program details page.
1. The cursor changes to a pointer when hovering over course cards.
2. The text on the course card remains 100% visible while the course card image's opacity is 50% when not hovering on the card.
1. Configure your local instance to have a program.
2. The program should have 2 courses defined as requirements or electives.
3. The program should have an associated program run which has a start date in the past and end date in the future.
4. Both courses should have course runs with start dates in the past, enrollment start dates in the past, and end dates in the future.
5. The program and courses should all have CMS pages created for them.
6. Navigate to the MITx Online dashboard page.
7. Click on the …

3362: No opacity on program card, pointer when hovering

---

ecommerce/models_test.py

Closes mitodl/hq#2979
After some examination, it was determined that the `test_discount_product_calculation` test was failing because, when testing fixed price discounts, the price specified in the generated discount was greater than the price in the generated product. Since we won't _raise_ a price to make the discount code work, the app correctly just returns back the original price in the `discount_product` call; this was then making the test fail, since that (maybe) wasn't always the case and the test wasn't updated for this. 
There wasn't an issue with the algorithm so this just adjusts the test to assert that the discounted amount is the unchanged product price if the discount amount is greater than the product price for fixed price discounts. This also adds in an explicit test for …

Updated fixed price test to be less flaky

---

courses/views/v2/__init__.py

Fix https://github.com/mitodl/hq/issues/3016
sorting courses and programs by title
make sure you have few courses and programs populated. Notice their ordering.
checkout this branch. The ordering of courses and programs should now be alphabetical.

Catalog: sorting courses and programs by title

---

frontend/public/src/components/EnrolledItemCard.js

Same issue is fixed with this PR as in https://github.com/mitodl/mitxonline/pull/2079.
Resolves keyboard accessibility issue with the program un-enroll modal.

Fix for program unenrollment modal

---

frontend/public/scss/product-page/program-courses.scss

Fix https://github.com/mitodl/hq/issues/3437
Adds cursor pointer and updates the styles to be the same as in [figma](https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?page-id=0%3A1&type=design&node-id=1373-5892&viewport=-424%2C384%2C0.04&t=MY5V7sbddgY6meTt-1&scaling=min-zoom&mode=design).
After:
Before:

Program courses cards styles

---

frontend/public/src/containers/pages/CatalogPage.js

Fixes previous release - small console statement removal.
Left a console.log statement in that was missed by me and in review.
open catalog, should not get the console.log statement - can also search the repo for console.log

remove extraneous console.log statement

---

frontend/public/scss/banner.scss
main/templates/partials/banner.html

https://github.com/mitodl/hq/issues/4012
Improves screen reader accessibility of the site-wide banner.
1. Create a new banner at http://mitxonline.odl.local:8013/cms/snippets/cms/sitebanner/. Ensure that the banner has a hyperlink.
2. Visit http://mitxonline.odl.local:8013/
3. Using a screen reader, tab through the page.  Ensure that the hyperlink in the banner is read by the screen reader prior to the close button.
4. Ensure the banner is properly formatted on different screen sizes.

4012: Improve screen reader accessibility of the site-wide banner.

---

cms/api_test.py

Fixes https://github.com/mitodl/hq/issues/4215
Changes the dates for the future courses so they remain within range of enrollment
Run `docker compose run --rm web pytest cms/api_test.py::test_home_page_featured_products` multiple times to ensure it does not fail

add relational dates to ensure all courses end up getting pulled

---

frontend/public/src/components/forms/ProfileFormFields.js

https://github.com/mitodl/hq/issues/4111
Adds a check on a parameter to ensure that the front-end does not error when the parameter is undefined.
1. Create a user in MITx Online that does not have any profile information specified.  I used my administrator user created from the management command.
2. Enroll the user from step 1 into a course.
3. Visit the dashboard for the user from step 1.
4. Click on the course title for the course from step 2.
5. Verify that you are presented with a modal containing a form for collecting additional profile information.
6. Verify that no console errors are occurring in the browser.

4111: dashboard crashes when user profile is incomplete

---

.github/workflows/docs.yml

Fixes https://github.com/mitodl/hq/issues/4223
Change the python version on the workflow that calls the pants build
Check out the docs action in github actions https://github.com/mitodl/mitxonline/actions/workflows/docs.yml (I had to manually kick it off using this branch, you can as well to test again)

Updating python version to fix pants

---

cms/models.py

NA
I missed one of the feature flag requests while merging https://github.com/mitodl/mitxonline/pull/2211.  This PR will fix that.
App should load with no errors.

Fix missed feature flag after merge 

---

frontend/public/src/components/forms/AddlProfileFieldsForm.js
frontend/public/src/components/forms/ChangeEmailForm.js
frontend/public/src/components/forms/ChangeEmailForm_test.js
frontend/public/src/components/forms/ChangePasswordForm.js
frontend/public/src/components/forms/ChangePasswordForm_test.js
frontend/public/src/components/forms/EditProfileForm.js
frontend/public/src/components/forms/EditProfileForm_test.js
frontend/public/src/components/forms/EmailForm.js
frontend/public/src/components/forms/ProfileFormFields.js
frontend/public/src/components/forms/ProfileFormFields_test.js
frontend/public/src/components/forms/RegisterDetailsForm.js
frontend/public/src/components/forms/RegisterEmailForm.js
frontend/public/src/components/forms/ResetPasswordForm.js
frontend/public/src/containers/pages/login/LoginForgotPasswordConfirmPage.js
frontend/public/src/containers/pages/login/LoginForgotPasswordConfirmPage_test.js
frontend/public/src/containers/pages/register/RegisterAdditionalDetailsPage.js
frontend/public/src/containers/pages/settings/AccountSettingsPage.js
frontend/public/src/containers/pages/settings/AccountSettingsPage_test.js
frontend/public/src/lib/queries/auth.js
frontend/public/src/lib/validation.js
frontend/public/src/lib/validation_test.js

https://github.com/mitodl/hq/issues/4244
https://github.com/mitodl/hq/issues/4272
Documentation: https://docs.google.com/document/d/1W7jYty8HjkaYxSFXoUMF9ZYTOp8eJ4ssmINfgLhQ61Q/edit#heading=h.ie7st6eu9m5w
Go through each form in the application and verify the following:
- Accessibility with a screen reader.
- https://github.com/mitodl/hq/issues/4244 is resolved.
- Requirements outlined in documentation are defined clearly and addressed: https://docs.google.com/document/d/1W7jYty8HjkaYxSFXoUMF9ZYTOp8eJ4ssmINfgLhQ61Q/edit#heading=h.ppw15bxqq3n7

4244: no error message is shown when education level is not specified in additional details modal

---

cms/blocks.py

https://github.com/mitodl/mitxonline/issues/1855
Remove FacultyBlock class

Remove FacultyBlock class

---

frontend/public/scss/common.scss
frontend/public/scss/product-page/product-details.scss

Fix enroll button text color on hover
Fix enroll button text color on hover when not authenticated.

important enroll color on hover

---

frontend/public/scss/common.scss
frontend/public/src/components/CourseProductDetailEnroll.js
frontend/public/src/components/ProgramProductDetailEnroll.js

N/A
Updating the Enroll button to follow the design: https://www.figma.com/proto/Gs4zIhOFv5gVvafawwl6PF/MITx-Online?node-id=4792-207
Go to course about page and hover over the "enroll now" button. It should turn blue on hover keeping the text color white, like all other buttons.

Enroll Now button styles

---

frontend/public/src/components/ProgramInfoBox.js

https://github.com/mitodl/hq/issues/4546
Adds spacing in the program description

Add spacing to program badge

---

frontend/public/scss/cards.scss
frontend/public/scss/dashboard.scss
frontend/public/src/components/CartItemCard.js
frontend/public/src/components/EnrolledItemCard.js
frontend/public/src/containers/pages/DashboardPage.js

https://github.com/mitodl/hq/issues/4545
Fixes the upgrade button formatting on the program drawer
1. Enroll into a program.
2. Go to your dashboard, then program tab, then click on the program.
3. Verify that the "Get certificate" button is formatted under the text for any required course.
4. Verify that the formatting of the same button is unchanged when viewing the course on the course tab of the dashboard.

4545 mitx online program drawercourse upgrade formatting

---

docker-compose.yml

Adds comment to ignore pre-commit secret issue in docker file.
This pre-commit check failure is blocking the current MITx Online release.

Fix pre-commit secret issue

---

.secrets.baseline
frontend/public/src/constants.js
frontend/public/src/containers/pages/profile/EditProfilePage.js

NA
Removes and uses some constants.

Clean up constants

---

cms/models.py
cms/models_test.py
courses/api.py
courses/api_test.py
courses/models.py
courses/models_test.py
courses/serializers/v2/departments.py
courses/utils.py

Related to https://github.com/mitodl/hq/issues/4543
Find all places where we use the definition of an enrollable run.

Clarify enrollable run

---

ecommerce/templates/checkout_interstitial.html
ecommerce/views/v0/__init__.py

https://github.com/mitodl/hq/issues/4099
Moves to a safer location on the page and changes how prices are formatted
Make sure you can get ot the purchase processor without issue

Fix GA4 output for purchase

---

ecommerce/views/v0/__init__.py
ecommerce/views_test.py

N/A
Events are not showing in the GA admin. The values for prices, tax, value, etc should never be strings - or it rejects the data.  I've forced those values as well as written a test to ensure those types.

Change value and add new test for Google Analytics

---

frontend/public/scss/dashboard.scss
frontend/public/src/components/EnrolledItemCard.js
frontend/public/src/components/EnrolledItemCard_test.js
frontend/public/src/components/Loader.js
frontend/public/src/lib/courseApi.js
frontend/public/src/lib/util.js

Fix https://github.com/mitodl/hq/issues/4269
Add Go To Course button to enrolled courses on the dashboard.

Add Go To Course button

---

scripts/heroku-release-phase.sh

N/A
For now, don't run migrations on deploy so we can get the code out.
Code review, test in heroku.

Temporarily don't run migrations

---

ecommerce/templates/checkout_interstitial.html
main/templates/partials/gtm_body.html
main/templates/partials/gtm_head.html

Followup on https://github.com/mitodl/mitxonline/pull/2440
Related to https://github.com/mitodl/hq/issues/4099
removes the debug code and modifies the checkout data layer push.
This can't really be tested.

Adding data layer push for purchase events

---

cms/migrations/0041_populate_min_weeks.py

Fix https://github.com/mitodl/mitxonline/pull/2481
Fix a migration
In the /cms enter "15 months" for length in a course or program page. And make sure `max_weeks`` is empty before you run the migration.
Undo the previous migration if you ran it locally
./manage.py migrate cms 0040
./manage.py migrate cms 0041

Fix up a migration

---

frontend/public/src/components/EnrolledItemCard.js

Fix https://github.com/mitodl/hq/issues/3728
Updating menu title for program enrollment card
go to your dashboard select my programs tab, hover over the menu for the program and the text is updated.

Change menu title for enrolled program card

---

users/serializers.py

Fix https://github.com/mitodl/hq/issues/6677
Match email with iexact filter for a change request
Try to change you email through the "Change Email" form with an existing email by changing to capital letter.
Example:
email@gmail.com
EMAIL@gmail.com

Match email with iexact filter for a change request

---

courses/api.py

Related to https://github.com/mitodl/hq/issues/6736
Fix save and log on enrollments
I tested this locally and will be tested on RC.

Fix deferral error

---

RELEASE.rst
courses/api.py
main/settings.py

Reverts mitodl/mitxonline#2559

Revert "Release 0.112.4"

---

.secrets.baseline
authentication/pipeline/user.py
authentication/pipeline/user_test.py
main/settings.py

Reverts mitodl/mitxonline#2546

Revert "Prevent linking existing user if uid is different"

---

courses/serializers/v1/base.py
courses/serializers/v2/courses.py
courses/serializers/v2/programs.py
openapi/specs/v0.yaml

For https://github.com/mitodl/hq/issues/7004
Fixes some spec issues
Tests should pass. There should be no runtime behavior change.

OpenAPI Schema Fixes

---

.gemini/config.yaml
.gemini/styleguide.md

N/A
This makes Gemini optional but folks can still request it manually to cut down on unwanted PR review noise.

Make gemini optional on PRs

---

main/settings.py

Closes https://github.com/mitodl/hq/issues/7307
Adds `Profile` and `LegalAddress` to the set of created models when a user is authenticated via APISIX.
Create a new user and verify these models get created.

Create profile and legal address on apisix auth

---

app.json
main/settings.py

Fixes https://github.com/mitodl/hq/issues/7358
This adds a missing setting that was causing an error.
- Confirm you hit the error on `main`
- Login via keycloak/apisix and confirm you don't hit the error.

Add missing ALLOWED_REDIRECT_HOSTS variable

---

courses/signals.py
courses/signals_test.py

N/a
This is blocking certificate generation
nothing should break.

Remove configure hubspot command

---

authentication/api_gateway/views_test.py
authentication/social_auth/views_test.py

N/A
Fixes an import error from a previous commit.
Tests should pass.

Fix lazy_fixture error

---

courses/serializers/v1/courses_test.py

N/A
Fixes some other course api tests that were failing due to inconsistent run ordering.

Fix another set of flaky course api tests

---

app.json
frontend/public/src/components/CourseProductDetailEnroll.js
frontend/public/src/components/ProgramProductDetailEnroll.js
frontend/public/src/lib/api.js
frontend/public/src/lib/api_test.js
frontend/public/src/lib/queries/util.js
frontend/staff-dashboard/src/hooks/useDrfDataProvider.ts
locustfile.py.example
main/settings.py
main/settings_test.py

N/A
Reverts 3 previous PRs that added and then attempted to fix CSRF configuration
You should be able to use things like django admin, wagtail, etc locally again. You may need to clear your cookies.

Revert recent CSRF-related changes

---

authentication/api_gateway/serializers.py

None
Create edx user outside db transaction.
- Create user outside db transaction.

fix: create edx user outside db transaction

---

.github/workflows/ci.yml
docker-compose.yml

N/A
Trying to clean up the PR backlog, this unused code for elasticsearch was causing renovate to try to update it: https://github.com/mitodl/mitxonline/pull/2094, plus there's no point in pulling down the images and running it for CI.

Removes remnants of Elasticsearch

---

frontend/public/src/lib/courseApi.js
frontend/public/src/lib/courseApi_test.js

Fix https://github.com/mitodl/hq/issues/8420
Allow a program with electives to appear as completed on the learners certificate.
create a program with no electives.
Setup required courses only. 
Then create a course certificate and grades for all required courses in the program.
Your program record should show as completed.

If program has no electives should still be completed

---

ecommerce/management/commands/generate_discount_code.py

N/A
Adds an example command that is easy to modify and use for coupon generation.
testing not required

Add an example command to run for discount code generation

---

poetry.lock
pyproject.toml

ol-infra change. 
Installs [granian](https://github.com/emmett-framework/granian) into the container. Doesn't make any changes to dev environments / configurations.

feat: Install granian.
